-- Director interview/positioning dictionaries. Repeatable and non-destructive.
INSERT INTO system_dict_type (name, type, status, remark, creator, create_time, updater, update_time, deleted)
SELECT seed.name, seed.type, 0, 'ZSJOS 编导 Demo 表单字典；管理员可维护', 'V129', NOW(), 'V129', NOW(), b'0'
FROM (
 SELECT '编导证书' name,'zsjos_director_certificate' type UNION ALL SELECT '证书实操能力','zsjos_certificate_practice' UNION ALL SELECT '性别','zsjos_gender' UNION ALL SELECT '视频能力','zsjos_video_skill' UNION ALL SELECT '直播经验','zsjos_live_experience' UNION ALL SELECT '拍摄设备','zsjos_shooting_equipment' UNION ALL SELECT '自媒体时间投入','zsjos_media_time' UNION ALL SELECT '出镜意愿','zsjos_appearance_willingness' UNION ALL SELECT '购买动机','zsjos_purchase_motivation' UNION ALL SELECT '交付风险','zsjos_delivery_risk' UNION ALL SELECT '核心身份标签','zsjos_identity_tag' UNION ALL SELECT '现有素材清单','zsjos_position_material' UNION ALL SELECT '定位时间投入','zsjos_time_investment' UNION ALL SELECT '表达能力','zsjos_expression_ability' UNION ALL SELECT '执行稳定性','zsjos_execution_stability' UNION ALL SELECT '定位风险标注','zsjos_position_risk' UNION ALL SELECT '人设类型','zsjos_persona_type' UNION ALL SELECT '目标人群','zsjos_target_audience' UNION ALL SELECT '内容支柱','zsjos_content_pillar' UNION ALL SELECT '视频内容形式','zsjos_video_format' UNION ALL SELECT '图文内容形式','zsjos_image_text_format' UNION ALL SELECT '布尔选择','zsjos_boolean_choice'
) seed WHERE NOT EXISTS (SELECT 1 FROM system_dict_type x WHERE x.type=seed.type AND x.deleted=b'0');

INSERT INTO system_dict_data (sort,label,value,dict_type,status,color_type,creator,create_time,updater,update_time,deleted)
SELECT seed.sort,seed.label,seed.value,seed.dict_type,0,'default','V129',NOW(),'V129',NOW(),b'0'
FROM (
 SELECT 10 sort,'营养师' label,'nutritionist' value,'zsjos_director_certificate' dict_type UNION ALL SELECT 20,'健康管理师','health_manager','zsjos_director_certificate' UNION ALL SELECT 30,'心理咨询师','psychological','zsjos_director_certificate' UNION ALL SELECT 40,'执业药师','licensed_pharmacist','zsjos_director_certificate' UNION ALL SELECT 50,'中医适宜技术','tcm_technique','zsjos_director_certificate' UNION ALL SELECT 60,'康复理疗','rehabilitation','zsjos_director_certificate' UNION ALL SELECT 70,'暂无','none','zsjos_director_certificate'
 UNION ALL SELECT 10,'有实操能力（可配餐/接个案）','practical','zsjos_certificate_practice' UNION ALL SELECT 20,'仅理论、无实操','theory_only','zsjos_certificate_practice'
 UNION ALL SELECT 10,'男','male','zsjos_gender' UNION ALL SELECT 20,'女','female','zsjos_gender'
 UNION ALL SELECT 10,'会','yes','zsjos_video_skill' UNION ALL SELECT 20,'不会','no','zsjos_video_skill'
 UNION ALL SELECT 10,'做过直播','experienced','zsjos_live_experience' UNION ALL SELECT 20,'没做过','none','zsjos_live_experience'
 UNION ALL SELECT 10,'相机','camera','zsjos_shooting_equipment' UNION ALL SELECT 20,'手机','phone','zsjos_shooting_equipment' UNION ALL SELECT 30,'三脚架','tripod','zsjos_shooting_equipment' UNION ALL SELECT 40,'收音麦','microphone','zsjos_shooting_equipment' UNION ALL SELECT 50,'补光灯','light','zsjos_shooting_equipment' UNION ALL SELECT 60,'暂无设备','none','zsjos_shooting_equipment'
 UNION ALL SELECT 10,'A（8h+/周）','high','zsjos_media_time' UNION ALL SELECT 20,'B（4-8h/周）','medium','zsjos_media_time' UNION ALL SELECT 30,'C（<4h/周）','low','zsjos_media_time'
 UNION ALL SELECT 10,'愿意出镜','willing','zsjos_appearance_willingness' UNION ALL SELECT 20,'条件式出镜','conditional','zsjos_appearance_willingness' UNION ALL SELECT 30,'不愿意','unwilling','zsjos_appearance_willingness'
 UNION ALL SELECT 10,'副业','side_business','zsjos_purchase_motivation' UNION ALL SELECT 20,'获客能力','customer_acquisition','zsjos_purchase_motivation' UNION ALL SELECT 30,'考证咨询','exam_consulting','zsjos_purchase_motivation' UNION ALL SELECT 40,'IP','ip','zsjos_purchase_motivation' UNION ALL SELECT 50,'技能实操','practical_skill','zsjos_purchase_motivation' UNION ALL SELECT 60,'其他','other','zsjos_purchase_motivation'
 UNION ALL SELECT 10,'拖延','delay','zsjos_delivery_risk' UNION ALL SELECT 20,'怕出镜','camera_shy','zsjos_delivery_risk' UNION ALL SELECT 30,'怕熟人','familiarity_shy','zsjos_delivery_risk' UNION ALL SELECT 40,'不会剪辑','no_editing','zsjos_delivery_risk' UNION ALL SELECT 50,'合规敏感','compliance','zsjos_delivery_risk' UNION ALL SELECT 60,'退款风险','refund','zsjos_delivery_risk'
 UNION ALL SELECT 10,'专业背书型','professional','zsjos_identity_tag' UNION ALL SELECT 20,'学习成长型','learning_growth','zsjos_identity_tag' UNION ALL SELECT 30,'家庭实践型','family_practice','zsjos_identity_tag' UNION ALL SELECT 40,'职业转型型','career_transition','zsjos_identity_tag' UNION ALL SELECT 50,'技能实操型','skill_practice','zsjos_identity_tag' UNION ALL SELECT 60,'政策咨询型','policy_consulting','zsjos_identity_tag'
 UNION ALL SELECT 10,'学习笔记','study_notes','zsjos_position_material' UNION ALL SELECT 20,'实操视频','practice_video','zsjos_position_material' UNION ALL SELECT 30,'职业场景','work_scene','zsjos_position_material' UNION ALL SELECT 40,'家庭场景','family_scene','zsjos_position_material' UNION ALL SELECT 50,'备考记录','exam_record','zsjos_position_material' UNION ALL SELECT 60,'群聊截图','chat_screenshot','zsjos_position_material' UNION ALL SELECT 70,'课程页面','course_page','zsjos_position_material' UNION ALL SELECT 80,'打卡记录','checkin_record','zsjos_position_material'
 UNION ALL SELECT 10,'A（8h+）','high','zsjos_time_investment' UNION ALL SELECT 20,'B（4-8h）','medium','zsjos_time_investment' UNION ALL SELECT 30,'C（<4h）','low','zsjos_time_investment'
 UNION ALL SELECT 10,'好','good','zsjos_expression_ability' UNION ALL SELECT 20,'一般','average','zsjos_expression_ability' UNION ALL SELECT 30,'较弱','weak','zsjos_expression_ability'
 UNION ALL SELECT 10,'稳定','stable','zsjos_execution_stability' UNION ALL SELECT 20,'一般','average','zsjos_execution_stability'
 UNION ALL SELECT 10,'高期待','high_expectation','zsjos_position_risk' UNION ALL SELECT 20,'低执行','low_execution','zsjos_position_risk' UNION ALL SELECT 30,'合规风险','compliance','zsjos_position_risk' UNION ALL SELECT 40,'表达弱','weak_expression','zsjos_position_risk' UNION ALL SELECT 50,'无素材','no_material','zsjos_position_risk' UNION ALL SELECT 60,'其他','other','zsjos_position_risk'
 UNION ALL SELECT 10,'零基础学习成长号','beginner_growth','zsjos_persona_type' UNION ALL SELECT 20,'考证备考陪伴号','exam_companion','zsjos_persona_type' UNION ALL SELECT 30,'宝妈/副业转型号','mother_sidejob','zsjos_persona_type' UNION ALL SELECT 40,'技能实操成长号','skill_growth','zsjos_persona_type' UNION ALL SELECT 50,'职业升级号','career_upgrade','zsjos_persona_type' UNION ALL SELECT 60,'轻创客资引流号','light_lead_gen','zsjos_persona_type' UNION ALL SELECT 70,'轻创实践记录号','light_practice','zsjos_persona_type' UNION ALL SELECT 80,'本地服务/咨询号','local_service','zsjos_persona_type' UNION ALL SELECT 90,'专业IP老师号','professional_ip','zsjos_persona_type' UNION ALL SELECT 100,'事业化经营号','business_operation','zsjos_persona_type' UNION ALL SELECT 110,'信息避坑/资料福利号','information_guide','zsjos_persona_type'
 UNION ALL SELECT 10,'A类：专业强/想赚提成/已有客资或门店','A','zsjos_target_audience' UNION ALL SELECT 20,'B类：备考中/宝妈上班族/中年转型','B','zsjos_target_audience' UNION ALL SELECT 30,'C类：刚报名/无经验/不敢讲/不出镜','C','zsjos_target_audience'
 UNION ALL SELECT 10,'学习笔记','study_notes','zsjos_content_pillar' UNION ALL SELECT 20,'备考打卡','exam_checkin','zsjos_content_pillar' UNION ALL SELECT 30,'个人故事','personal_story','zsjos_content_pillar' UNION ALL SELECT 40,'实操练习','practice','zsjos_content_pillar' UNION ALL SELECT 50,'职业经验','career_experience','zsjos_content_pillar' UNION ALL SELECT 60,'报考问答','exam_qa','zsjos_content_pillar' UNION ALL SELECT 70,'轻创过程','light_process','zsjos_content_pillar' UNION ALL SELECT 80,'场景问题','scene_problem','zsjos_content_pillar' UNION ALL SELECT 90,'专业观点','professional_view','zsjos_content_pillar' UNION ALL SELECT 100,'品牌故事','brand_story','zsjos_content_pillar' UNION ALL SELECT 110,'考试避坑','exam_pitfall','zsjos_content_pillar'
 UNION ALL SELECT 10,'口播','talking_head','zsjos_video_format' UNION ALL SELECT 20,'vlog','vlog','zsjos_video_format' UNION ALL SELECT 30,'实拍','live_shoot','zsjos_video_format' UNION ALL SELECT 40,'剧情','drama','zsjos_video_format' UNION ALL SELECT 50,'混剪','mixed_edit','zsjos_video_format'
 UNION ALL SELECT 10,'学员实拍','student_photo','zsjos_image_text_format' UNION ALL SELECT 20,'设计','design','zsjos_image_text_format'
 UNION ALL SELECT 10,'是','yes','zsjos_boolean_choice' UNION ALL SELECT 20,'否','no','zsjos_boolean_choice'
) seed WHERE NOT EXISTS (SELECT 1 FROM system_dict_data x WHERE x.dict_type=seed.dict_type AND x.value=seed.value AND x.deleted=b'0');

INSERT INTO zsjos_schema_version (version, description, checksum, installed_at)
SELECT 'V129','seed director form dictionaries',SHA2('V129__seed_director_form_dictionaries.sql',256),NOW()
WHERE NOT EXISTS (SELECT 1 FROM zsjos_schema_version WHERE version='V129');
