-- UTF-8. V191: material library, content review batches, and student-scoped partner invitations.
-- Migration-Owner: ai
-- Dependencies/order: apply after V185. This migration owns the material-library schema and metadata.
-- Data scope: additive ZSJOS schema, four confirmed material type rows per enabled tenant, two
-- administrator-maintained dictionary types, the nine confirmed profession options, menu metadata,
-- compatible legacy content-page grants, and schema-version records. BPM categories are
-- provisioned through BpmCategoryApi when the application initializes each tenant.
-- It does not seed material instances, review batches, invitations, or role identities. The default
-- viral-account schema is generated by MaterialTenantInitializer after application startup.
-- Repeatability: tables, columns, indexes, configuration rows, menus, packages, and markers are guarded.
-- Recovery: forward-only once material/content versions reference this schema; hide menus and retain data on rollback.

SET NAMES utf8mb4;

DROP PROCEDURE IF EXISTS `zsjos_v191_add_column`;
DELIMITER $$
CREATE PROCEDURE `zsjos_v191_add_column`(
  IN p_table varchar(64), IN p_column varchar(64), IN p_definition text
)
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema=DATABASE() AND table_name=p_table AND column_name=p_column
  ) THEN
    SET @zsjos_v191_ddl=CONCAT('ALTER TABLE `',p_table,'` ADD COLUMN `',p_column,'` ',p_definition);
    PREPARE zsjos_v191_stmt FROM @zsjos_v191_ddl;
    EXECUTE zsjos_v191_stmt;
    DEALLOCATE PREPARE zsjos_v191_stmt;
  END IF;
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS `zsjos_v191_add_index`;
DELIMITER $$
CREATE PROCEDURE `zsjos_v191_add_index`(
  IN p_table varchar(64), IN p_index varchar(64), IN p_definition text
)
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.statistics
    WHERE table_schema=DATABASE() AND table_name=p_table AND index_name=p_index
  ) THEN
    SET @zsjos_v191_ddl=CONCAT('ALTER TABLE `',p_table,'` ADD ',p_definition);
    PREPARE zsjos_v191_stmt FROM @zsjos_v191_ddl;
    EXECUTE zsjos_v191_stmt;
    DEALLOCATE PREPARE zsjos_v191_stmt;
  END IF;
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS `zsjos_v191_apply`;
DELIMITER $$
CREATE PROCEDURE `zsjos_v191_apply`()
BEGIN
  DECLARE v_menu_id int DEFAULT 80010;
  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    ROLLBACK;
    RESIGNAL;
  END;

  IF NOT EXISTS (SELECT 1 FROM `zsjos_schema_version` WHERE `version`='V185')
     OR NOT EXISTS (SELECT 1 FROM `zsjos_module_schema_version`
                    WHERE `module_code`='core' AND `version`='V185') THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='V191 requires V185 in both schema-version registries';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM `system_menu` WHERE `id`=6735 AND `deleted`=b'0') THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='V191 requires ZSJOS menu root 6735';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM `system_menu` WHERE `id`=7022 AND `deleted`=b'0') THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='V191 requires media student page 7022';
  END IF;
  IF EXISTS (
    SELECT 1 FROM `system_menu` menu_row WHERE menu_row.`id` BETWEEN 80010 AND 80040
      AND (menu_row.`type` <> CASE WHEN menu_row.`id`=80010 THEN 1
                                    WHEN menu_row.`id` BETWEEN 80011 AND 80015 OR menu_row.`id`=80040 THEN 2
                                    ELSE 3 END
        OR menu_row.`parent_id` <> CASE menu_row.`id`
             WHEN 80010 THEN 6735
             WHEN 80011 THEN 80010 WHEN 80012 THEN 80010 WHEN 80013 THEN 80010
             WHEN 80014 THEN 80010 WHEN 80015 THEN 80010
             WHEN 80016 THEN 80011 WHEN 80017 THEN 80011 WHEN 80018 THEN 80011
             WHEN 80019 THEN 80012 WHEN 80020 THEN 80012
             WHEN 80021 THEN 80011 WHEN 80022 THEN 80011 WHEN 80023 THEN 80011
             WHEN 80024 THEN 80013 WHEN 80025 THEN 80013 WHEN 80026 THEN 80013
             WHEN 80027 THEN 80013 WHEN 80028 THEN 80014 WHEN 80029 THEN 80014
             WHEN 80030 THEN 80014 WHEN 80031 THEN 80013
             WHEN 80032 THEN 80015 WHEN 80033 THEN 80015 WHEN 80034 THEN 80015
             WHEN 80035 THEN 80015 WHEN 80036 THEN 80015 WHEN 80037 THEN 7022
             WHEN 80038 THEN 80015 WHEN 80039 THEN 80014 WHEN 80040 THEN 80010 END
        OR COALESCE(menu_row.`permission`,'') <> CASE menu_row.`id`
             WHEN 80010 THEN '' WHEN 80011 THEN 'zsjos:material:query'
             WHEN 80012 THEN 'zsjos:material:manage' WHEN 80013 THEN 'zsjos:material-type:query'
             WHEN 80014 THEN 'zsjos:material-import:query' WHEN 80015 THEN 'zsjos:content-review:query'
             WHEN 80016 THEN 'zsjos:material:create' WHEN 80017 THEN 'zsjos:material:update'
             WHEN 80018 THEN 'zsjos:material:submit' WHEN 80019 THEN 'zsjos:material:disable'
             WHEN 80020 THEN 'zsjos:material:restore' WHEN 80021 THEN 'zsjos:material:like'
             WHEN 80022 THEN 'zsjos:material:favorite' WHEN 80023 THEN 'zsjos:material:reference'
             WHEN 80024 THEN 'zsjos:material-type:create' WHEN 80025 THEN 'zsjos:material-type:update'
             WHEN 80026 THEN 'zsjos:material-schema:update' WHEN 80027 THEN 'zsjos:material-schema:publish'
             WHEN 80028 THEN 'zsjos:material-import:download' WHEN 80029 THEN 'zsjos:material-import:preview'
             WHEN 80030 THEN 'zsjos:material-import:commit' WHEN 80031 THEN 'zsjos:content-review:config'
             WHEN 80032 THEN 'zsjos:content-review:create' WHEN 80033 THEN 'zsjos:content-review:submit'
             WHEN 80034 THEN 'zsjos:content-review:director-review'
             WHEN 80035 THEN 'zsjos:content-review:final-review'
             WHEN 80036 THEN 'zsjos:content-review:publish-register'
             WHEN 80037 THEN 'zsjos:partner-invitation:create-student'
             WHEN 80038 THEN 'zsjos:content-review:query-all'
             WHEN 80039 THEN 'zsjos:material-import:error-download'
             WHEN 80040 THEN 'zsjos:content:query' END
        OR COALESCE(menu_row.`path`,'') <> CASE menu_row.`id`
             WHEN 80010 THEN 'material-library' WHEN 80011 THEN 'browse' WHEN 80012 THEN 'manage'
             WHEN 80013 THEN 'types' WHEN 80014 THEN 'imports' WHEN 80015 THEN 'content-review'
             WHEN 80040 THEN 'content-production' ELSE '' END)
  ) THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='V191 menu ID range is occupied';
  END IF;
  IF EXISTS (
    SELECT 1 FROM `system_menu` WHERE `id` NOT BETWEEN 80010 AND 80040 AND `deleted`=b'0'
      AND `permission` IN ('zsjos:material:query','zsjos:material:manage','zsjos:material-type:query',
        'zsjos:material-import:query','zsjos:content-review:query','zsjos:material:create',
        'zsjos:material:update','zsjos:material:submit','zsjos:material:disable','zsjos:material:restore',
        'zsjos:material:like','zsjos:material:favorite','zsjos:material:reference','zsjos:material-type:create',
        'zsjos:material-type:update','zsjos:material-schema:update','zsjos:material-schema:publish',
        'zsjos:material-import:download','zsjos:material-import:preview','zsjos:material-import:commit',
        'zsjos:content-review:config','zsjos:content-review:create','zsjos:content-review:submit',
        'zsjos:content-review:director-review','zsjos:content-review:final-review',
        'zsjos:content-review:publish-register','zsjos:partner-invitation:create-student',
        'zsjos:content-review:query-all','zsjos:material-import:error-download','zsjos:content:query')
  ) THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='V191 permission is already owned by another menu';
  END IF;

  CREATE TABLE IF NOT EXISTS `zsjos_material_type` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '素材类型编号',
    `code` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '稳定类型编码',
    `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '类型名称',
    `description` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '类型说明',
    `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态：0启用 1停用',
    `current_schema_version_id` bigint DEFAULT NULL COMMENT '当前已发布模板版本',
    `bpm_process_definition_key` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '素材审批流程定义 Key',
    `allow_manual_create` bit(1) NOT NULL DEFAULT b'1',
    `allow_import` bit(1) NOT NULL DEFAULT b'0',
    `allow_auto_collect` bit(1) NOT NULL DEFAULT b'0',
    `recommendation_enabled` bit(1) NOT NULL DEFAULT b'0',
    `recommendation_config_json` json DEFAULT NULL COMMENT '推荐规则配置',
    `version` int NOT NULL DEFAULT 0,
    `creator` varchar(64) DEFAULT '', `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '', `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0', `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_material_type_code` (`tenant_id`,`code`,`deleted`),
    KEY `idx_material_type_status` (`tenant_id`,`status`,`id`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='素材类型';

  CREATE TABLE IF NOT EXISTS `zsjos_material_schema_version` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '素材模板版本编号',
    `material_type_id` bigint NOT NULL,
    `version_no` int NOT NULL,
    `status` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'draft/published/archived',
    `fields_json` json NOT NULL COMMENT '字段定义快照',
    `schema_hash` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
    `published_by_user_id` bigint DEFAULT NULL,
    `published_at` datetime DEFAULT NULL,
    `version` int NOT NULL DEFAULT 0,
    `creator` varchar(64) DEFAULT '', `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '', `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0', `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_material_schema_version` (`tenant_id`,`material_type_id`,`version_no`,`deleted`),
    KEY `idx_material_schema_status` (`tenant_id`,`material_type_id`,`status`,`id`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='不可变素材表单模板版本';

  CREATE TABLE IF NOT EXISTS `zsjos_material` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '素材编号',
    `material_no` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '素材业务编号',
    `material_type_id` bigint NOT NULL,
    `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '素材库标题',
    `cover_snapshot_json` json DEFAULT NULL,
    `summary` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `source` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'MANUAL/IMPORT/CONTENT_REVIEW',
    `source_business_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `source_business_version_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `status` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'DRAFT/IN_APPROVAL/EFFECTIVE/REJECTED/DISABLED',
    `current_draft_version_id` bigint DEFAULT NULL,
    `current_effective_version_id` bigint DEFAULT NULL,
    `owner_user_id` bigint NOT NULL,
    `like_count` bigint NOT NULL DEFAULT 0,
    `favorite_count` bigint NOT NULL DEFAULT 0,
    `reference_count` bigint NOT NULL DEFAULT 0,
    `pinned` bit(1) NOT NULL DEFAULT b'0',
    `priority` int NOT NULL DEFAULT 0,
    `disabled_reason` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `disabled_at` datetime DEFAULT NULL,
    `disabled_by_user_id` bigint DEFAULT NULL,
    `version` int NOT NULL DEFAULT 0,
    `creator` varchar(64) DEFAULT '', `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '', `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0', `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_material_no` (`tenant_id`,`material_no`,`deleted`),
    UNIQUE KEY `uk_material_source` (`tenant_id`,`material_type_id`,`source`,`source_business_id`,`source_business_version_id`,`deleted`),
    KEY `idx_material_list` (`tenant_id`,`material_type_id`,`status`,`pinned`,`priority`,`id`),
    KEY `idx_material_owner` (`tenant_id`,`owner_user_id`,`status`,`id`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='素材主记录';

  CREATE TABLE IF NOT EXISTS `zsjos_material_version` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '素材内容版本编号',
    `material_id` bigint NOT NULL,
    `version_no` int NOT NULL,
    `schema_version_id` bigint NOT NULL,
    `status` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'DRAFT/IN_APPROVAL/EFFECTIVE/REJECTED',
    `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
    `cover_snapshot_json` json DEFAULT NULL,
    `summary` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `values_json` json NOT NULL,
    `field_snapshot_json` json NOT NULL,
    `dict_snapshot_json` json NOT NULL,
    `file_snapshot_json` json NOT NULL,
    `search_text` mediumtext COLLATE utf8mb4_unicode_ci,
    `content_hash` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
    `process_definition_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `process_definition_key` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `process_definition_version` int DEFAULT NULL,
    `process_instance_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `business_key` varchar(160) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `submitted_by_user_id` bigint DEFAULT NULL,
    `submitted_at` datetime DEFAULT NULL,
    `effective_at` datetime DEFAULT NULL,
    `rejected_at` datetime DEFAULT NULL,
    `rejection_reason` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `version` int NOT NULL DEFAULT 0,
    `creator` varchar(64) DEFAULT '', `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '', `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0', `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_material_content_version` (`tenant_id`,`material_id`,`version_no`,`deleted`),
    UNIQUE KEY `uk_material_process_instance` (`tenant_id`,`process_instance_id`),
    UNIQUE KEY `uk_material_business_key` (`tenant_id`,`business_key`),
    KEY `idx_material_version_state` (`tenant_id`,`material_id`,`status`,`id`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='不可变素材内容版本';

  CREATE TABLE IF NOT EXISTS `zsjos_material_dimension` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `material_version_id` bigint NOT NULL,
    `dimension_key` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'account_type/profession/account_stage',
    `dimension_value` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
    `label_snapshot` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
    `unlimited` bit(1) NOT NULL DEFAULT b'0',
    `creator` varchar(64) DEFAULT '', `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '', `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0', `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_material_dimension` (`tenant_id`,`material_version_id`,`dimension_key`,`dimension_value`,`deleted`),
    KEY `idx_material_dimension_match` (`tenant_id`,`dimension_key`,`dimension_value`,`material_version_id`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='素材推荐维度投影';

  CREATE TABLE IF NOT EXISTS `zsjos_material_field_index` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `material_version_id` bigint NOT NULL,
    `field_key` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
    `group_index` int NOT NULL DEFAULT -1 COMMENT '-1 表示非重复组字段',
    `value_code` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `label_snapshot` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `text_value` text COLLATE utf8mb4_unicode_ci,
    `number_value` decimal(24,6) DEFAULT NULL,
    `date_value` date DEFAULT NULL,
    `datetime_value` datetime DEFAULT NULL,
    `creator` varchar(64) DEFAULT '', `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '', `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0', `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_material_field_lookup` (`tenant_id`,`field_key`,`value_code`,`material_version_id`),
    KEY `idx_material_field_number` (`tenant_id`,`field_key`,`number_value`,`material_version_id`),
    KEY `idx_material_field_date` (`tenant_id`,`field_key`,`date_value`,`material_version_id`),
    KEY `idx_material_field_datetime` (`tenant_id`,`field_key`,`datetime_value`,`material_version_id`),
    KEY `idx_material_field_version` (`tenant_id`,`material_version_id`,`field_key`,`group_index`,`id`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='素材动态字段结构化索引';

  CREATE TABLE IF NOT EXISTS `zsjos_material_file` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `material_version_id` bigint NOT NULL,
    `field_key` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
    `group_index` int NOT NULL DEFAULT -1 COMMENT '-1 表示非重复组字段',
    `infra_file_id` bigint NOT NULL,
    `file_url_snapshot` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `original_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
    `content_type` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
    `file_size` bigint NOT NULL,
    `uploaded_by_user_id` bigint NOT NULL,
    `creator` varchar(64) DEFAULT '', `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '', `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0', `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_material_file_ref` (`tenant_id`,`material_version_id`,`field_key`,`group_index`,`infra_file_id`,`deleted`),
    KEY `idx_material_file_version` (`tenant_id`,`material_version_id`,`field_key`,`group_index`,`id`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='素材版本文件引用快照';

  CREATE TABLE IF NOT EXISTS `zsjos_material_approval_round` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `material_version_id` bigint NOT NULL,
    `round_no` int NOT NULL,
    `status` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL,
    `process_definition_id` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
    `process_definition_key` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
    `process_definition_version` int NOT NULL,
    `process_instance_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `business_key` varchar(160) COLLATE utf8mb4_unicode_ci NOT NULL,
    `last_event_key` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `submitted_by_user_id` bigint NOT NULL,
    `submitted_at` datetime NOT NULL,
    `concluded_at` datetime DEFAULT NULL,
    `result_reason` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `creator` varchar(64) DEFAULT '', `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '', `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0', `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_material_approval_round` (`tenant_id`,`material_version_id`,`round_no`,`deleted`),
    UNIQUE KEY `uk_material_approval_process` (`tenant_id`,`process_instance_id`),
    KEY `idx_material_approval_state` (`tenant_id`,`status`,`id`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='素材业务审批轮次';

  CREATE TABLE IF NOT EXISTS `zsjos_material_like` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `material_id` bigint NOT NULL,
    `user_id` bigint NOT NULL,
    `active` bit(1) NOT NULL DEFAULT b'1',
    `liked_at` datetime NOT NULL,
    `unliked_at` datetime DEFAULT NULL,
    `version` int NOT NULL DEFAULT 0,
    `creator` varchar(64) DEFAULT '', `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '', `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0', `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_material_like_user` (`tenant_id`,`material_id`,`user_id`),
    KEY `idx_material_like_active` (`tenant_id`,`user_id`,`active`,`material_id`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='素材点赞明细';

  CREATE TABLE IF NOT EXISTS `zsjos_material_favorite` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `material_id` bigint NOT NULL,
    `user_id` bigint NOT NULL,
    `active` bit(1) NOT NULL DEFAULT b'1',
    `favorited_at` datetime NOT NULL,
    `unfavorited_at` datetime DEFAULT NULL,
    `version` int NOT NULL DEFAULT 0,
    `creator` varchar(64) DEFAULT '', `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '', `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0', `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_material_favorite_user` (`tenant_id`,`material_id`,`user_id`),
    KEY `idx_material_favorite_active` (`tenant_id`,`user_id`,`active`,`material_id`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='素材收藏明细';

  CREATE TABLE IF NOT EXISTS `zsjos_material_reference` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `material_version_id` bigint NOT NULL,
    `target_content_version_id` bigint NOT NULL,
    `referenced_by_user_id` bigint NOT NULL,
    `copied_fields_json` json NOT NULL,
    `idempotency_key` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
    `referenced_at` datetime NOT NULL,
    `creator` varchar(64) DEFAULT '', `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '', `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0', `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_material_reference_target` (`tenant_id`,`material_version_id`,`target_content_version_id`),
    UNIQUE KEY `uk_material_reference_idempotency` (`tenant_id`,`idempotency_key`),
    KEY `idx_material_reference_content` (`tenant_id`,`target_content_version_id`,`id`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='素材字段引用明细';

  CREATE TABLE IF NOT EXISTS `zsjos_material_import_batch` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `batch_no` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
    `material_type_id` bigint NOT NULL,
    `schema_version_id` bigint NOT NULL,
    `source_file_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
    `source_file_hash` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
    `status` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'PREVIEWED/COMMITTED',
    `total_count` int NOT NULL DEFAULT 0,
    `success_count` int NOT NULL DEFAULT 0,
    `failure_count` int NOT NULL DEFAULT 0,
    `preview_rows_json` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
    `idempotency_key` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
    `created_by_user_id` bigint NOT NULL,
    `confirmed_by_user_id` bigint DEFAULT NULL,
    `confirmed_at` datetime DEFAULT NULL,
    `version` int NOT NULL DEFAULT 0,
    `creator` varchar(64) DEFAULT '', `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '', `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0', `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_material_import_no` (`tenant_id`,`batch_no`,`deleted`),
    UNIQUE KEY `uk_material_import_idempotency` (`tenant_id`,`idempotency_key`,`deleted`),
    KEY `idx_material_import_list` (`tenant_id`,`material_type_id`,`status`,`id`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='素材 Excel 导入批次';

  CREATE TABLE IF NOT EXISTS `zsjos_material_import_error` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `batch_id` bigint NOT NULL,
    `sheet_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
    `row_no` int NOT NULL,
    `field_key` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `error_code` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
    `error_message` varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL,
    `row_snapshot_json` json DEFAULT NULL,
    `creator` varchar(64) DEFAULT '', `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '', `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0', `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_material_import_error` (`tenant_id`,`batch_id`,`row_no`,`id`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='素材导入逐行错误';

  CREATE TABLE IF NOT EXISTS `zsjos_content_review_config` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `process_definition_key` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `director_task_key` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `final_task_key` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `production_material_type_code` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'production_content',
    `material_field_mapping_json` json DEFAULT NULL COMMENT '生产内容到动态素材字段的受控映射',
    `material_default_values_json` json DEFAULT NULL COMMENT '自动收录时的管理员默认字段值',
    `version` int NOT NULL DEFAULT 0,
    `creator` varchar(64) DEFAULT '', `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '', `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0', `tenant_id` bigint NOT NULL DEFAULT 0,
    `active_tenant_id` bigint GENERATED ALWAYS AS (CASE WHEN `deleted`=b'0' THEN `tenant_id` ELSE NULL END) STORED,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_content_review_config_tenant` (`active_tenant_id`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='生产内容批审配置';

  CREATE TABLE IF NOT EXISTS `zsjos_content_review_batch` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `batch_no` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
    `account_id` bigint NOT NULL,
    `operator_user_id` bigint NOT NULL,
    `director_user_id` bigint DEFAULT NULL COMMENT '提交时冻结的责任编导',
    `relation_snapshot_json` json DEFAULT NULL COMMENT '提交时冻结的编导运营关系',
    `context_snapshot_json` json DEFAULT NULL COMMENT '提交时冻结的账号、模板和审核配置',
    `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'DRAFT/DIRECTOR_REVIEW/FINAL_REVIEW/COMPLETED/REJECTED',
    `current_stage` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL,
    `process_definition_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `process_definition_key` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `process_definition_version` int DEFAULT NULL,
    `process_instance_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `business_key` varchar(160) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `last_event_key` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `submitted_at` datetime DEFAULT NULL,
    `director_completed_at` datetime DEFAULT NULL,
    `final_completed_at` datetime DEFAULT NULL,
    `finalized_at` datetime DEFAULT NULL,
    `version` int NOT NULL DEFAULT 0,
    `creator` varchar(64) DEFAULT '', `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '', `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0', `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_content_review_batch_no` (`tenant_id`,`batch_no`,`deleted`),
    UNIQUE KEY `uk_content_review_process` (`tenant_id`,`process_instance_id`),
    UNIQUE KEY `uk_content_review_business_key` (`tenant_id`,`business_key`),
    KEY `idx_content_review_list` (`tenant_id`,`status`,`director_user_id`,`id`),
    KEY `idx_content_review_operator` (`tenant_id`,`operator_user_id`,`status`,`id`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='生产内容批审批次';

  CREATE TABLE IF NOT EXISTS `zsjos_content_review_batch_item` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `batch_id` bigint NOT NULL,
    `content_id` bigint NOT NULL,
    `content_version_id` bigint NOT NULL,
    `sort_no` int NOT NULL,
    `content_snapshot_json` json NOT NULL,
    `director_decision` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `director_comment` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `director_reviewed_by_user_id` bigint DEFAULT NULL,
    `director_reviewed_at` datetime DEFAULT NULL,
    `final_decision` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `final_comment` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `collect_material` bit(1) NOT NULL DEFAULT b'0',
    `collection_snapshot_json` json DEFAULT NULL COMMENT '终审勾选时冻结的完整素材准备结果',
    `final_reviewed_by_user_id` bigint DEFAULT NULL,
    `final_reviewed_at` datetime DEFAULT NULL,
    `collected_material_id` bigint DEFAULT NULL,
    `collected_material_version_id` bigint DEFAULT NULL,
    `result_status` varchar(24) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `published_platform_url` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `published_at` datetime DEFAULT NULL,
    `published_by_user_id` bigint DEFAULT NULL,
    `version` int NOT NULL DEFAULT 0,
    `creator` varchar(64) DEFAULT '', `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '', `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0', `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_content_review_item` (`tenant_id`,`batch_id`,`content_version_id`,`deleted`),
    KEY `idx_content_review_item_batch` (`tenant_id`,`batch_id`,`sort_no`,`id`),
    KEY `idx_content_review_item_content` (`tenant_id`,`content_id`,`content_version_id`),
    KEY `idx_content_review_item_version` (`tenant_id`,`content_version_id`,`batch_id`,`deleted`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='生产内容批审条目';

  CREATE TABLE IF NOT EXISTS `zsjos_content_version_file` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `content_version_id` bigint NOT NULL,
    `field_key` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'cover/deliverable',
    `sort_no` int NOT NULL,
    `infra_file_id` bigint NOT NULL,
    `file_url_snapshot` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `original_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `content_type` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `file_size` bigint DEFAULT NULL,
    `uploaded_by_user_id` bigint DEFAULT NULL,
    `creator` varchar(64) DEFAULT '', `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '', `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0', `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_content_version_file` (`tenant_id`,`content_version_id`,`field_key`,`infra_file_id`,`deleted`),
    KEY `idx_content_version_file_order` (`tenant_id`,`content_version_id`,`field_key`,`sort_no`,`id`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='生产内容版本文件绑定';

  CALL `zsjos_v191_add_column`('zsjos_content_version','title_snapshot',
    'varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT ''标题快照'' AFTER `stage`');
  CALL `zsjos_v191_add_column`('zsjos_content_version','topic_snapshot',
    'varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT ''选题快照'' AFTER `title_snapshot`');
  CALL `zsjos_v191_add_column`('zsjos_content_version','cover_snapshot_json',
    'json DEFAULT NULL COMMENT ''封面文件快照'' AFTER `topic_snapshot`');
  CALL `zsjos_v191_add_column`('zsjos_content_version','deliverable_snapshot_json',
    'json DEFAULT NULL COMMENT ''成品视频或图文快照'' AFTER `deliverable_url`');
  CALL `zsjos_v191_add_column`('zsjos_content_version','lead_resource_url',
    'varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT ''引流资料 HTTPS 链接'' AFTER `script_text`');
  CALL `zsjos_v191_add_column`('zsjos_content_version','planned_publish_at',
    'datetime DEFAULT NULL COMMENT ''预计发布时间'' AFTER `lead_resource_url`');
  CALL `zsjos_v191_add_column`('zsjos_content_version','frozen_at',
    'datetime DEFAULT NULL COMMENT ''进入批审后的冻结时间'' AFTER `planned_publish_at`');
  ALTER TABLE `zsjos_content` MODIFY COLUMN `current_version_no` int NOT NULL DEFAULT 0;

  CALL `zsjos_v191_add_column`('zsjos_partner_invitation','invitation_scene',
    'varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT ''GENERAL'' COMMENT ''GENERAL/STUDENT_PARTNER'' AFTER `invite_code`');
  CALL `zsjos_v191_add_column`('zsjos_partner_invitation','student_person_id',
    'bigint DEFAULT NULL COMMENT ''学员 Person 编号'' AFTER `invitation_scene`');
  CALL `zsjos_v191_add_column`('zsjos_partner_invitation','student_name_snapshot',
    'varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT ''邀请时学员原姓名快照'' AFTER `student_person_id`');
  CALL `zsjos_v191_add_column`('zsjos_partner_invitation','student_mobile_snapshot',
    'varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT ''邀请时学员原手机号快照'' AFTER `student_name_snapshot`');
  CALL `zsjos_v191_add_column`('zsjos_partner_invitation','initiated_by_director_user_id',
    'bigint DEFAULT NULL COMMENT ''发起邀请的责任编导'' AFTER `student_mobile_snapshot`');
  CALL `zsjos_v191_add_column`('zsjos_partner_invitation','assignment_context_json',
    'json DEFAULT NULL COMMENT ''邀请时分配上下文快照'' AFTER `initiated_by_director_user_id`');
  CALL `zsjos_v191_add_column`('zsjos_partner_invitation','active_student_person_id',
    'bigint GENERATED ALWAYS AS (CASE WHEN `invitation_scene`=''STUDENT_PARTNER'' AND `status`=''active'' AND `deleted`=b''0'' THEN `student_person_id` ELSE NULL END) STORED AFTER `assignment_context_json`');

  ALTER TABLE `zsjos_partner_invitation`
    MODIFY COLUMN `assigned_operator_user_id` bigint DEFAULT NULL COMMENT '普通邀请的归属运营；学员邀请为空',
    MODIFY COLUMN `assigned_operator_name_snapshot` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '普通邀请归属运营姓名快照';
  CALL `zsjos_v191_add_index`('zsjos_partner_invitation','idx_tenant_student_scene_status',
    'KEY `idx_tenant_student_scene_status` (`tenant_id`,`student_person_id`,`invitation_scene`,`status`,`id`)');
  CALL `zsjos_v191_add_index`('zsjos_partner_invitation','uk_tenant_active_student_invitation',
    'UNIQUE KEY `uk_tenant_active_student_invitation` (`tenant_id`,`active_student_person_id`)');
  CALL `zsjos_v191_add_index`('zsjos_content_review_batch_item','idx_content_review_item_version',
    'KEY `idx_content_review_item_version` (`tenant_id`,`content_version_id`,`batch_id`,`deleted`)');
  IF (SELECT COUNT(*) FROM information_schema.tables
      WHERE table_schema=DATABASE() AND table_name IN (
        'zsjos_material_type','zsjos_material_schema_version','zsjos_material','zsjos_material_version',
        'zsjos_material_dimension','zsjos_material_field_index','zsjos_material_file',
        'zsjos_material_approval_round','zsjos_material_like','zsjos_material_favorite',
        'zsjos_material_reference','zsjos_material_import_batch','zsjos_material_import_error',
        'zsjos_content_review_config','zsjos_content_review_batch','zsjos_content_review_batch_item',
        'zsjos_content_version_file')) <> 17 THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='V191 material/content-review tables are incomplete';
  END IF;
  IF EXISTS (
    SELECT 1
    FROM JSON_TABLE(
      '[{"table":"zsjos_material_type","columns":["id","code","name","description","status","current_schema_version_id","bpm_process_definition_key","allow_manual_create","allow_import","allow_auto_collect","recommendation_enabled","recommendation_config_json","version","creator","create_time","updater","update_time","deleted","tenant_id"]},{"table":"zsjos_material_schema_version","columns":["id","material_type_id","version_no","status","fields_json","schema_hash","published_by_user_id","published_at","version","creator","create_time","updater","update_time","deleted","tenant_id"]},{"table":"zsjos_material","columns":["id","material_no","material_type_id","title","cover_snapshot_json","summary","source","source_business_id","source_business_version_id","status","current_draft_version_id","current_effective_version_id","owner_user_id","like_count","favorite_count","reference_count","pinned","priority","disabled_reason","disabled_at","disabled_by_user_id","version","creator","create_time","updater","update_time","deleted","tenant_id"]},{"table":"zsjos_material_version","columns":["id","material_id","version_no","schema_version_id","status","title","cover_snapshot_json","summary","values_json","field_snapshot_json","dict_snapshot_json","file_snapshot_json","search_text","content_hash","process_definition_id","process_definition_key","process_definition_version","process_instance_id","business_key","submitted_by_user_id","submitted_at","effective_at","rejected_at","rejection_reason","version","creator","create_time","updater","update_time","deleted","tenant_id"]},{"table":"zsjos_material_dimension","columns":["id","material_version_id","dimension_key","dimension_value","label_snapshot","unlimited","creator","create_time","updater","update_time","deleted","tenant_id"]},{"table":"zsjos_material_field_index","columns":["id","material_version_id","field_key","group_index","value_code","label_snapshot","text_value","number_value","date_value","datetime_value","creator","create_time","updater","update_time","deleted","tenant_id"]},{"table":"zsjos_material_file","columns":["id","material_version_id","field_key","group_index","infra_file_id","file_url_snapshot","original_name","content_type","file_size","uploaded_by_user_id","creator","create_time","updater","update_time","deleted","tenant_id"]},{"table":"zsjos_material_approval_round","columns":["id","material_version_id","round_no","status","process_definition_id","process_definition_key","process_definition_version","process_instance_id","business_key","last_event_key","submitted_by_user_id","submitted_at","concluded_at","result_reason","creator","create_time","updater","update_time","deleted","tenant_id"]},{"table":"zsjos_material_like","columns":["id","material_id","user_id","active","liked_at","unliked_at","version","creator","create_time","updater","update_time","deleted","tenant_id"]},{"table":"zsjos_material_favorite","columns":["id","material_id","user_id","active","favorited_at","unfavorited_at","version","creator","create_time","updater","update_time","deleted","tenant_id"]},{"table":"zsjos_material_reference","columns":["id","material_version_id","target_content_version_id","referenced_by_user_id","copied_fields_json","idempotency_key","referenced_at","creator","create_time","updater","update_time","deleted","tenant_id"]},{"table":"zsjos_material_import_batch","columns":["id","batch_no","material_type_id","schema_version_id","source_file_name","source_file_hash","status","total_count","success_count","failure_count","preview_rows_json","idempotency_key","created_by_user_id","confirmed_by_user_id","confirmed_at","version","creator","create_time","updater","update_time","deleted","tenant_id"]},{"table":"zsjos_material_import_error","columns":["id","batch_id","sheet_name","row_no","field_key","error_code","error_message","row_snapshot_json","creator","create_time","updater","update_time","deleted","tenant_id"]},{"table":"zsjos_content_review_config","columns":["id","process_definition_key","director_task_key","final_task_key","production_material_type_code","material_field_mapping_json","material_default_values_json","version","creator","create_time","updater","update_time","deleted","tenant_id","active_tenant_id"]},{"table":"zsjos_content_review_batch","columns":["id","batch_no","account_id","operator_user_id","director_user_id","relation_snapshot_json","context_snapshot_json","status","current_stage","process_definition_id","process_definition_key","process_definition_version","process_instance_id","business_key","last_event_key","submitted_at","director_completed_at","final_completed_at","finalized_at","version","creator","create_time","updater","update_time","deleted","tenant_id"]},{"table":"zsjos_content_review_batch_item","columns":["id","batch_id","content_id","content_version_id","sort_no","content_snapshot_json","director_decision","director_comment","director_reviewed_by_user_id","director_reviewed_at","final_decision","final_comment","collect_material","collection_snapshot_json","final_reviewed_by_user_id","final_reviewed_at","collected_material_id","collected_material_version_id","result_status","published_platform_url","published_at","published_by_user_id","version","creator","create_time","updater","update_time","deleted","tenant_id"]},{"table":"zsjos_content_version_file","columns":["id","content_version_id","field_key","sort_no","infra_file_id","file_url_snapshot","original_name","content_type","file_size","uploaded_by_user_id","creator","create_time","updater","update_time","deleted","tenant_id"]}]',
      '$[*]' COLUMNS (
        table_name varchar(64) PATH '$.table',
        columns_json json PATH '$.columns'
      )
    ) expected_table
    CROSS JOIN JSON_TABLE(
      expected_table.columns_json,
      '$[*]' COLUMNS (column_name varchar(64) PATH '$')
    ) expected_column
    LEFT JOIN information_schema.columns actual_column
      ON actual_column.table_schema=DATABASE()
     AND actual_column.table_name=expected_table.table_name
     AND actual_column.column_name=expected_column.column_name
    WHERE actual_column.column_name IS NULL
  ) THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='V191 material/content-review table columns are incomplete';
  END IF;
  IF EXISTS (
    SELECT 1
    FROM JSON_TABLE(
      '[{"table":"zsjos_material_type","index":"uk_material_type_code","columns":"tenant_id,code,deleted","nonUnique":0},{"table":"zsjos_material_type","index":"idx_material_type_status","columns":"tenant_id,status,id","nonUnique":1},{"table":"zsjos_material_schema_version","index":"uk_material_schema_version","columns":"tenant_id,material_type_id,version_no,deleted","nonUnique":0},{"table":"zsjos_material_schema_version","index":"idx_material_schema_status","columns":"tenant_id,material_type_id,status,id","nonUnique":1},{"table":"zsjos_material","index":"uk_material_no","columns":"tenant_id,material_no,deleted","nonUnique":0},{"table":"zsjos_material","index":"uk_material_source","columns":"tenant_id,material_type_id,source,source_business_id,source_business_version_id,deleted","nonUnique":0},{"table":"zsjos_material","index":"idx_material_list","columns":"tenant_id,material_type_id,status,pinned,priority,id","nonUnique":1},{"table":"zsjos_material","index":"idx_material_owner","columns":"tenant_id,owner_user_id,status,id","nonUnique":1},{"table":"zsjos_material_version","index":"uk_material_content_version","columns":"tenant_id,material_id,version_no,deleted","nonUnique":0},{"table":"zsjos_material_version","index":"uk_material_process_instance","columns":"tenant_id,process_instance_id","nonUnique":0},{"table":"zsjos_material_version","index":"uk_material_business_key","columns":"tenant_id,business_key","nonUnique":0},{"table":"zsjos_material_version","index":"idx_material_version_state","columns":"tenant_id,material_id,status,id","nonUnique":1},{"table":"zsjos_material_dimension","index":"uk_material_dimension","columns":"tenant_id,material_version_id,dimension_key,dimension_value,deleted","nonUnique":0},{"table":"zsjos_material_dimension","index":"idx_material_dimension_match","columns":"tenant_id,dimension_key,dimension_value,material_version_id","nonUnique":1},{"table":"zsjos_material_field_index","index":"idx_material_field_lookup","columns":"tenant_id,field_key,value_code,material_version_id","nonUnique":1},{"table":"zsjos_material_field_index","index":"idx_material_field_number","columns":"tenant_id,field_key,number_value,material_version_id","nonUnique":1},{"table":"zsjos_material_field_index","index":"idx_material_field_date","columns":"tenant_id,field_key,date_value,material_version_id","nonUnique":1},{"table":"zsjos_material_field_index","index":"idx_material_field_datetime","columns":"tenant_id,field_key,datetime_value,material_version_id","nonUnique":1},{"table":"zsjos_material_field_index","index":"idx_material_field_version","columns":"tenant_id,material_version_id,field_key,group_index,id","nonUnique":1},{"table":"zsjos_material_file","index":"uk_material_file_ref","columns":"tenant_id,material_version_id,field_key,group_index,infra_file_id,deleted","nonUnique":0},{"table":"zsjos_material_file","index":"idx_material_file_version","columns":"tenant_id,material_version_id,field_key,group_index,id","nonUnique":1},{"table":"zsjos_material_approval_round","index":"uk_material_approval_round","columns":"tenant_id,material_version_id,round_no,deleted","nonUnique":0},{"table":"zsjos_material_approval_round","index":"uk_material_approval_process","columns":"tenant_id,process_instance_id","nonUnique":0},{"table":"zsjos_material_approval_round","index":"idx_material_approval_state","columns":"tenant_id,status,id","nonUnique":1},{"table":"zsjos_material_like","index":"uk_material_like_user","columns":"tenant_id,material_id,user_id","nonUnique":0},{"table":"zsjos_material_like","index":"idx_material_like_active","columns":"tenant_id,user_id,active,material_id","nonUnique":1},{"table":"zsjos_material_favorite","index":"uk_material_favorite_user","columns":"tenant_id,material_id,user_id","nonUnique":0},{"table":"zsjos_material_favorite","index":"idx_material_favorite_active","columns":"tenant_id,user_id,active,material_id","nonUnique":1},{"table":"zsjos_material_reference","index":"uk_material_reference_target","columns":"tenant_id,material_version_id,target_content_version_id","nonUnique":0},{"table":"zsjos_material_reference","index":"uk_material_reference_idempotency","columns":"tenant_id,idempotency_key","nonUnique":0},{"table":"zsjos_material_reference","index":"idx_material_reference_content","columns":"tenant_id,target_content_version_id,id","nonUnique":1},{"table":"zsjos_material_import_batch","index":"uk_material_import_no","columns":"tenant_id,batch_no,deleted","nonUnique":0},{"table":"zsjos_material_import_batch","index":"uk_material_import_idempotency","columns":"tenant_id,idempotency_key,deleted","nonUnique":0},{"table":"zsjos_material_import_batch","index":"idx_material_import_list","columns":"tenant_id,material_type_id,status,id","nonUnique":1},{"table":"zsjos_material_import_error","index":"idx_material_import_error","columns":"tenant_id,batch_id,row_no,id","nonUnique":1},{"table":"zsjos_content_review_config","index":"uk_content_review_config_tenant","columns":"active_tenant_id","nonUnique":0},{"table":"zsjos_content_review_batch","index":"uk_content_review_batch_no","columns":"tenant_id,batch_no,deleted","nonUnique":0},{"table":"zsjos_content_review_batch","index":"uk_content_review_process","columns":"tenant_id,process_instance_id","nonUnique":0},{"table":"zsjos_content_review_batch","index":"uk_content_review_business_key","columns":"tenant_id,business_key","nonUnique":0},{"table":"zsjos_content_review_batch","index":"idx_content_review_list","columns":"tenant_id,status,director_user_id,id","nonUnique":1},{"table":"zsjos_content_review_batch","index":"idx_content_review_operator","columns":"tenant_id,operator_user_id,status,id","nonUnique":1},{"table":"zsjos_content_review_batch_item","index":"uk_content_review_item","columns":"tenant_id,batch_id,content_version_id,deleted","nonUnique":0},{"table":"zsjos_content_review_batch_item","index":"idx_content_review_item_batch","columns":"tenant_id,batch_id,sort_no,id","nonUnique":1},{"table":"zsjos_content_review_batch_item","index":"idx_content_review_item_content","columns":"tenant_id,content_id,content_version_id","nonUnique":1},{"table":"zsjos_content_review_batch_item","index":"idx_content_review_item_version","columns":"tenant_id,content_version_id,batch_id,deleted","nonUnique":1},{"table":"zsjos_content_version_file","index":"uk_content_version_file","columns":"tenant_id,content_version_id,field_key,infra_file_id,deleted","nonUnique":0},{"table":"zsjos_content_version_file","index":"idx_content_version_file_order","columns":"tenant_id,content_version_id,field_key,sort_no,id","nonUnique":1},{"table":"zsjos_partner_invitation","index":"idx_tenant_student_scene_status","columns":"tenant_id,student_person_id,invitation_scene,status,id","nonUnique":1},{"table":"zsjos_partner_invitation","index":"uk_tenant_active_student_invitation","columns":"tenant_id,active_student_person_id","nonUnique":0}]',
      '$[*]' COLUMNS (
        table_name varchar(64) PATH '$.table',
        index_name varchar(64) PATH '$.index',
        column_names varchar(1000) PATH '$.columns',
        non_unique int PATH '$.nonUnique'
      )
    ) expected_index
    LEFT JOIN (
      SELECT table_name,index_name,MIN(non_unique) non_unique,
             GROUP_CONCAT(column_name ORDER BY seq_in_index SEPARATOR ',') column_names
      FROM information_schema.statistics
      WHERE table_schema=DATABASE()
      GROUP BY table_name,index_name
    ) actual_index
      ON actual_index.table_name=expected_index.table_name
     AND actual_index.index_name=expected_index.index_name
    WHERE actual_index.index_name IS NULL
       OR actual_index.non_unique<>expected_index.non_unique
       OR actual_index.column_names<>expected_index.column_names
  ) THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='V191 material/content-review indexes are incompatible';
  END IF;
  IF (SELECT COUNT(*) FROM information_schema.columns
      WHERE table_schema=DATABASE() AND table_name='zsjos_content_version'
        AND ((column_name='title_snapshot' AND data_type='varchar' AND character_maximum_length=255)
          OR (column_name='topic_snapshot' AND data_type='varchar' AND character_maximum_length=1000)
          OR (column_name='cover_snapshot_json' AND data_type='json')
          OR (column_name='deliverable_snapshot_json' AND data_type='json')
          OR (column_name='lead_resource_url' AND data_type='varchar' AND character_maximum_length=1024)
          OR (column_name='planned_publish_at' AND data_type='datetime')
          OR (column_name='frozen_at' AND data_type='datetime'))) <> 7
     OR (SELECT COUNT(*) FROM information_schema.columns
         WHERE table_schema=DATABASE() AND table_name='zsjos_partner_invitation'
           AND ((column_name='invitation_scene' AND data_type='varchar' AND character_maximum_length=32
                 AND is_nullable='NO' AND column_default='GENERAL')
             OR (column_name='student_person_id' AND data_type='bigint' AND is_nullable='YES')
             OR (column_name='student_name_snapshot' AND data_type='varchar' AND character_maximum_length=100)
             OR (column_name='student_mobile_snapshot' AND data_type='varchar' AND character_maximum_length=32)
             OR (column_name='initiated_by_director_user_id' AND data_type='bigint')
             OR (column_name='assignment_context_json' AND data_type='json')
             OR (column_name='active_student_person_id' AND data_type='bigint'
                 AND extra LIKE '%STORED GENERATED%')
             OR (column_name='assigned_operator_user_id' AND data_type='bigint' AND is_nullable='YES')
             OR (column_name='assigned_operator_name_snapshot' AND data_type='varchar'
                 AND character_maximum_length=100 AND is_nullable='YES'))) <> 9 THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='V191 base-table extensions are incomplete';
  END IF;

  START TRANSACTION;

  INSERT INTO `system_dict_type`
    (`name`,`type`,`status`,`remark`,`creator`,`create_time`,`updater`,`update_time`,`deleted`)
  SELECT seed.name,seed.type,0,'管理员维护；V191 不预置业务选项','V191',NOW(),'V191',NOW(),b'0'
  FROM (
    SELECT '素材适配账号类型' name,'zsjos_material_account_type' type
    UNION ALL SELECT '素材适配专业方向','zsjos_material_profession'
  ) seed
  WHERE NOT EXISTS (SELECT 1 FROM `system_dict_type` existing
                    WHERE existing.type=seed.type AND existing.deleted=b'0');

  INSERT INTO `system_dict_data`
    (`sort`,`label`,`value`,`dict_type`,`status`,`color_type`,`creator`,`create_time`,`updater`,`update_time`,`deleted`)
  SELECT seed.sort,seed.label,seed.value,'zsjos_material_profession',0,'default','V191',NOW(),'V191',NOW(),b'0'
  FROM (
    SELECT 10 sort,'T1 职业营养' label,'t1_occupational_nutrition' value
    UNION ALL SELECT 20,'T2 健康管理','t2_health_management'
    UNION ALL SELECT 30,'T3 心理与社工','t3_psychology_social_work'
    UNION ALL SELECT 40,'T4 药学','t4_pharmacy'
    UNION ALL SELECT 50,'T5 中药学','t5_traditional_chinese_pharmacy'
    UNION ALL SELECT 60,'T6 中医适宜技术','t6_tcm_appropriate_technology'
    UNION ALL SELECT 70,'T7 中医师承专长','t7_tcm_apprenticeship_specialty'
    UNION ALL SELECT 80,'T8 健康医疗学历提升','t8_healthcare_academic_upgrade'
    UNION ALL SELECT 90,'T9 健康职业商业变现','t9_healthcare_career_monetization'
  ) seed
  WHERE NOT EXISTS (SELECT 1 FROM `system_dict_data` existing
                    WHERE existing.dict_type='zsjos_material_profession'
                      AND existing.value=seed.value AND existing.deleted=b'0');

  INSERT INTO `zsjos_material_type`
    (`code`,`name`,`description`,`status`,`allow_manual_create`,`allow_import`,`allow_auto_collect`,
     `recommendation_enabled`,`recommendation_config_json`,`version`,`creator`,`create_time`,`updater`,`update_time`,`deleted`,`tenant_id`)
  SELECT seed.code,seed.name,seed.description,0,seed.manual_create,seed.allow_import,seed.auto_collect,
         seed.recommendation_enabled,JSON_OBJECT('dimensions',JSON_ARRAY('account_type','profession','account_stage'),
         'maxResults',20),
         0,'V191',NOW(),'V191',NOW(),b'0',tenant.id
  FROM `system_tenant` tenant
  CROSS JOIN (
    SELECT 'viral_account' code,'爆款账号' name,'爆款账号拆解内容包' description,b'1' manual_create,b'1' allow_import,b'0' auto_collect,b'1' recommendation_enabled
    UNION ALL SELECT 'viral_content','爆款视频/图文','爆款视频或图文拆解内容包',b'1',b'1',b'0',b'1'
    UNION ALL SELECT 'sop','SOP','可检索、可引用的标准作业参考文档',b'1',b'1',b'0',b'0'
    UNION ALL SELECT 'production_content','生产内容','审核通过并明确收录的生产内容',b'0',b'0',b'1',b'1'
  ) seed
  WHERE tenant.deleted=b'0' AND tenant.status=0
    AND NOT EXISTS (SELECT 1 FROM `zsjos_material_type` existing
                    WHERE existing.tenant_id=tenant.id AND existing.code=seed.code AND existing.deleted=b'0');

  INSERT INTO `zsjos_content_review_config`
    (`production_material_type_code`,`version`,`creator`,`create_time`,`updater`,`update_time`,`deleted`,`tenant_id`)
  SELECT 'production_content',0,'V191',NOW(),'V191',NOW(),b'0',tenant.id
  FROM `system_tenant` tenant
  WHERE tenant.deleted=b'0' AND tenant.status=0
    AND NOT EXISTS (SELECT 1 FROM `zsjos_content_review_config` existing
                    WHERE existing.tenant_id=tenant.id AND existing.deleted=b'0');

  INSERT INTO `system_menu`
    (`id`,`name`,`permission`,`type`,`sort`,`parent_id`,`path`,`icon`,`component`,`component_name`,
     `workbench_render_mode`,`status`,`visible`,`keep_alive`,`always_show`,`creator`,`create_time`,`updater`,`update_time`,`deleted`)
  SELECT seed.id,seed.name,seed.permission,seed.type,seed.sort,seed.parent_id,seed.path,seed.icon,
         seed.component,seed.component_name,seed.render_mode,0,b'1',b'1',b'1','V191',NOW(),'V191',NOW(),b'0'
  FROM (
    SELECT 80010 id,'素材库' name,'' permission,1 type,60 sort,6735 parent_id,'material-library' path,'ep:collection' icon,'' component,NULL component_name,'native' render_mode
    UNION ALL SELECT 80011,'素材浏览','zsjos:material:query',2,1,80010,'browse','ep:search','zsjos-workbench','MaterialLibraryPage','native'
    UNION ALL SELECT 80012,'素材管理','zsjos:material:manage',2,2,80010,'manage','ep:files','zsjos/material/index','ZsjosMaterial','admin_embed'
    UNION ALL SELECT 80013,'类型与模板','zsjos:material-type:query',2,3,80010,'types','ep:setting','zsjos/materialType/index','ZsjosMaterialType','admin_embed'
    UNION ALL SELECT 80014,'导入记录','zsjos:material-import:query',2,4,80010,'imports','ep:upload-filled','zsjos/materialImport/index','ZsjosMaterialImport','admin_embed'
    UNION ALL SELECT 80015,'内容审核','zsjos:content-review:query',2,5,80010,'content-review','ep:finished','zsjos-workbench','ContentReviewBatchPage','native'
    UNION ALL SELECT 80016,'创建素材','zsjos:material:create',3,1,80011,'','','',NULL,'native'
    UNION ALL SELECT 80017,'修改素材','zsjos:material:update',3,2,80011,'','','',NULL,'native'
    UNION ALL SELECT 80018,'提交素材审批','zsjos:material:submit',3,3,80011,'','','',NULL,'native'
    UNION ALL SELECT 80019,'停用素材','zsjos:material:disable',3,4,80012,'','','',NULL,'admin_only'
    UNION ALL SELECT 80020,'恢复素材','zsjos:material:restore',3,5,80012,'','','',NULL,'admin_only'
    UNION ALL SELECT 80021,'点赞素材','zsjos:material:like',3,6,80011,'','','',NULL,'native'
    UNION ALL SELECT 80022,'收藏素材','zsjos:material:favorite',3,7,80011,'','','',NULL,'native'
    UNION ALL SELECT 80023,'引用素材','zsjos:material:reference',3,8,80011,'','','',NULL,'native'
    UNION ALL SELECT 80024,'创建素材类型','zsjos:material-type:create',3,1,80013,'','','',NULL,'admin_only'
    UNION ALL SELECT 80025,'修改素材类型','zsjos:material-type:update',3,2,80013,'','','',NULL,'admin_only'
    UNION ALL SELECT 80026,'编辑素材模板','zsjos:material-schema:update',3,3,80013,'','','',NULL,'admin_only'
    UNION ALL SELECT 80027,'发布素材模板','zsjos:material-schema:publish',3,4,80013,'','','',NULL,'admin_only'
    UNION ALL SELECT 80028,'下载导入模板','zsjos:material-import:download',3,1,80014,'','','',NULL,'admin_only'
    UNION ALL SELECT 80029,'预检素材导入','zsjos:material-import:preview',3,2,80014,'','','',NULL,'admin_only'
    UNION ALL SELECT 80030,'确认素材导入','zsjos:material-import:commit',3,3,80014,'','','',NULL,'admin_only'
    UNION ALL SELECT 80031,'配置内容审核','zsjos:content-review:config',3,5,80013,'','','',NULL,'admin_only'
    UNION ALL SELECT 80032,'创建审核批次','zsjos:content-review:create',3,1,80015,'','','',NULL,'native'
    UNION ALL SELECT 80033,'提交审核批次','zsjos:content-review:submit',3,2,80015,'','','',NULL,'native'
    UNION ALL SELECT 80034,'编导逐条审核','zsjos:content-review:director-review',3,3,80015,'','','',NULL,'native'
    UNION ALL SELECT 80035,'终审逐条审核','zsjos:content-review:final-review',3,4,80015,'','','',NULL,'native'
    UNION ALL SELECT 80036,'登记发布结果','zsjos:content-review:publish-register',3,5,80015,'','','',NULL,'native'
    UNION ALL SELECT 80037,'学员开通兼职账号','zsjos:partner-invitation:create-student',3,50,7022,'','','',NULL,'native'
    UNION ALL SELECT 80038,'查看全部内容审核','zsjos:content-review:query-all',3,6,80015,'','','',NULL,'native'
    UNION ALL SELECT 80039,'下载导入错误报告','zsjos:material-import:error-download',3,4,80014,'','','',NULL,'admin_only'
    UNION ALL SELECT 80040,'内容生产','zsjos:content:query',2,6,80010,'content-production','ep:edit-pen','zsjos-workbench','ContentProductionPage','native'
  ) seed
  ON DUPLICATE KEY UPDATE
    `name`=VALUES(`name`),`permission`=VALUES(`permission`),`type`=VALUES(`type`),`sort`=VALUES(`sort`),
    `parent_id`=VALUES(`parent_id`),`path`=VALUES(`path`),`icon`=VALUES(`icon`),
    `component`=VALUES(`component`),`component_name`=VALUES(`component_name`),
    `workbench_render_mode`=VALUES(`workbench_render_mode`),`status`=0,`visible`=b'1',
    `keep_alive`=VALUES(`keep_alive`),`always_show`=VALUES(`always_show`),
    `updater`='V191',`update_time`=NOW(),`deleted`=b'0';

  SET v_menu_id=80010;
  WHILE v_menu_id <= 80036 DO
    UPDATE `system_tenant_package`
    SET `menu_ids`=JSON_ARRAY_APPEND(`menu_ids`,'$',v_menu_id),`updater`='V191',`update_time`=NOW()
    WHERE `deleted`=b'0' AND JSON_CONTAINS(`menu_ids`,'6735','$')
      AND NOT JSON_CONTAINS(`menu_ids`,CAST(v_menu_id AS CHAR),'$');
    SET v_menu_id=v_menu_id+1;
  END WHILE;
  UPDATE `system_tenant_package`
  SET `menu_ids`=JSON_ARRAY_APPEND(`menu_ids`,'$',80037),`updater`='V191',`update_time`=NOW()
  WHERE `deleted`=b'0' AND JSON_CONTAINS(`menu_ids`,'7022','$')
    AND NOT JSON_CONTAINS(`menu_ids`,'80037','$');
  UPDATE `system_tenant_package`
  SET `menu_ids`=JSON_ARRAY_APPEND(`menu_ids`,'$',80038),`updater`='V191',`update_time`=NOW()
  WHERE `deleted`=b'0' AND JSON_CONTAINS(`menu_ids`,'6735','$')
    AND NOT JSON_CONTAINS(`menu_ids`,'80038','$');
  UPDATE `system_tenant_package`
  SET `menu_ids`=JSON_ARRAY_APPEND(`menu_ids`,'$',80039),`updater`='V191',`update_time`=NOW()
  WHERE `deleted`=b'0' AND JSON_CONTAINS(`menu_ids`,'6735','$')
    AND NOT JSON_CONTAINS(`menu_ids`,'80039','$');
  UPDATE `system_tenant_package`
  SET `menu_ids`=JSON_ARRAY_APPEND(`menu_ids`,'$',80040),`updater`='V191',`update_time`=NOW()
  WHERE `deleted`=b'0' AND JSON_CONTAINS(`menu_ids`,'6735','$')
    AND NOT JSON_CONTAINS(`menu_ids`,'80040','$');

  -- Preserve access held through the retired standalone content page without inferring role names.
  INSERT INTO `system_role_menu`
    (`role_id`,`menu_id`,`creator`,`create_time`,`updater`,`update_time`,`deleted`,`tenant_id`)
  SELECT DISTINCT role_row.id,target_menu.id,'V191',NOW(),'V191',NOW(),b'0',role_row.tenant_id
  FROM `system_role_menu` source_grant
  JOIN `system_role` role_row ON role_row.id=source_grant.role_id
    AND role_row.tenant_id=source_grant.tenant_id AND role_row.status=0 AND role_row.deleted=b'0'
  CROSS JOIN (SELECT 80010 id UNION ALL SELECT 80040) target_id
  JOIN `system_menu` target_menu ON target_menu.id=target_id.id
    AND target_menu.status=0 AND target_menu.deleted=b'0'
  WHERE source_grant.menu_id=6974 AND source_grant.deleted=b'0'
    AND NOT EXISTS (SELECT 1 FROM `system_role_menu` existing_grant
      WHERE existing_grant.role_id=role_row.id AND existing_grant.menu_id=target_menu.id
        AND existing_grant.tenant_id=role_row.tenant_id AND existing_grant.deleted=b'0');

  INSERT INTO `zsjos_schema_version` (`version`,`description`,`checksum`,`installed_at`)
  VALUES ('V191','Material library, content review, and student partner invitation',
          SHA2('V191__material_library_content_review.sql',256),NOW())
  ON DUPLICATE KEY UPDATE `description`=VALUES(`description`),`checksum`=VALUES(`checksum`);
  INSERT INTO `zsjos_module_schema_version`
    (`module_code`,`version`,`description`,`checksum`,`release_version`,`installed_at`)
  VALUES ('core','V191','Material library, content review, and student partner invitation',
          SHA2('V191__material_library_content_review.sql',256),'baseline',NOW())
  ON DUPLICATE KEY UPDATE `description`=VALUES(`description`),`checksum`=VALUES(`checksum`);

  COMMIT;
END$$
DELIMITER ;

CALL `zsjos_v191_apply`();
DROP PROCEDURE IF EXISTS `zsjos_v191_apply`;
DROP PROCEDURE IF EXISTS `zsjos_v191_add_index`;
DROP PROCEDURE IF EXISTS `zsjos_v191_add_column`;
