SET NAMES utf8mb4;
SET @db := DATABASE();
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='zsjos_content_version' AND column_name='purpose_value'),'SELECT 1','ALTER TABLE zsjos_content_version ADD COLUMN purpose_value varchar(64) DEFAULT NULL'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='zsjos_content_version' AND column_name='purpose_label_snapshot'),'SELECT 1','ALTER TABLE zsjos_content_version ADD COLUMN purpose_label_snapshot varchar(128) DEFAULT NULL'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='zsjos_content_version' AND column_name='format_value'),'SELECT 1','ALTER TABLE zsjos_content_version ADD COLUMN format_value varchar(64) DEFAULT NULL'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='zsjos_content_version' AND column_name='format_label_snapshot'),'SELECT 1','ALTER TABLE zsjos_content_version ADD COLUMN format_label_snapshot varchar(128) DEFAULT NULL'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='zsjos_content_version' AND column_name='detail_url'),'SELECT 1','ALTER TABLE zsjos_content_version ADD COLUMN detail_url varchar(1000) DEFAULT NULL'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='zsjos_content_version' AND column_name='comment_hook'),'SELECT 1','ALTER TABLE zsjos_content_version ADD COLUMN comment_hook text DEFAULT NULL'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='zsjos_content_version' AND column_name='reference_content_version_id'),'SELECT 1','ALTER TABLE zsjos_content_version ADD COLUMN reference_content_version_id bigint DEFAULT NULL'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
