-- ZSJOS 客资、支付、订单与学生服务生命周期表结构雏形
-- MySQL 8.x / 仅创建 ZSJOS 自有业务表
--
-- 本脚本：
--   1. 只使用 CREATE TABLE IF NOT EXISTS，可重复执行；
--   2. 不删除、重建或修改现有表，不插入业务数据；
--   3. 不创建 BPM 任务/历史、系统用户/组织/权限/字典或产品 SKU 表；
--   4. 暂不建立跨模块物理外键，跨模块编号通过业务 API 和服务校验保证；
--   5. 执行前仍需评审字段精度、字典初始化、索引容量和产品规则契约。

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `zsjos_person` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Person 编号',
  `person_no` varchar(64) NOT NULL COMMENT 'Person 业务编号',
  `name` varchar(100) NOT NULL COMMENT '姓名',
  `mobile` varchar(32) DEFAULT NULL COMMENT '手机号（脱敏展示）',
  `wechat_id` varchar(128) DEFAULT NULL COMMENT '微信号（脱敏展示）',
  `identity_status` varchar(32) NOT NULL COMMENT '身份状态，协议值待确认',
  `first_seen_at` datetime NOT NULL COMMENT '首次发现时间',
  `last_seen_at` datetime NOT NULL COMMENT '最近发现时间',
  `version` int NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_person_no` (`tenant_id`, `person_no`),
  KEY `idx_tenant_mobile` (`tenant_id`, `mobile`),
  KEY `idx_tenant_wechat_id` (`tenant_id`, `wechat_id`),
  KEY `idx_tenant_identity_status` (`tenant_id`, `identity_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ZSJOS 客户与学员身份主档';

CREATE TABLE IF NOT EXISTS `zsjos_person_merge_event` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '合并事件编号',
  `from_person_id` bigint NOT NULL COMMENT '被合并 Person 编号',
  `to_person_id` bigint NOT NULL COMMENT '保留 Person 编号',
  `event_type` varchar(32) NOT NULL COMMENT '合并/拆分事件类型',
  `reason` varchar(500) DEFAULT NULL COMMENT '原因',
  `operator_user_id` bigint DEFAULT NULL COMMENT '操作人用户编号',
  `source_snapshot` json DEFAULT NULL COMMENT '事件前身份快照',
  `occurred_at` datetime NOT NULL COMMENT '实际发生时间',
  `idempotency_key` varchar(128) NOT NULL COMMENT '幂等键',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_idempotency` (`tenant_id`, `idempotency_key`),
  KEY `idx_tenant_from_person` (`tenant_id`, `from_person_id`),
  KEY `idx_tenant_to_person` (`tenant_id`, `to_person_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ZSJOS Person 合并与拆分历史';

CREATE TABLE IF NOT EXISTS `zsjos_partner` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '兼职主体编号',
  `partner_no` varchar(64) NOT NULL COMMENT '兼职主体业务编号',
  `name` varchar(100) NOT NULL COMMENT '姓名或主体名称',
  `mobile` varchar(32) DEFAULT NULL COMMENT '手机号',
  `status` varchar(32) NOT NULL COMMENT '启停状态，协议值待确认',
  `bound_system_user_id` bigint DEFAULT NULL COMMENT '绑定系统账号编号',
  `channel_id` varchar(64) DEFAULT NULL COMMENT '渠道编号',
  `enabled_at` datetime DEFAULT NULL COMMENT '启用时间',
  `disabled_at` datetime DEFAULT NULL COMMENT '停用时间',
  `version` int NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_partner_no` (`tenant_id`, `partner_no`),
  KEY `idx_tenant_mobile` (`tenant_id`, `mobile`),
  KEY `idx_tenant_bound_user` (`tenant_id`, `bound_system_user_id`),
  KEY `idx_tenant_status` (`tenant_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ZSJOS 兼职客资提交主体';

CREATE TABLE IF NOT EXISTS `zsjos_lead` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '客资编号',
  `person_id` bigint NOT NULL COMMENT 'Person 编号',
  `submitted_name` varchar(100) NOT NULL COMMENT '表单原始姓名',
  `submitted_mobile` varchar(32) DEFAULT NULL COMMENT '表单原始手机号',
  `submitted_wechat_id` varchar(128) DEFAULT NULL COMMENT '表单原始微信号',
  `source_type` varchar(32) NOT NULL COMMENT '客资来源类型',
  `source_user_id` bigint DEFAULT NULL COMMENT '内部提交员工用户编号',
  `partner_id` bigint DEFAULT NULL COMMENT '兼职提交主体编号',
  `source_channel_id` varchar(64) DEFAULT NULL COMMENT '来源渠道编号',
  `status` varchar(32) NOT NULL COMMENT '客资主状态',
  `assignment_status` varchar(32) NOT NULL COMMENT '客资分配状态',
  `owner_user_id` bigint DEFAULT NULL COMMENT '当前主责销售用户编号',
  `submitted_at` datetime NOT NULL COMMENT '提交时间',
  `converted_at` datetime DEFAULT NULL COMMENT '首次销售转化机会创建时间',
  `invalid_reason` varchar(500) DEFAULT NULL COMMENT '无效原因',
  `appeal_deadline_at` datetime DEFAULT NULL COMMENT '申诉截止时间',
  `closed_at` datetime DEFAULT NULL COMMENT '关闭时间',
  `close_reason` varchar(500) DEFAULT NULL COMMENT '关闭原因',
  `version` int NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_person_status` (`tenant_id`, `person_id`, `status`),
  KEY `idx_tenant_owner_assignment` (`tenant_id`, `owner_user_id`, `assignment_status`),
  KEY `idx_tenant_source_user` (`tenant_id`, `source_user_id`),
  KEY `idx_tenant_partner` (`tenant_id`, `partner_id`),
  KEY `idx_tenant_submitted_at` (`tenant_id`, `submitted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ZSJOS 客资';

CREATE TABLE IF NOT EXISTS `zsjos_lead_activation` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '客资激活编号',
  `person_id` bigint NOT NULL COMMENT 'Person 编号',
  `lead_id` bigint NOT NULL COMMENT '被激活的既有客资编号',
  `source_type` varchar(32) NOT NULL COMMENT '来源类型',
  `source_user_id` bigint DEFAULT NULL COMMENT '内部提交员工用户编号',
  `partner_id` bigint DEFAULT NULL COMMENT '兼职提交主体编号',
  `source_channel_id` varchar(64) DEFAULT NULL COMMENT '来源渠道编号',
  `submission_snapshot` json NOT NULL COMMENT '本次表单快照',
  `notification_targets` json DEFAULT NULL COMMENT '按当前关系解析的通知对象',
  `activated_at` datetime NOT NULL COMMENT '激活时间',
  `idempotency_key` varchar(128) NOT NULL COMMENT '幂等键',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_idempotency` (`tenant_id`, `idempotency_key`),
  KEY `idx_tenant_person_activated_at` (`tenant_id`, `person_id`, `activated_at`),
  KEY `idx_tenant_lead_activated_at` (`tenant_id`, `lead_id`, `activated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ZSJOS 已有客资再次激活记录';

CREATE TABLE IF NOT EXISTS `zsjos_lead_assignment_history` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '分配历史编号',
  `lead_id` bigint NOT NULL COMMENT '客资编号',
  `action_type` varchar(32) NOT NULL COMMENT '派单、接单、拒单、转派、回收、释放或认领',
  `from_owner_user_id` bigint DEFAULT NULL COMMENT '原负责人用户编号',
  `to_owner_user_id` bigint DEFAULT NULL COMMENT '新负责人用户编号',
  `operator_user_id` bigint NOT NULL COMMENT '操作人用户编号',
  `reason` varchar(500) DEFAULT NULL COMMENT '原因',
  `occurred_at` datetime NOT NULL COMMENT '实际发生时间',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_lead_occurred_at` (`tenant_id`, `lead_id`, `occurred_at`),
  KEY `idx_tenant_to_owner` (`tenant_id`, `to_owner_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ZSJOS 客资分配历史';

CREATE TABLE IF NOT EXISTS `zsjos_lead_appeal` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '申诉编号',
  `lead_id` bigint NOT NULL COMMENT '客资编号',
  `round_no` int NOT NULL COMMENT '申诉轮次',
  `status` varchar(32) NOT NULL COMMENT '申诉状态',
  `applicant_user_id` bigint NOT NULL COMMENT '申请人用户编号',
  `reason` varchar(1000) NOT NULL COMMENT '申诉原因',
  `evidence_refs` json DEFAULT NULL COMMENT '证据引用',
  `reviewer_user_id` bigint DEFAULT NULL COMMENT '复核人用户编号',
  `decision_reason` varchar(1000) DEFAULT NULL COMMENT '决定原因',
  `submitted_at` datetime NOT NULL COMMENT '提交时间',
  `decided_at` datetime DEFAULT NULL COMMENT '决定时间',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_lead_round` (`tenant_id`, `lead_id`, `round_no`),
  KEY `idx_tenant_status` (`tenant_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ZSJOS 客资申诉';

CREATE TABLE IF NOT EXISTS `zsjos_opportunity` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '机会编号',
  `person_id` bigint NOT NULL COMMENT 'Person 编号',
  `type` varchar(32) NOT NULL COMMENT 'initial_conversion 或 repurchase',
  `lead_id` bigint DEFAULT NULL COMMENT '首次销售转化来源客资',
  `source_service_relation_id` bigint DEFAULT NULL COMMENT '复购来源服务关系',
  `previous_order_id` bigint DEFAULT NULL COMMENT '可选上一张订单',
  `status` varchar(32) NOT NULL COMMENT '机会状态',
  `owner_user_id` bigint NOT NULL COMMENT '当前成交责任人',
  `expected_product_summary` json DEFAULT NULL COMMENT '意向产品摘要',
  `next_follow_up_at` datetime DEFAULT NULL COMMENT '下次跟进提醒时间',
  `shelved_until` datetime DEFAULT NULL COMMENT '暂缓截止时间',
  `shelved_reason` varchar(500) DEFAULT NULL COMMENT '暂缓原因',
  `won_at` datetime DEFAULT NULL COMMENT '成交时间',
  `lost_at` datetime DEFAULT NULL COMMENT '流失时间',
  `lost_reason` varchar(500) DEFAULT NULL COMMENT '流失原因',
  `version` int NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_initial_conversion_lead` (`tenant_id`, `type`, `lead_id`),
  KEY `idx_tenant_person_status` (`tenant_id`, `person_id`, `status`),
  KEY `idx_tenant_owner_status` (`tenant_id`, `owner_user_id`, `status`),
  KEY `idx_tenant_source_relation` (`tenant_id`, `source_service_relation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ZSJOS 销售机会';

CREATE TABLE IF NOT EXISTS `zsjos_payment_order` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '支付单编号',
  `payment_order_no` varchar(64) NOT NULL COMMENT '支付单业务编号',
  `lead_id` bigint NOT NULL COMMENT '绑定客资编号，创建后不可修改',
  `person_id` bigint NOT NULL COMMENT 'Person 编号',
  `opportunity_id` bigint DEFAULT NULL COMMENT '可选正式销售机会编号',
  `status` varchar(32) NOT NULL COMMENT 'pending_payment/paid/expired/closed',
  `expected_amount` decimal(18,2) NOT NULL COMMENT '应收金额',
  `currency` varchar(16) NOT NULL DEFAULT 'CNY' COMMENT '币种',
  `product_items_snapshot` json NOT NULL COMMENT '收款时产品 SKU 快照',
  `product_rule_snapshot` json DEFAULT NULL COMMENT '收款时产品规则结果快照',
  `product_rule_version` varchar(64) DEFAULT NULL COMMENT '产品规则版本',
  `initiator_user_id` bigint NOT NULL COMMENT '发起人用户编号',
  `link_token_hash` varchar(128) NOT NULL COMMENT '支付链接令牌摘要',
  `expires_at` datetime DEFAULT NULL COMMENT '链接过期时间',
  `paid_at` datetime DEFAULT NULL COMMENT '支付成功时间',
  `closed_at` datetime DEFAULT NULL COMMENT '关闭时间',
  `close_reason` varchar(500) DEFAULT NULL COMMENT '关闭原因',
  `version` int NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_payment_order_no` (`tenant_id`, `payment_order_no`),
  UNIQUE KEY `uk_tenant_link_token_hash` (`tenant_id`, `link_token_hash`),
  KEY `idx_tenant_lead_status` (`tenant_id`, `lead_id`, `status`),
  KEY `idx_tenant_opportunity` (`tenant_id`, `opportunity_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ZSJOS 客资绑定支付单';

CREATE TABLE IF NOT EXISTS `zsjos_payment_transaction` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '支付流水编号',
  `payment_order_id` bigint NOT NULL COMMENT '支付单编号',
  `amount` decimal(18,2) NOT NULL COMMENT '渠道实付金额',
  `currency` varchar(16) NOT NULL DEFAULT 'CNY' COMMENT '币种',
  `payment_method` varchar(64) DEFAULT NULL COMMENT '渠道支付方式',
  `paid_at` datetime NOT NULL COMMENT '渠道支付成功时间',
  `external_channel` varchar(64) NOT NULL COMMENT '外部支付渠道',
  `external_transaction_no` varchar(128) NOT NULL COMMENT '外部渠道流水号',
  `payer_reference` varchar(256) DEFAULT NULL COMMENT '实际付款人引用，不作为业务归属',
  `callback_event_id` varchar(128) NOT NULL COMMENT '支付回调事件编号',
  `evidence_refs` json DEFAULT NULL COMMENT '渠道凭证引用',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_channel_transaction` (`tenant_id`, `external_channel`, `external_transaction_no`),
  UNIQUE KEY `uk_tenant_callback_event` (`tenant_id`, `callback_event_id`),
  UNIQUE KEY `uk_tenant_payment_order` (`tenant_id`, `payment_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ZSJOS 支付渠道成功流水';

CREATE TABLE IF NOT EXISTS `zsjos_order` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '订单编号',
  `order_no` varchar(64) NOT NULL COMMENT '订单业务编号',
  `lead_id` bigint NOT NULL COMMENT '来源客资编号',
  `source_payment_order_id` bigint DEFAULT NULL COMMENT '来源支付单编号，支付自动建单时唯一',
  `opportunity_id` bigint DEFAULT NULL COMMENT '正式销售机会编号，按产品规则条件必填',
  `person_id` bigint NOT NULL COMMENT 'Person 编号',
  `order_type` varchar(32) NOT NULL COMMENT '订单业务类型，具体协议待确认',
  `status` varchar(32) NOT NULL COMMENT '订单状态',
  `submitter_user_id` bigint DEFAULT NULL COMMENT '本次订单提交人',
  `submitter_center_type` varchar(64) DEFAULT NULL COMMENT '提交中心类型',
  `total_amount` decimal(18,2) NOT NULL COMMENT '订单总额',
  `discount_amount` decimal(18,2) NOT NULL DEFAULT 0 COMMENT '优惠金额',
  `payable_amount` decimal(18,2) NOT NULL COMMENT '应付金额',
  `contract_refs` json DEFAULT NULL COMMENT '合同或附件引用',
  `current_approval_round_id` bigint DEFAULT NULL COMMENT '当前审批轮次编号',
  `submitted_at` datetime DEFAULT NULL COMMENT '提交时间',
  `effective_at` datetime DEFAULT NULL COMMENT '生效时间',
  `cancelled_at` datetime DEFAULT NULL COMMENT '取消时间',
  `cancel_reason` varchar(500) DEFAULT NULL COMMENT '取消原因',
  `zero_amount_reason` varchar(500) DEFAULT NULL COMMENT '零元订单原因',
  `zero_amount_approved_by_user_id` bigint DEFAULT NULL COMMENT '零元订单授权人',
  `version` int NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_order_no` (`tenant_id`, `order_no`),
  UNIQUE KEY `uk_tenant_source_payment_order` (`tenant_id`, `source_payment_order_id`),
  UNIQUE KEY `uk_tenant_opportunity` (`tenant_id`, `opportunity_id`),
  KEY `idx_tenant_lead_status` (`tenant_id`, `lead_id`, `status`),
  KEY `idx_tenant_person_status` (`tenant_id`, `person_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ZSJOS 业务订单';

CREATE TABLE IF NOT EXISTS `zsjos_order_item` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '订单项编号',
  `order_id` bigint NOT NULL COMMENT '订单编号',
  `product_id` bigint DEFAULT NULL COMMENT '产品模块产品编号',
  `sku_id` bigint DEFAULT NULL COMMENT '产品模块 SKU 编号',
  `quantity` decimal(18,4) NOT NULL DEFAULT 1 COMMENT '数量',
  `unit_price` decimal(18,2) NOT NULL COMMENT '单价',
  `discount_amount` decimal(18,2) NOT NULL DEFAULT 0 COMMENT '订单项优惠金额',
  `payable_amount` decimal(18,2) NOT NULL COMMENT '订单项应付金额',
  `product_snapshot` json NOT NULL COMMENT '产品 SKU 快照',
  `product_rule_snapshot` json DEFAULT NULL COMMENT '产品规则结果快照',
  `product_rule_version` varchar(64) DEFAULT NULL COMMENT '产品规则版本',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_order` (`tenant_id`, `order_id`),
  KEY `idx_tenant_sku` (`tenant_id`, `sku_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ZSJOS 订单项';

CREATE TABLE IF NOT EXISTS `zsjos_order_payment_allocation` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '订单资金分配编号',
  `order_id` bigint NOT NULL COMMENT '订单编号',
  `payment_transaction_id` bigint DEFAULT NULL COMMENT '渠道支付流水编号',
  `customer_account_ledger_id` bigint DEFAULT NULL COMMENT '客户账户账本编号',
  `allocated_amount` decimal(18,2) NOT NULL COMMENT '本次分配金额',
  `currency` varchar(16) NOT NULL DEFAULT 'CNY' COMMENT '币种',
  `allocated_at` datetime NOT NULL COMMENT '分配时间',
  `idempotency_key` varchar(128) NOT NULL COMMENT '幂等键',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_idempotency` (`tenant_id`, `idempotency_key`),
  KEY `idx_tenant_order` (`tenant_id`, `order_id`),
  KEY `idx_tenant_payment_transaction` (`tenant_id`, `payment_transaction_id`),
  KEY `idx_tenant_account_ledger` (`tenant_id`, `customer_account_ledger_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ZSJOS 订单资金分配';

CREATE TABLE IF NOT EXISTS `zsjos_order_approval_round` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '审批轮次编号',
  `order_id` bigint NOT NULL COMMENT '订单编号',
  `round_no` int NOT NULL COMMENT '订单内连续轮次',
  `status` varchar(32) NOT NULL COMMENT '审批轮次状态',
  `order_snapshot` json NOT NULL COMMENT '本轮订单完整快照',
  `process_instance_id` varchar(128) NOT NULL COMMENT 'BPM 流程实例编号',
  `process_definition_key` varchar(128) NOT NULL COMMENT 'BPM 流程定义 Key',
  `submitted_by_user_id` bigint NOT NULL COMMENT '本轮提交人用户编号',
  `submitted_at` datetime NOT NULL COMMENT '本轮提交时间',
  `completed_at` datetime DEFAULT NULL COMMENT '本轮完成时间',
  `rejected_bpm_task_id` varchar(128) DEFAULT NULL COMMENT '驳回任务引用，由 BPM 任务事件提供',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_order_round` (`tenant_id`, `order_id`, `round_no`),
  UNIQUE KEY `uk_tenant_process_instance` (`tenant_id`, `process_instance_id`),
  KEY `idx_tenant_order_status` (`tenant_id`, `order_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ZSJOS 订单审批轮次与 BPM 引用';

CREATE TABLE IF NOT EXISTS `zsjos_registration_case` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '报名服务单编号',
  `order_id` bigint NOT NULL COMMENT '有效订单编号',
  `status` varchar(32) NOT NULL COMMENT '报名服务状态',
  `owner_user_id` bigint DEFAULT NULL COMMENT '报名服务负责人用户编号',
  `started_at` datetime DEFAULT NULL COMMENT '开始处理时间',
  `completed_at` datetime DEFAULT NULL COMMENT '完成时间',
  `cancelled_at` datetime DEFAULT NULL COMMENT '取消时间',
  `cancel_reason` varchar(500) DEFAULT NULL COMMENT '取消原因',
  `version` int NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_order` (`tenant_id`, `order_id`),
  KEY `idx_tenant_owner_status` (`tenant_id`, `owner_user_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ZSJOS 报名服务单';

CREATE TABLE IF NOT EXISTS `zsjos_registration_item` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '报名记录编号',
  `registration_case_id` bigint NOT NULL COMMENT '报名服务单编号',
  `item_type` varchar(64) NOT NULL COMMENT '报名记录类型',
  `occurred_at` datetime NOT NULL COMMENT '实际发生时间',
  `recorded_at` datetime NOT NULL COMMENT '系统记录时间',
  `recorded_by_user_id` bigint NOT NULL COMMENT '记录人用户编号',
  `evidence_refs` json DEFAULT NULL COMMENT '凭证引用',
  `remark` varchar(1000) DEFAULT NULL COMMENT '说明',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_case_occurred_at` (`tenant_id`, `registration_case_id`, `occurred_at`),
  KEY `idx_tenant_item_type` (`tenant_id`, `item_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ZSJOS 报名服务事实记录';

CREATE TABLE IF NOT EXISTS `zsjos_service_relation` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '学生服务关系编号',
  `person_id` bigint NOT NULL COMMENT '被服务 Person 编号',
  `order_id` bigint NOT NULL COMMENT '来源有效订单编号',
  `order_item_id` bigint NOT NULL COMMENT '来源订单项编号',
  `registration_case_id` bigint NOT NULL COMMENT '激活报名服务单编号',
  `status` varchar(32) NOT NULL COMMENT '服务关系状态',
  `owner_user_id` bigint DEFAULT NULL COMMENT '学生服务负责人用户编号',
  `service_snapshot` json DEFAULT NULL COMMENT '服务权益及产品规则快照',
  `activated_at` datetime NOT NULL COMMENT '激活时间',
  `paused_at` datetime DEFAULT NULL COMMENT '暂停时间',
  `pause_reason` varchar(500) DEFAULT NULL COMMENT '暂停原因',
  `completed_at` datetime DEFAULT NULL COMMENT '正常完成时间',
  `terminated_at` datetime DEFAULT NULL COMMENT '非正常终止时间',
  `termination_reason` varchar(500) DEFAULT NULL COMMENT '终止原因',
  `version` int NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_order_item` (`tenant_id`, `order_item_id`),
  KEY `idx_tenant_person_status` (`tenant_id`, `person_id`, `status`),
  KEY `idx_tenant_owner_status` (`tenant_id`, `owner_user_id`, `status`),
  KEY `idx_tenant_registration_case` (`tenant_id`, `registration_case_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ZSJOS 学生服务关系';

CREATE TABLE IF NOT EXISTS `zsjos_service_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '服务记录编号',
  `service_relation_id` bigint NOT NULL COMMENT '学生服务关系编号',
  `record_type` varchar(64) NOT NULL COMMENT '服务记录类型',
  `occurred_at` datetime NOT NULL COMMENT '实际发生时间',
  `recorded_by_user_id` bigint NOT NULL COMMENT '记录人用户编号',
  `content` text COMMENT '服务内容',
  `evidence_refs` json DEFAULT NULL COMMENT '凭证引用',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_relation_occurred_at` (`tenant_id`, `service_relation_id`, `occurred_at`),
  KEY `idx_tenant_record_type` (`tenant_id`, `record_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ZSJOS 学生服务过程记录';

CREATE TABLE IF NOT EXISTS `zsjos_customer_account` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '客户资金账户编号',
  `person_id` bigint NOT NULL COMMENT 'Person 编号',
  `currency` varchar(16) NOT NULL DEFAULT 'CNY' COMMENT '币种',
  `available_balance` decimal(18,2) NOT NULL DEFAULT 0 COMMENT '可用余额',
  `version` int NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_person_currency` (`tenant_id`, `person_id`, `currency`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ZSJOS 客户预充值资金账户';

CREATE TABLE IF NOT EXISTS `zsjos_customer_account_ledger` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '账户账本编号',
  `account_id` bigint NOT NULL COMMENT '客户资金账户编号',
  `entry_type` varchar(32) NOT NULL COMMENT '充值、消费、退款或经审批调整，协议待确认',
  `amount` decimal(18,2) NOT NULL COMMENT '有符号变动金额',
  `balance_before` decimal(18,2) NOT NULL COMMENT '变动前余额',
  `balance_after` decimal(18,2) NOT NULL COMMENT '变动后余额',
  `payment_transaction_id` bigint DEFAULT NULL COMMENT '关联支付流水编号',
  `order_id` bigint DEFAULT NULL COMMENT '关联订单编号',
  `refund_case_id` bigint DEFAULT NULL COMMENT '关联退款申请编号',
  `occurred_at` datetime NOT NULL COMMENT '实际发生时间',
  `operator_user_id` bigint DEFAULT NULL COMMENT '操作人用户编号，渠道回调可为空',
  `idempotency_key` varchar(128) NOT NULL COMMENT '幂等键',
  `remark` varchar(500) DEFAULT NULL COMMENT '说明',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_idempotency` (`tenant_id`, `idempotency_key`),
  KEY `idx_tenant_account_occurred_at` (`tenant_id`, `account_id`, `occurred_at`),
  KEY `idx_tenant_payment_transaction` (`tenant_id`, `payment_transaction_id`),
  KEY `idx_tenant_order` (`tenant_id`, `order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ZSJOS 客户资金账户只追加账本';

CREATE TABLE IF NOT EXISTS `zsjos_refund_case` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '退款申请编号',
  `order_id` bigint NOT NULL COMMENT '订单编号',
  `status` varchar(32) NOT NULL COMMENT '退款申请状态',
  `requested_amount` decimal(18,2) NOT NULL COMMENT '申请退款金额',
  `approved_amount` decimal(18,2) DEFAULT NULL COMMENT '批准退款金额',
  `refunded_amount` decimal(18,2) NOT NULL DEFAULT 0 COMMENT '已退款金额',
  `currency` varchar(16) NOT NULL DEFAULT 'CNY' COMMENT '币种',
  `reason` varchar(1000) NOT NULL COMMENT '退款原因',
  `evidence_refs` json DEFAULT NULL COMMENT '证据引用',
  `requested_by_user_id` bigint NOT NULL COMMENT '申请人用户编号',
  `approved_by_user_id` bigint DEFAULT NULL COMMENT '批准人用户编号',
  `process_instance_id` varchar(128) DEFAULT NULL COMMENT '独立退款 BPM 流程实例编号',
  `external_refund_no` varchar(128) DEFAULT NULL COMMENT '外部退款流水号',
  `completed_at` datetime DEFAULT NULL COMMENT '完成时间',
  `version` int NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_order_status` (`tenant_id`, `order_id`, `status`),
  KEY `idx_tenant_process_instance` (`tenant_id`, `process_instance_id`),
  KEY `idx_tenant_external_refund` (`tenant_id`, `external_refund_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ZSJOS 退款业务申请';

CREATE TABLE IF NOT EXISTS `zsjos_refund_item` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '退款明细编号',
  `refund_case_id` bigint NOT NULL COMMENT '退款申请编号',
  `order_item_id` bigint NOT NULL COMMENT '退款订单项编号',
  `service_relation_id` bigint DEFAULT NULL COMMENT '受影响服务关系编号',
  `requested_amount` decimal(18,2) NOT NULL COMMENT '明细申请金额',
  `approved_amount` decimal(18,2) DEFAULT NULL COMMENT '明细批准金额',
  `refunded_amount` decimal(18,2) NOT NULL DEFAULT 0 COMMENT '明细已退款金额',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_refund_order_item` (`tenant_id`, `refund_case_id`, `order_item_id`),
  KEY `idx_tenant_service_relation` (`tenant_id`, `service_relation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ZSJOS 按订单项退款明细';

CREATE TABLE IF NOT EXISTS `zsjos_business_task` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '业务任务编号',
  `task_type` varchar(64) NOT NULL COMMENT '任务类型',
  `biz_type` varchar(64) NOT NULL COMMENT '业务对象类型',
  `biz_id` bigint NOT NULL COMMENT '业务对象编号',
  `status` varchar(32) NOT NULL COMMENT '任务状态',
  `assignee_type` varchar(32) NOT NULL COMMENT '处理人类型',
  `assignee_id` bigint NOT NULL COMMENT '处理人编号',
  `due_at` datetime DEFAULT NULL COMMENT '截止时间',
  `completed_at` datetime DEFAULT NULL COMMENT '完成时间',
  `cancelled_at` datetime DEFAULT NULL COMMENT '关闭时间',
  `cancel_reason` varchar(500) DEFAULT NULL COMMENT '关闭原因',
  `payload` json DEFAULT NULL COMMENT '任务业务负载',
  `idempotency_key` varchar(128) DEFAULT NULL COMMENT '可选幂等键',
  `version` int NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_idempotency` (`tenant_id`, `idempotency_key`),
  KEY `idx_tenant_assignee_status_due` (`tenant_id`, `assignee_type`, `assignee_id`, `status`, `due_at`),
  KEY `idx_tenant_biz` (`tenant_id`, `biz_type`, `biz_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ZSJOS 非 BPM 业务任务';

CREATE TABLE IF NOT EXISTS `zsjos_business_event` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '业务事件编号',
  `event_type` varchar(64) NOT NULL COMMENT '事件类型',
  `aggregate_type` varchar(64) NOT NULL COMMENT '聚合类型',
  `aggregate_id` bigint NOT NULL COMMENT '聚合编号',
  `operator_user_id` bigint DEFAULT NULL COMMENT '操作人用户编号',
  `from_status` varchar(32) DEFAULT NULL COMMENT '变更前状态',
  `to_status` varchar(32) DEFAULT NULL COMMENT '变更后状态',
  `reason` varchar(1000) DEFAULT NULL COMMENT '原因',
  `evidence_refs` json DEFAULT NULL COMMENT '证据引用',
  `related_object_refs` json DEFAULT NULL COMMENT '关联业务对象引用',
  `occurred_at` datetime NOT NULL COMMENT '实际发生时间',
  `idempotency_key` varchar(128) NOT NULL COMMENT '幂等键',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_idempotency` (`tenant_id`, `idempotency_key`),
  KEY `idx_tenant_aggregate_occurred_at` (`tenant_id`, `aggregate_type`, `aggregate_id`, `occurred_at`),
  KEY `idx_tenant_event_type` (`tenant_id`, `event_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ZSJOS 只追加业务事件';
