package cn.iocoder.yudao.module.zsjos.service.delivery;
import cn.iocoder.yudao.module.zsjos.controller.admin.delivery.vo.StudentDeliveryDeferReqVO; import cn.iocoder.yudao.module.zsjos.dal.dataobject.delivery.*; import cn.iocoder.yudao.module.zsjos.dal.mysql.delivery.*; import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper; import jakarta.annotation.Resource; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import cn.iocoder.yudao.module.bpm.api.task.BpmProcessInstanceApi; import cn.iocoder.yudao.module.bpm.api.task.dto.BpmProcessInstanceCreateReqDTO; import java.util.*;
import cn.iocoder.yudao.module.bpm.enums.task.BpmProcessInstanceStatusEnum;
@Service public class StudentDeliveryDeferServiceImpl implements StudentDeliveryDeferService { @Resource private StudentDeliveryDeferMapper deferMapper; @Resource private StudentDeliveryStageMapper stageMapper;
 @Resource private BpmProcessInstanceApi processInstanceApi;
 @Override @Transactional public void handleProcessResult(String processId, Integer status, String reason) { StudentDeliveryDeferDO row=deferMapper.selectByProcessInstanceId(processId); if(row==null||!"PENDING".equals(row.getStatus())) return; boolean approved=BpmProcessInstanceStatusEnum.APPROVE.getStatus().equals(status); row.setStatus(approved?"APPROVED":"REJECTED").setDecisionReason(reason); deferMapper.updateById(row); stageMapper.update(null,new com.baomidou.mybatisplus.core.conditions.update.LambdaUpdateWrapper<StudentDeliveryStageDO>().eq(StudentDeliveryStageDO::getId,row.getStageId()).eq(StudentDeliveryStageDO::getStatus,"DEFER_PENDING").set(StudentDeliveryStageDO::getStatus,"PENDING").set(StudentDeliveryStageDO::getDueAt,approved?row.getOriginalDueAt().plusDays(row.getRequestedDays()):row.getOriginalDueAt())); }
 @Override @Transactional public StudentDeliveryDeferDO request(StudentDeliveryDeferReqVO req) { if(req.getRequestedDays()<1||req.getRequestedDays()>3) throw new IllegalArgumentException("延期只能选择1至3天"); StudentDeliveryStageDO stage=stageMapper.selectById(req.getStageId()); if(stage==null||!("PENDING".equals(stage.getStatus())||"OVERDUE".equals(stage.getStatus()))) throw new IllegalStateException("当前阶段不可申请延期"); StudentDeliveryDeferDO old=deferMapper.selectOne(new LambdaQueryWrapper<StudentDeliveryDeferDO>().eq(StudentDeliveryDeferDO::getStageId,req.getStageId()).eq(StudentDeliveryDeferDO::getStatus,"PENDING")); if(old!=null)return old; if(req.getSupervisorUserId()==null) throw new IllegalStateException("未找到编导上级"); StudentDeliveryDeferDO row=new StudentDeliveryDeferDO().setStageId(req.getStageId()).setRequestedBy(req.getRequestedBy()).setSupervisorUserId(req.getSupervisorUserId()).setRequestedDays(req.getRequestedDays()).setOriginalDueAt(stage.getDueAt()).setReason(req.getReason()).setStatus("PENDING"); deferMapper.insert(row); stageMapper.update(null,new com.baomidou.mybatisplus.core.conditions.update.LambdaUpdateWrapper<StudentDeliveryStageDO>().eq(StudentDeliveryStageDO::getId,stage.getId()).eq(StudentDeliveryStageDO::getStatus,stage.getStatus()).set(StudentDeliveryStageDO::getStatus,"DEFER_PENDING")); BpmProcessInstanceCreateReqDTO process=new BpmProcessInstanceCreateReqDTO(); process.setProcessDefinitionKey("zsjos_student_contact_extension"); process.setBusinessKey("student-delivery-defer:"+row.getId()); process.setVariables(new HashMap<>(Map.of("extensionId",row.getId(),"stageId",stage.getId(),"requestedDays",row.getRequestedDays(),"reason",row.getReason()))); process.setStartUserSelectAssignees(Map.of("deliverySupervisorReview",List.of(req.getSupervisorUserId()))); row.setBpmProcessInstanceId(processInstanceApi.createProcessInstance(req.getRequestedBy(),process)); deferMapper.updateById(row); return row; }
}
