import DiagnosisReminder from '../src/components/DiagnosisReminder';
import {OverlayCoordinatorProvider} from '../src/components/OverlayCoordinator';
import {BrowserRouter} from 'react-router-dom';
// UTF-8. Actual components with isolated synthetic transport; never writes real business data.
import {createRoot} from 'react-dom/client';import {App,ConfigProvider} from 'antd';
import AccountProfilePanel from '../src/components/AccountProfilePanel';import {StudentDeliveryPanel} from '../src/components/StudentDeliveryPanel';
import ThemeProvider from '../src/components/Theme/ThemeProvider';import {http} from '../src/services/api';import '../src/styles/index.css';
let version=1;let content=JSON.stringify({cycle:1,currentStage:'s0',currentStageLabel:'S0',accountStatus:'normal',accountStatusLabel:'正常',primaryProblem:'content',primaryProblemLabel:'内容表达',primaryProblemEvidence:'需要具体案例',cooperationLevel:'a',cooperationLevelLabel:'配合积极',cooperationEvidence:'每周按时沟通',secondaryProblem:'content',secondaryProblemLabel:'内容表达',secondaryProblemEvidence:'继续观察',conclusion:'表达清晰，案例需要补充',improvementMeasures:'每周补充两个案例',observedData:'完播率与有效客资',reposition:false});
const entry=()=>({id:version,kind:'DIAGNOSIS',fieldKey:'diagnosis_7d',title:'7天账号数据诊断',content,files:[],snapshots:[],operatedBy:'测试编导',operatedAt:1789704000000,resultVersion:version});
const fields=[{key:'delivery_goals',label:'内部交付目标约定',type:'textarea',group:'REVIEW',ownerType:'AUTO',enabled:true},{key:'diagnosis_14d',label:'14天验证指标诊断',type:'record',group:'REVIEW',ownerType:'DIRECTOR',enabled:true},{key:'adjustment_28d',label:'28天调整触发条件',type:'record',group:'REVIEW',ownerType:'DIRECTOR',enabled:true},{key:'diagnosis_7d',label:'7天账号数据诊断',type:'record',group:'REVIEW',ownerType:'DIRECTOR',enabled:true},{key:'student_commitments',label:'学员承担事项',type:'textarea',group:'REVIEW',ownerType:'DIRECTOR',enabled:true}];
if (new URLSearchParams(location.search).has('layout')) fields.push(
  ...['publish_rhythm', 'account_position', 'professional_position', 'stage', 'current_status', 'bottleneck', 'content_format'].map(key => ({ key, label: key, type: 'select', group: 'STATUS', ownerType: 'AUTO', enabled: true })),
  { key: 'homepage', label: '主页链接', type: 'url', group: 'PROFILE', ownerType: 'OPERATOR', enabled: true },
  { key: 'company_commitments', label: '公司承担事项', type: 'textarea', group: 'REVIEW', ownerType: 'DIRECTOR', enabled: true },
);
const stage={id:1,stageCode:'S0',version:0,status:'PENDING',canSubmit:true,canDefer:true,agreement:{agreement:'完成主页搭建\n确认第一批作品计划',submissionNo:2,references:[]},defers:[] as unknown[],dueAt:1789704000000,confirmation:undefined as unknown};
let seen=false;
const todos=()=>[7,14,28].map(days=>({taskId:days,accountId:900001,studentPersonId:1,accountName:'交付验收账号',title:`${days}天诊断`,templateType:`diagnosis_${days}d`,cycle:1,dueAt:1789704000000,payload:{requirementSnapshot:{diagnosis_7d:'检查播放和互动数据',diagnosis_14d:'验证咨询转化指标',diagnosis_28d:'连续低于目标时调整选题'},source:{submissionNo:2}}}));
http.defaults.adapter=async config=>{const url=config.url||'';let data:unknown; if(url.includes('dict-data'))data=[['zsjos_media_account_stage','s0','S0'],['zsjos_media_account_current_status','normal','正常'],['zsjos_media_account_primary_problem','content','内容表达'],['zsjos_media_account_cooperation_level','a','配合积极']].map(([dictType,value,label])=>({dictType,value,label,status:0}));
else if(url.endsWith('/diagnosis/reminders'))data=seen?[]:todos();
else if(url.endsWith('/diagnosis/acknowledge')){seen=true;data=true}
else if(url.endsWith('/diagnosis/tasks'))data=[7,14,28].map(days=>({taskId:days,accountId:900001,studentPersonId:1,accountName:'交付验收账号',title:`${days}天诊断`,templateType:`diagnosis_${days}d`,cycle:1,dueAt:1789704000000,payload:{requirementSnapshot:{diagnosis_7d:'检查播放和互动数据',diagnosis_14d:'验证咨询转化指标',diagnosis_28d:'连续低于目标时调整选题'},source:{submissionNo:2}}}));
else if(url.endsWith('/diagnosis')){content=JSON.stringify({...JSON.parse(content),...JSON.parse(config.data)});data=++version}
else if(url.endsWith('/history'))data={list:config.params?.kind==='PROFILE'?[]:[entry()],total:config.params?.kind==='PROFILE'?0:1};
else if(url.endsWith('/profile'))data={account:{id:900001,nickname:'交付验收账号',version,availableActions:['MAINTAIN_ACCOUNT']},config:{id:1,fields,versionNo:1},diagnosisContext:{submissionNo:2,syncedAt:'2026-09-18 12:00',anchorAt:'2026-08-01T00:00:00'},positioningRequirements:{diagnosis_7d:'检查播放和互动数据',diagnosis_14d:'验证咨询转化指标',diagnosis_28d:'连续低于目标时调整选题'},values:{...Object.fromEntries(fields.filter(f=>f.type==='select').map(f=>[f.key,'stored-code'])),homepage:'https://example.com/account',company_commitments:'保留公司承担事项全文',delivery_goals:'内部目标只读，自动覆盖',student_commitments:'每周提供两个案例\n按时完成学习任务'},snapshots:fields.filter(f=>f.type==='select').map(f=>({key:f.key,displayValue:f.key==='account_position'?'事业化经营号、轻创实践记录号':`已保存标签-${f.key}`})),files:{},sourceNotes:{},editableFields:fields.filter(f=>f.ownerType==='DIRECTOR').map(f=>f.key),missingFields:[],missingByOwner:{},latestRecords:{diagnosis_7d:entry()},canViewHistory:true,canSubmitDiagnosis:true,diagnosisStarted:true};
else if(url.endsWith('/student-delivery/plan'))data={id:1,roundNo:1,status:'ACTIVE',sourceAvailable:true,notificationRecipient:'测试部门负责人',stages:[stage],rounds:[{id:1,roundNo:1,status:'ACTIVE'}]};
else if(url.endsWith('/student-delivery/defer')){const d=JSON.parse(config.data);stage.defers.push({id:1,reason:d.reason,newDueAt:d.newDueAt,createdAt:1789704000000,status:'EFFECTIVE'});stage.dueAt=d.newDueAt;data={id:1}}
else if(url.endsWith('/student-delivery/submission')){stage.status='COMPLETED';stage.canSubmit=false;stage.canDefer=false;stage.confirmation=JSON.parse(JSON.parse(config.data).fieldValuesJson);data={id:1}}
else data=[];return {config,status:200,statusText:'OK',headers:{},data:{code:0,data}}};
createRoot(document.getElementById('root')!).render(<ConfigProvider><ThemeProvider><App><BrowserRouter><OverlayCoordinatorProvider>{new URLSearchParams(location.search).has("reminders") && <DiagnosisReminder enabled/>}<div style={{padding:16}}><AccountProfilePanel account={{id:900001,version:1,availableActions:['MAINTAIN_ACCOUNT']} as never} canQuery canMaintain onSaved={async()=>{}} deliveryActions={<StudentDeliveryPanel accountId={900001} submittedBy={1} canQuery canSubmit canDefer/>}/></div></OverlayCoordinatorProvider></BrowserRouter></App></ThemeProvider></ConfigProvider>);
