# -*- coding: utf-8 -*-
"""Real components with synthetic transport; never sends employee notifications."""
import os
import re
import tempfile
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

base = os.environ.get('WORKBENCH_TEST_URL', 'http://localhost:5175')
out = Path(tempfile.gettempdir()) / 'calendar-notification-browser'
out.mkdir(exist_ok=True)
with sync_playwright() as p:
    browser = p.chromium.launch(channel='chrome', headless=True)
    for width in [1440, 390]:
        page = browser.new_page(viewport={'width': width, 'height': 900})
        errors = []
        page.on('pageerror', lambda error: errors.append(str(error)))
        for kind in ['EXAM', 'COURSE']:
            url = base + '/test/calendar-notification.html?type=' + kind
            page.goto(url)
            submit = page.get_by_role('button', name='提交发送')
            preview = page.get_by_role('button', name='预览通知')
            expect(preview).to_be_disabled()
            page.get_by_role('radio', name='全员通知').check()
            preview.click()
            expect(page.get_by_text('测试课程（线上）')).to_be_visible()
            expect(submit).to_be_disabled()
            page.get_by_role('checkbox', name='确认向当前租户', exact=False).check()
            page.evaluate('window.calendarFixture.fail = 1900092009')
            submit.click()
            expect(page.get_by_text('测试发送失败，请重新预览或重试')).to_be_visible()
            expect(submit).to_be_disabled()
            preview.click()
            page.get_by_role('checkbox', name='确认向当前租户', exact=False).check()
            page.evaluate('window.calendarFixture.fail = 0')
            submit.dblclick()
            expect(page.get_by_text('已提交发送', exact=True)).to_be_visible()
            requests = page.evaluate('window.calendarFixture.requests')
            assert len(requests) == 2
            assert requests[0]['idempotencyKey'] == requests[1]['idempotencyKey']
            assert requests[1]['calendarVersion'] == 3 and requests[1]['previewToken'] == 'preview-2'
            assert 'title' not in requests[1]
            page.goto(url + '&specified=1')
            expect(page.get_by_role('radio', name='全员通知')).to_have_count(0)
            combo = page.get_by_role('combobox')
            expect(combo).to_be_enabled()
            assert page.evaluate('window.calendarFixture.pages') == [1, 2]
            expect(page.get_by_role('button', name='下一页')).to_have_count(0)
            combo.click()
            def check_node(name):
                page.locator('.ant-select-tree-treenode').filter(has=page.get_by_text(name, exact=True)).locator('.ant-select-tree-checkbox').click()
            check_node('教务部')
            expect(page.get_by_text('已选 2 人', exact=False)).to_be_visible()
            combo.fill('员工丙')
            check_node('员工丙')
            combo.fill('')
            combo.press('Escape')
            expect(page.get_by_text('已选 3 人', exact=False)).to_be_visible()
            preview.click()
            expect(page.get_by_text('测试课程（线上）')).to_be_visible()
            page.get_by_role('checkbox', name='再次提醒已通知人员').check()
            expect(submit).to_be_disabled()
            preview.click()
            expect(submit).to_be_enabled()
            combo.click()
            combo.fill('分页员工103')
            check_node('分页员工103')
            combo.fill('')
            combo.press('Escape')
            expect(submit).to_be_disabled()
            expect(page.get_by_text('已选 4 人', exact=False)).to_be_visible()
            combo.click()
            combo.fill('分页员工103')
            check_node('分页员工103')
            combo.fill('')
            combo.press('Escape')
            expect(page.get_by_text('已选 3 人', exact=False)).to_be_visible()
            preview.click()
            page.evaluate('window.calendarFixture.fail = 1900092008')
            submit.click()
            expect(page.get_by_text('测试发送失败，请重新预览或重试')).to_be_visible()
            expect(submit).to_be_disabled()
            expect(page.get_by_text('已选 3 人', exact=False)).to_be_visible()
            page.evaluate('window.calendarFixture.fail = 0')
            preview.click()
            combo.click()
            combo.fill('教务')
            expect(page.get_by_text('员工甲', exact=True).last).to_be_visible()
            page.screenshot(path=str(out / f'{kind}-tree-{width}.png'), full_page=True, animations='disabled')
            combo.fill('')
            combo.press('Escape')
            page.screenshot(path=str(out / f'{kind}-{width}.png'), full_page=True, animations='disabled')
            assert page.evaluate('document.documentElement.scrollWidth <= innerWidth')
            submit.click()
            expect(page.get_by_text('已提交发送', exact=True)).to_be_visible()
            request = page.evaluate('window.calendarFixture.requests.at(-1)')
            assert sorted(request['userIds']) == [1, 2, 3] and request['resend'] is True
            page.goto(url + '&denied=1')
            expect(submit).to_be_disabled()
            expect(page.get_by_text('没有当前范围的通知权限，请联系管理员授权')).to_be_visible()
            assert page.evaluate('window.calendarFixture.pages') == []
            page.goto(url + '&loadError=1')
            expect(page.get_by_text('测试员工加载失败')).to_be_visible()
            expect(preview).to_be_disabled()
            page.evaluate('window.calendarFixture.loadFail = false')
            page.get_by_role('button', name=re.compile(r'重\s*试')).click()
            expect(page.get_by_role('combobox')).to_be_enabled()
            page.get_by_role('combobox').click()
            check_node('教务部')
            page.get_by_role('combobox').press('Escape')
            page.locator('.ant-select').hover()
            page.locator('.ant-select-clear').click()
            expect(preview).to_be_disabled()
            expect(page.get_by_text('已选 0 人', exact=False)).to_be_visible()
            page.goto(url + '&empty=1')
            expect(page.get_by_role('combobox')).to_be_enabled()
            page.get_by_role('combobox').click()
            expect(page.get_by_text('没有匹配的部门或员工')).to_be_visible()
            expect(preview).to_be_disabled()
            page.goto(url + '&slow=1')
            expect(page.get_by_role('combobox')).to_be_disabled()
            expect(page.get_by_text('正在加载部门和员工…')).to_be_visible()
            expect(page.get_by_role('combobox')).to_be_enabled()
        assert not errors, errors
        page.close()
    browser.close()
print('PASS: both calendars, desktop/mobile, nested department selection, cross-department search, all candidate pages, clear, loading/empty/error/retry/permissions, version conflict selection retention and double-submit guard')
