# -*- coding: utf-8 -*-
from pathlib import Path
import os
import re
import tempfile
from playwright.sync_api import sync_playwright, expect

base = os.environ.get('CASHBACK_TABS_BASE_URL', 'http://localhost:5175')
out = Path(tempfile.gettempdir()) / 'cashback-tabs-browser'
out.mkdir(exist_ok=True)
with sync_playwright() as p:
    browser = p.chromium.launch(channel='chrome', headless=True)
    page = browser.new_page(viewport={'width': 1440, 'height': 1000}, reduced_motion='reduce')
    errors = []
    page.on('pageerror', lambda error: errors.append(str(error)))
    page.goto(base + '/test/cashback-tabs.html')
    types = page.locator('[aria-label="返现类型"]')
    statuses = page.locator('[aria-label="返现状态"]')
    def tab(group, label):
        return group.get_by_role('tab', name=label, exact=True)
    def wait_body(expression):
        page.wait_for_function('cashbackTabsFixture.calls.length && (' + expression + ')')
    def row(number):
        return page.get_by_text(number, exact=True).first
    expect(row('CB-valid-pending-1')).to_be_visible()
    expect(tab(types, '全部')).to_have_attribute('aria-selected', 'true')
    expect(tab(statuses, '全部')).to_have_attribute('aria-selected', 'true')
    tab(types, '成交返现').click()
    wait_body("cashbackTabsFixture.calls.at(-1).body.type === 'deal'")
    tab(statuses, '可提现').click()
    expect(row('CB-deal-available-1')).to_be_visible()
    page.locator('.ant-pagination-item-2').click()
    expect(row('CB-deal-available-11')).to_be_visible()
    tab(statuses, '不可提现').click()
    expect(row('CB-deal-blocked-1')).to_be_visible()
    wait_body("cashbackTabsFixture.calls.at(-1).body.pageNo === 1")
    tab(types, '全部').click()
    expect(row('CB-valid-blocked-1')).to_be_visible()
    wait_body("!cashbackTabsFixture.calls.at(-1).body.type && cashbackTabsFixture.calls.at(-1).body.status === 'blocked'")
    tab(types, '有效返现').click()
    tab(statuses, '全部').click()
    expect(row('CB-valid-pending-1')).to_be_visible()
    wait_body("cashbackTabsFixture.calls.at(-1).body.type === 'valid' && !cashbackTabsFixture.calls.at(-1).body.status")
    search = page.get_by_placeholder('返现编号 / 客资编号 / 姓名', exact=True)
    search.fill('  -available-  ')
    page.get_by_role('button', name=re.compile(r'查\s*询')).click()
    expect(row('CB-valid-available-1')).to_be_visible()
    tab(types, '升级返现').click()
    expect(row('CB-upgrade-available-1')).to_be_visible()
    wait_body("cashbackTabsFixture.calls.at(-1).body.keyword === '-available-'")
    tab(statuses, '已结算').click()
    expect(page.get_by_text('当前筛选下暂无返现记录', exact=True)).to_be_visible()
    search.fill(''); search.press('Enter')
    expect(row('CB-upgrade-settled-1')).to_be_visible()
    page.evaluate('cashbackTabsFixture.delay = 700')
    tab(types, '有效返现').click()
    wait_body("cashbackTabsFixture.calls.at(-1).body.type === 'valid'")
    page.evaluate('cashbackTabsFixture.delay = 0')
    tab(types, '成交返现').click()
    expect(row('CB-deal-settled-1')).to_be_visible()
    page.wait_for_timeout(850)
    expect(row('CB-deal-settled-1')).to_be_visible()
    page.evaluate('cashbackTabsFixture.fail = true')
    tab(statuses, '可提现').click()
    expect(page.get_by_text('列表加载失败，请重试', exact=False).first).to_be_visible()
    page.evaluate('cashbackTabsFixture.fail = false')
    page.get_by_role('button', name=re.compile(r'重\s*试')).first.click()
    expect(row('CB-deal-available-1')).to_be_visible()
    page.screenshot(path=str(out / 'desktop.png'), full_page=True)
    page.set_viewport_size({'width': 390, 'height': 844})
    expect(tab(types, '全部')).to_be_visible()
    expect(tab(statuses, '全部')).to_be_visible()
    tab(types, '全部').click(); tab(statuses, '全部').click()
    expect(row('CB-valid-pending-1')).to_be_visible()
    expect(tab(types, '全部')).to_have_attribute('aria-selected', 'true')
    expect(tab(statuses, '全部')).to_have_attribute('aria-selected', 'true')
    page.wait_for_timeout(300)
    page.screenshot(path=str(out / 'mobile.png'), full_page=True)
    page.set_viewport_size({'width': 1440, 'height': 1000})
    page.goto(base + '/test/cashback-tabs.html?catalog-error')
    expect(page.get_by_text('筛选选项加载失败，请重试', exact=True)).to_be_visible()
    expect(tab(types, '全部')).to_have_attribute('aria-disabled', 'true')
    page.evaluate('cashbackTabsFixture.catalogFail = false')
    page.get_by_role('button', name=re.compile(r'重\s*试')).first.click()
    expect(tab(types, '有效返现')).to_be_visible()
    page.goto(base + '/test/cashback-tabs.html?catalog-empty')
    expect(types.get_by_role('tab')).to_have_count(1)
    expect(statuses.get_by_role('tab')).to_have_count(1)
    page.goto(base + '/test/cashback-tabs.html?personal')
    expect(row('CB-valid-pending-1')).to_be_visible()
    wait_body("cashbackTabsFixture.calls.at(-1).url.endsWith('/my-page')")
    page.goto(base + '/test/cashback-tabs.html?unauthorized')
    expect(page.get_by_text('无权查看返现记录', exact=True).first).to_be_visible()
    assert page.evaluate('cashbackTabsFixture.calls.length') == 0
    assert not errors, errors
    browser.close()
print('PASS: tab intersection, both All filters, pagination reset, keyword, empty, stale responses, retry, catalog failure/empty, personal/unauthorized, desktop/mobile')
print('Screenshots:', out)
