# UTF-8. Browser acceptance uses synthetic fixtures only.
from pathlib import Path
import tempfile,re,json,os
from playwright.sync_api import sync_playwright,expect
out=Path(tempfile.gettempdir())/'cashback-browser';out.mkdir(exist_ok=True)
with sync_playwright() as p:
 browser=p.chromium.launch(channel='chrome',headless=True)
 for frontend,base in [('workbench',os.getenv('CASHBACK_WB','http://localhost:5175')),('admin',os.getenv('CASHBACK_ADMIN','http://localhost:80'))]:
  page=browser.new_page(viewport={'width':1440,'height':1000});errors=[]
  page.on('pageerror',lambda e:errors.append(str(e)))
  page.goto(base+'/test/cashback-control.html')
  page.get_by_role('button',name='禁止提现',exact=True).first.click()
  modal=page.get_by_role('dialog',name='禁止提现',exact=True)
  expect(modal.get_by_text('该原因将展示给兼职',exact=True)).to_be_visible()
  submit=modal.get_by_role('button',name=re.compile('确认禁止提现|确.*定'))
  submit.click();expect(modal.get_by_text(re.compile('请填写.*操作原因|请填写1至500字'))).to_be_visible()
  modal.get_by_role('textbox').fill('  核实后暂不可提现  ')
  page.evaluate('cashbackFixture.fail=true');submit.click()
  expect(modal.get_by_text('返现状态已变化，请刷新后重试',exact=True)).to_be_visible()
  expect(modal.get_by_role('textbox')).to_have_value('  核实后暂不可提现  ')
  page.evaluate('cashbackFixture.fail=false;cashbackFixture.delay=700')
  submit.click();expect(modal.get_by_role('button',name=re.compile('取.*消'))).to_be_disabled()
  expect(modal).not_to_be_visible()
  expect(page.get_by_role('button',name='恢复提现',exact=True).first).to_be_visible()
  assert page.evaluate('cashbackFixture.calls.at(-1).body.reason')=='核实后暂不可提现'
  page.get_by_role('button',name='详情',exact=True).first.click()
  drawer=page.get_by_role('dialog',name='返现详情',exact=True)
  expect(drawer.get_by_text('该笔返现已禁止提现',exact=True)).to_be_visible()
  expect(drawer.get_by_text('核实后暂不可提现',exact=True).first).to_be_visible()
  expect(drawer.get_by_text('验收财务',exact=True)).to_be_visible()
  page.wait_for_timeout(400)
  page.screenshot(path=str(out/(frontend+'-desktop.png')),full_page=True)
  page.set_viewport_size({'width':390,'height':844})
  expect(drawer.get_by_role('button',name='恢复提现',exact=True)).to_be_visible()
  page.wait_for_timeout(400)
  page.screenshot(path=str(out/(frontend+'-mobile.png')),full_page=True)
  drawer.get_by_role('button',name='恢复提现',exact=True).click()
  modal=page.get_by_role('dialog',name='恢复提现',exact=True)
  expect(modal.get_by_text('恢复后按原结算条件判断是否可提现，不重新计算金额。',exact=True)).to_be_visible()
  modal.get_by_role('textbox').fill('已核实可恢复')
  modal.get_by_role('button',name=re.compile('确认恢复提现|确.*定')).click()
  expect(modal).not_to_be_visible()
  expect(drawer.get_by_role('button',name='禁止提现',exact=True)).to_be_visible()
  expect(drawer.get_by_text('已核实可恢复',exact=True)).to_be_visible()
  page.goto(base+'/test/cashback-control.html?read-only')
  expect(page.get_by_text('CB-TEST-001',exact=True).first).to_be_visible()
  expect(page.get_by_role('button',name='禁止提现',exact=True)).to_have_count(0)
  assert not errors,errors
  print(frontend,'PASS: list/detail, validation, failure retention, busy lock, reason, restore, history, permission, desktop/mobile')
  page.close()
 page=browser.new_page(viewport={'width':1440,'height':1000})
 page.goto(os.getenv('CASHBACK_H5','http://127.0.0.1:10087')+'/test/cashback-control.html')
 expect(page.get_by_text('不可提现',exact=True)).to_be_visible()
 expect(page.get_by_text('核实后暂不可提现',exact=True)).to_be_visible()
 page.get_by_text('查看详情',exact=False).first.click()
 expect(page.get_by_text('收益详情',exact=True)).to_be_visible()
 expect(page.get_by_role('button',name='去提现',exact=True)).to_have_count(0)
 for width,height,label in [(1440,1000,'desktop'),(390,844,'mobile')]:
  page.set_viewport_size({'width':width,'height':height})
  reason=page.locator('.earnings-detail__row').filter(has_text='不可提现原因')
  reason.scroll_into_view_if_needed()
  expect(reason).to_contain_text('核实后暂不可提现')
  expect(reason).to_be_visible()
  page.wait_for_timeout(400)
  page.screenshot(path=str(out/('h5-'+label+'.png')),full_page=True)
 print('h5 PASS: blocked status/reason, detail, no withdrawal action, desktop/mobile')
 page.close()
 browser.close()
print('Screenshots:',out)
