# -*- coding: utf-8 -*-
"""Real Workbench forms with synthetic transport; no live business writes."""
from pathlib import Path
import tempfile
from playwright.sync_api import sync_playwright, expect

out = Path(tempfile.mkdtemp(prefix='free-exam-browser-'))
out.mkdir(exist_ok=True)
with sync_playwright() as p:
    browser = p.chromium.launch(channel='chrome', headless=True)
    for width in [1440, 390]:
        page = browser.new_page(viewport={'width': width, 'height': 960})
        errors = []
        page.on('pageerror', lambda error: errors.append(str(error)))
        page.goto('http://localhost:5175/test/free-exam.html')
        expect(page.get_by_role('switch', name='显示多日考期')).to_be_checked()
        expect(page.get_by_text('多日 · 秋季多日考试', exact=False).first).to_be_visible()
        page.get_by_role('switch', name='显示多日考期').click()
        expect(page.get_by_text('多日 · 秋季多日考试', exact=False)).to_have_count(0)
        page.get_by_role('switch', name='显示多日考期').click()
        page.locator('.exam-multiDay-bar').first.click()
        detail = page.get_by_role('dialog')
        expect(detail.get_by_text('时间类型', exact=True)).to_have_count(0)
        expect(detail.get_by_text('当前状态', exact=True)).to_have_count(0)
        expect(detail.get_by_text('时间', exact=True)).to_be_visible()
        expect(detail.locator('.ant-modal-title .ant-tag')).to_have_text('已发布')
        page.wait_for_function("!document.querySelector('.ant-modal')?.className.includes('zoom-')")
        page.screenshot(path=str(out / f'exam-detail-{width}.png'), full_page=True, animations='disabled')
        expect(page.get_by_role('dialog').get_by_text('开始日至结束日均属于本次考试安排（含首尾日期）。')).to_be_visible()
        page.get_by_role('dialog').get_by_role('button', name='Close').click()
        page.locator('.exam-month-day').filter(has=page.locator('.exam-month-date')).nth(10).locator('.exam-month-date').click()
        expect(page.get_by_role('dialog').get_by_text('当天多日考试', exact=True)).to_be_visible()
        page.get_by_role('dialog').get_by_role('button', name='Close').click()
        expect(page.get_by_role('dialog')).to_have_count(0)
        page.screenshot(path=str(out / f'multi-day-calendar-{width}.png'), full_page=True)
        assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth')
        page.get_by_role('button', name='新增考期').click()
        dialog = page.get_by_role('dialog')
        expect(dialog.get_by_label('考期名称')).to_have_value('')
        expect(dialog.get_by_text('单日', exact=True)).to_be_visible()
        expect(dialog.get_by_text('多日', exact=True)).to_be_visible()
        expect(dialog.get_by_label('日期', exact=True)).to_be_visible()
        expect(dialog.get_by_text('产品', exact=True)).to_have_count(0)
        page.get_by_role('button', name='保存草稿').click()
        expect(dialog.get_by_text('请填写考期名称', exact=True)).to_be_visible()
        dialog.get_by_label('考期名称').fill('自由命名秋季场')
        page.evaluate('window.freeExamFixture.fail = true')
        page.get_by_role('button', name='保存草稿').click()
        expect(page.get_by_text('测试保存失败')).to_be_visible()
        expect(dialog.get_by_label('考期名称')).to_have_value('自由命名秋季场')
        page.evaluate('window.freeExamFixture.fail = false')
        page.screenshot(path=str(out / f'exam-{width}.png'), full_page=True)
        page.get_by_role('button', name='保存并发布').click()
        expect(dialog).to_have_count(0)
        expect(page.get_by_text('自由命名秋季场', exact=True)).to_be_visible()
        request = page.evaluate('window.freeExamFixture.requests.at(-1)')
        assert request['scheduleName'] == '自由命名秋季场'
        assert not {'productId', 'categoryId', 'selectedAttrs'} & request.keys()
        page.get_by_role('button', name='新增考期').click()
        dialog = page.get_by_role('dialog')
        dialog.get_by_label('考期名称').fill('确定多日考试')
        dialog.get_by_text('多日', exact=True).click()
        expect(dialog.get_by_placeholder('开始日期')).to_have_value('')
        dialog.get_by_placeholder('开始日期').fill('2099-10-10')
        dialog.get_by_placeholder('结束日期').fill('2099-10-12')
        dialog.get_by_placeholder('结束日期').press('Enter')
        dialog.get_by_label('考期名称').click()
        dialog.get_by_role('button', name='保存草稿').click()
        expect(dialog).to_have_count(0)
        saved = page.evaluate('window.freeExamFixture.requests.at(-1)')
        assert saved['scheduleType'] == 'MULTI_DAY'
        assert saved['startDate'] == '2099-10-10' and saved['endDate'] == '2099-10-12'
        assert 'exactDate' not in saved and 'roughStartDate' not in saved
        page.goto('http://localhost:5175/test/free-exam.html?class')
        page.get_by_role('button', name='创建班级').click()
        dialog = page.get_by_role('dialog')
        expect(dialog.get_by_label('班级名称')).to_have_value('')
        expect(dialog.get_by_text('SKU', exact=True)).to_have_count(0)
        dialog.get_by_label('班级名称').fill('自由命名一班')
        dialog.get_by_label('考期', exact=True).click()
        page.locator('.ant-select-item-option').filter(has_text='自由考试').click()
        dialog.get_by_label('班主任', exact=True).click()
        page.locator('.ant-select-item-option').filter(has_text='测试班主任').click()
        dialog.get_by_label('班级名称').click()
        page.screenshot(path=str(out / f'class-{width}.png'), full_page=True)
        dialog.get_by_role('button', name='确 定').click()
        expect(dialog).to_have_count(0)
        assert page.evaluate('window.freeExamFixture.requests[0]') == {'className': '自由命名一班', 'examScheduleId': 7, 'homeroomUserId': 8}
        assert not errors, errors
        page.close()
    browser.close()
print(f'PASS Workbench free exam/class forms at 1440 and 390, required names, failure retention and no catalog fields; screenshots: {out}')
