# UTF-8. Real Chrome with synthetic HTTP only; verifies both existing frontend consumers.
from pathlib import Path
import re
from playwright.sync_api import sync_playwright, expect
OUT=Path('D:/ZSJ-OS-backups/lead-sales-stage-browser');OUT.mkdir(parents=True,exist_ok=True)

def choose(page, control, text):
    control.click()
    page.locator('.ant-select-dropdown:visible .ant-select-item-option-content').filter(has_text=re.compile('^'+re.escape(text)+'$')).click()

with sync_playwright() as p:
    browser=p.chromium.launch(channel='chrome',headless=True)
    page=browser.new_page(viewport={'width':1440,'height':1000})
    errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
    page.goto('http://127.0.0.1:5174/test/lead-sales-stage.html')
    form=page.locator('.fu-panel-form-wrapper')
    expect(form.get_by_label('跟进后销售阶段')).to_be_visible()
    expect(form.get_by_text('历史已触达名称',exact=True)).to_be_visible()
    expect(page.get_by_text('销售阶段：历史待触达 → 历史已触达名称')).to_be_visible()
    expect(page.get_by_text('销售阶段：未记录',exact=True)).to_be_visible()
    choose(page,form.get_by_label('跟进方式',exact=True),'电话')
    choose(page,form.get_by_label('跟进结果',exact=True),'取得联系')
    choose(page,form.get_by_label('跟进后销售阶段'),'意向客户')
    form.get_by_label('跟进备注').fill('阶段推进验收')
    form.get_by_role('button',name='+1 天',exact=True).click()
    page.screenshot(path=str(OUT/'workbench-desktop.png'),full_page=True)
    page.evaluate('stageFixture.saveError=true')
    form.get_by_role('button',name='提交跟进').click();expect(page.get_by_role('button',name='确认执行')).not_to_have_class(re.compile('.*ant-btn-loading.*'));page.get_by_role('button',name='确认执行').click()
    expect(page.get_by_text('阶段提交失败，请重试')).to_be_visible()
    expect(page.get_by_role('button',name='确认执行')).not_to_be_visible()
    expect(form.get_by_role('button',name='提交跟进')).not_to_have_class(re.compile('ant-btn-loading'))
    key=page.evaluate('stageFixture.payload.idempotencyKey')
    expect(page.get_by_text('阶段提交失败，请重试')).not_to_be_visible(timeout=10000)
    page.evaluate('stageFixture.saveError=false')
    form.get_by_role('button',name='提交跟进').click();expect(page.get_by_role('button',name='确认执行')).not_to_have_class(re.compile('.*ant-btn-loading.*'));page.get_by_role('button',name='确认执行').click()
    expect(page.get_by_test_id('current')).to_contain_text('意向客户')
    assert page.evaluate('stageFixture.payload.salesStage')=='intent_customer'
    assert page.evaluate('stageFixture.payload.idempotencyKey')==key
    assert 'salesStageLabelSnapshot' not in page.evaluate('stageFixture.payload')
    page.get_by_role('button',name='弹窗跟进').click();dialog=page.get_by_role('dialog')
    expect(dialog.get_by_label('跟进后销售阶段')).to_be_visible()
    choose(page,dialog.get_by_label('跟进方式',exact=True),'电话')
    choose(page,dialog.get_by_label('跟进结果',exact=True),'取得联系')
    choose(page,dialog.get_by_label('跟进后销售阶段'),'待触达')
    dialog.get_by_label('跟进备注').fill('允许阶段回退')
    dialog.get_by_role('button',name='+1 天',exact=True).click()
    dialog.get_by_role('button',name='提交跟进').click();page.get_by_role('button',name='确认执行').click()
    expect(page.get_by_test_id('current')).to_contain_text('待触达')
    page.locator('.advanced-filter-toolbar button.ant-btn').click()
    drawer=page.locator('.advanced-filter-drawer')
    drawer.locator('.advanced-filter-group-head').first.get_by_role('button').first.click()
    row=drawer.locator('.advanced-filter-condition').first
    choose(page,row.locator('.advanced-filter-value-control .ant-select'),'意向客户')
    page.keyboard.press('Escape')
    drawer.locator('.advanced-filter-group-head').first.get_by_role('button').first.click()
    row2=drawer.locator('.advanced-filter-condition').nth(1)
    choose(page,row2.locator('.ant-select').first,'负责人所属组织（含下级）')
    choose(page,row2.locator('.advanced-filter-value-control .ant-select'),'测试中心 / 测试部门')
    page.keyboard.press('Escape')
    drawer.get_by_role('button',name='应用筛选').click()
    assert page.evaluate('stageFixture.filter.conditions')==[{'fieldKey':'lead.salesStage','operator':'in','value':['intent_customer']},{'fieldKey':'lead.ownerDeptId','operator':'in','value':['11']}]
    page.set_viewport_size({'width':390,'height':844})
    page.get_by_role('button',name=re.compile('新增跟进')).first.click()
    expect(form.get_by_label('跟进后销售阶段')).to_be_visible()
    assert page.evaluate('document.documentElement.scrollWidth<=innerWidth')
    page.screenshot(path=str(OUT/'workbench-mobile.png'),full_page=True)
    page.goto('http://127.0.0.1:5174/test/lead-sales-stage.html?error')
    expect(page.get_by_text('销售阶段字典读取失败',exact=True)).to_be_visible()
    expect(page.locator('.fu-panel-form-wrapper').get_by_role('button',name='提交跟进')).to_be_disabled()
    page.evaluate('stageFixture.dictError=false')
    page.locator('.fu-panel-form-wrapper').get_by_role('button',name=re.compile('重\s*试')).click()
    expect(page.locator('.fu-panel-form-wrapper').get_by_role('button',name='提交跟进')).to_be_enabled()
    page.goto('http://127.0.0.1:5174/test/lead-sales-stage.html?readonly')
    expect(page.locator('.fu-panel-form-wrapper')).to_have_count(0)
    assert not errors,errors
    page.close()
    admin=browser.new_page(viewport={'width':1440,'height':1000})
    admin.goto('http://127.0.0.1:5197/test/lead-sales-stage.html')
    expect(admin.get_by_text('历史阶段名称',exact=True).first).to_be_visible(timeout=90000)
    admin.get_by_role('button',name='阶段测试客资').click()
    expect(admin.get_by_text('历史待触达',exact=False)).to_be_visible()
    admin.screenshot(path=str(OUT/'admin-desktop.png'),full_page=True,animations='disabled')
    admin.set_viewport_size({'width':390,'height':844})
    expect(admin.get_by_text('历史阶段名称',exact=True).last).to_be_visible()
    admin.screenshot(path=str(OUT/'admin-mobile.png'),full_page=True,animations='disabled')
    stage_box=admin.get_by_text('历史阶段名称',exact=True).last.bounding_box()
    assert stage_box and stage_box['x']>=0 and stage_box['x']+stage_box['width']<=390
    browser.close()
print('PASS both frontends, stage snapshots/defaults/legacy empty, advance/regress, retry/idempotency, dictionary error/retry, read-only, combined filter payload, desktop/mobile')
