# -*- coding: utf-8 -*-
from pathlib import Path
from tempfile import gettempdir
from playwright.sync_api import sync_playwright, expect

with sync_playwright() as p:
 browser=p.chromium.launch(channel='chrome',headless=True)
 page=browser.new_page(viewport={'width':1280,'height':900})
 page.on('pageerror',lambda e: print('PAGE ERROR:',str(e)[:500]))
 page.goto('http://127.0.0.1:5174/zsjos/media-students?personId=31')
 print('LIVE URL:',page.url)
 page.goto('http://127.0.0.1:5174/test/media-students-rail.html')
 expect(page.locator('.media-students-item')).to_have_count(20)
 expect(page.get_by_text('学员档案',exact=True)).to_be_visible()
 page.evaluate("window.detailBefore=document.querySelector('.lead-inbox-detail'); window.callsBefore=railFixture.calls")
 page.get_by_role('button',name='收起学员列表',exact=True).click()
 assert page.locator('.media-students-list-pane').bounding_box()['width']==72
 toggle_box=page.get_by_role('button',name='展开学员列表',exact=True).bounding_box()
 search_box=page.get_by_role('button',name='搜索学员',exact=True).bounding_box()
 assert abs(toggle_box['y']-search_box['y'])<2
 assert toggle_box['x']+toggle_box['width']<=search_box['x']
 assert search_box['x']+search_box['width']<=page.locator('.media-students-list-pane').bounding_box()['x']+72
 assert page.evaluate("window.detailBefore===document.querySelector('.lead-inbox-detail') && window.callsBefore===railFixture.calls")
 page.locator('.media-students-item').nth(1).focus()
 expect(page.get_by_role('tooltip').filter(has_text='TEST-2')).to_contain_text('测试学员2')
 page.locator('.media-students-item').nth(1).click()
 expect(page.locator('.media-students-item[aria-current=true]')).to_have_attribute('aria-label','测试学员2 · TEST-2')
 expect(page.get_by_role('button',name='展开学员列表',exact=True)).to_be_visible()
 page.get_by_role('button',name='下一页学员',exact=True).click()
 expect(page.locator('.media-students-item').first).to_have_attribute('aria-label','测试学员21 · TEST-21')
 page.get_by_role('button',name='上一页学员',exact=True).click()
 page.get_by_role('button',name='搜索学员',exact=True).click()
 search=page.get_by_placeholder('搜索姓名或手机号');expect(search).to_be_focused()
 search.fill('测试学员45');search.press('Enter')
 expect(page.locator('.media-students-item')).to_have_count(1)
 page.get_by_role('button',name='收起学员列表',exact=True).click()
 page.get_by_role('button',name='搜索学员',exact=True).click()
 expect(search).to_have_value('测试学员45')
 page.locator('.media-students-search .ant-input-clear-icon').click()
 expect(page.locator('.media-students-item')).to_have_count(20)
 scroll=page.locator('.media-students-scroll');scroll.evaluate('(e)=>e.scrollTop=250')
 previous=scroll.evaluate('(e)=>e.scrollTop')
 page.get_by_role('button',name='收起学员列表',exact=True).click()
 page.get_by_role('button',name='展开学员列表',exact=True).click()
 assert scroll.evaluate('(e)=>e.scrollTop')==previous
 page.get_by_role('button',name='收起学员列表',exact=True).click()
 page.reload();expect(page.get_by_role('button',name='展开学员列表',exact=True)).to_be_visible()
 expect(page.get_by_text('学员档案',exact=True)).to_be_visible()
 page.get_by_role('tab',name='测试账号',exact=True).click()
 expect(page.get_by_role('button',name='维护账号表')).to_be_visible()
 page.get_by_role('button',name='维护账号表').click()
 draft=page.get_by_role('textbox',name='账号昵称',exact=True)
 draft.fill('未保存测试草稿')
 calls=page.evaluate('railFixture.calls')
 # The editor is a modal, so exercise the underlying layout toggle without closing the editor.
 page.get_by_role('button',name='展开学员列表',exact=True).evaluate('(e)=>e.click()')
 expect(draft).to_have_value('未保存测试草稿')
 page.get_by_role('button',name='收起学员列表',exact=True).evaluate('(e)=>e.click()')
 expect(draft).to_have_value('未保存测试草稿')
 expect(page.get_by_role('tab',name='测试账号',exact=True)).to_have_attribute('aria-selected','true')
 assert page.evaluate('railFixture.calls')==calls
 page.reload()
 expect(page.get_by_text('学员档案',exact=True)).to_be_visible()
 page.screenshot(path=str(Path(gettempdir()) / 'media-students-desktop.png'),full_page=True)
 page.set_viewport_size({'width':390,'height':844})
 assert scroll.evaluate('(e)=>getComputedStyle(e).flexDirection')=='row'
 assert scroll.evaluate('(e)=>e.scrollWidth>e.clientWidth')
 assert page.evaluate('document.documentElement.scrollWidth<=window.innerWidth')
 page.screenshot(path=str(Path(gettempdir()) / 'media-students-mobile.png'),full_page=True)
 for mode in ['empty','error','denied']:
  page.evaluate('(m)=>railFixture.mode=m',mode)
  page.get_by_role('button',name='刷新学员',exact=True).click()
  if mode=='empty':expect(page.get_by_role('status')).to_contain_text('暂无')
  else:
   expect(page.get_by_role('button',name='查看学员列表错误')).to_be_visible()
   page.get_by_role('button',name='查看学员列表错误').click()
   expect(page.get_by_role('alert')).to_contain_text('无权查看' if mode=='denied' else '测试列表加载失败')
   page.get_by_role('button',name='收起学员列表',exact=True).click()
 page.evaluate("railFixture.mode='success';railFixture.delay=800")
 page.get_by_role('button',name='重试加载学员').click()
 expect(page.locator('.media-students-scroll .ant-skeleton-avatar')).to_be_visible()
 expect(page.locator('.media-students-item')).to_have_count(20)
 page.get_by_role('button',name='展开学员列表',exact=True).click()
 assert page.evaluate('document.documentElement.scrollWidth<=window.innerWidth')
 page.screenshot(path=str(Path(gettempdir()) / 'media-students-mobile-expanded.png'),full_page=True)
 fallback=browser.new_page(viewport={'width':1280,'height':900})
 fallback.add_init_script("""for (const method of ['getItem','setItem']) { const original=Storage.prototype[method]; Storage.prototype[method]=function(key,...args) { if(key==='zsjos.media-students.list-collapsed') throw new Error('Storage unavailable'); return original.call(this,key,...args); }; }""")
 fallback.goto('http://127.0.0.1:5174/test/media-students-rail.html')
 expect(fallback.get_by_role('button',name='收起学员列表',exact=True)).to_be_visible()
 fallback.get_by_role('button',name='收起学员列表',exact=True).click()
 expect(fallback.get_by_role('button',name='展开学员列表',exact=True)).to_be_visible()
 print('PASS draft/tab preservation and blocked storage fallback')
 print('PASS desktop/mobile, preference, keyboard tooltip, selected student, search/clear, pagination, scroll, DOM identity/no requests, loading/empty/error/denied/retry')
 browser.close()
