# -*- coding: utf-8 -*-
"""Real page component, isolated API adapter; no real business writes."""
import os
from pathlib import Path
from tempfile import gettempdir
from playwright.sync_api import sync_playwright, expect

base = os.environ.get('ZSJOS_UI_TEST_URL', 'http://localhost:5175')
out = Path(gettempdir()) / 'zsjos-service-period'
out.mkdir(exist_ok=True)
with sync_playwright() as p:
    browser = p.chromium.launch(channel='chrome', headless=True)
    page = browser.new_page(viewport={'width': 1440, 'height': 1000})
    errors = []
    page.on('pageerror', lambda error: errors.append(str(error)))
    page.goto(base + '/test/media-service-period.html')
    tabs = page.locator('.media-students-service-period-tabs')
    flag = page.get_by_role('switch', name='是否在服务期')
    expect(tabs.get_by_role('tab', name='服务期', exact=True)).to_have_attribute('aria-selected', 'true')
    expect(flag).to_be_checked()
    assert page.evaluate('servicePeriodFixture.queries[0].inServicePeriod === true')
    expect(page.get_by_role('heading', name='我的学员', exact=True)).to_have_count(0)
    page.screenshot(path=str(out / 'desktop.png'), full_page=True)
    page.locator('.media-students-scroll').evaluate('(node) => { node.scrollTop = node.scrollHeight }')
    expect(page.locator('.media-students-item')).to_have_count(24)
    assert page.evaluate('servicePeriodFixture.queries.some(q => q.pageNo === 2 && q.inServicePeriod === true)')
    flag.click()
    expect(page.locator('.media-students-card-select[aria-current=true]')).to_contain_text('验收学员3')
    tabs.get_by_role('tab', name='非服务期', exact=True).click()
    expect(page.locator('.media-students-item')).to_have_count(2)
    assert page.evaluate('servicePeriodFixture.queries.at(-1).pageNo === 1 && servicePeriodFixture.queries.at(-1).inServicePeriod === false')
    expect(flag).not_to_be_checked()
    tabs.get_by_role('tab', name='全部', exact=True).click()
    expect(page.locator('.media-students-card-select[aria-current=true]')).to_contain_text('验收学员1')
    flag.click()
    expect(flag).to_be_checked()
    expect(page.locator('.media-students-card-select[aria-current=true]')).to_contain_text('验收学员1')
    assert page.evaluate('servicePeriodFixture.writes') == 2
    page.evaluate("servicePeriodFixture.failure='save'")
    flag.click()
    expect(page.get_by_text('服务期保存失败', exact=True)).to_be_visible()
    expect(flag).to_be_checked()
    page.evaluate("servicePeriodFixture.failure=''")
    tabs.get_by_role('tab', name='非服务期', exact=True).click()
    expect(page.locator('.media-students-item')).to_have_count(1)
    search = page.get_by_placeholder('搜索姓名或手机号')
    search.fill('不存在的学员'); search.press('Enter')
    expect(page.locator('.media-students-item')).to_have_count(0)
    expect(flag).to_have_count(0)
    tabs.get_by_role('tab', name='全部', exact=True).click()
    expect(page.locator('.media-students-item')).to_have_count(0)
    search.fill(''); search.press('Enter')
    expect(flag).to_be_visible()
    page.evaluate("servicePeriodFixture.failure='list'")
    page.get_by_role('button', name='刷新学员', exact=True).click()
    expect(page.get_by_role('button', name='重试加载学员', exact=True)).to_be_visible()
    page.evaluate("servicePeriodFixture.failure=''")
    page.get_by_role('button', name='重试加载学员', exact=True).click()
    expect(flag).to_be_visible()
    page.evaluate('servicePeriodFixture.canUpdate=false')
    page.get_by_role('button', name='刷新学员', exact=True).click()
    expect(flag).to_be_disabled()
    page.goto(base + '/test/media-service-period.html?readonly')
    expect(flag).to_be_disabled()
    page.goto(base + '/test/media-service-period.html')
    expect(flag).to_be_enabled()
    page.evaluate('servicePeriodFixture.delay=500')
    flag.click()
    expect(tabs.get_by_role('tab', name='全部', exact=True)).to_have_attribute('aria-disabled', 'true')
    expect(page.locator('.media-students-card-select[aria-current=true]')).to_contain_text('验收学员3')
    page.set_viewport_size({'width': 390, 'height': 844})
    expect(tabs.get_by_role('tab', name='非服务期', exact=True)).to_be_visible()
    page.screenshot(path=str(out / 'mobile.png'), full_page=True)
    assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth')
    assert not errors, errors
    browser.close()
print('PASS: tabs, scope/search, save/restore, selection, failure/retry, permissions, pending save, desktop/mobile; screenshots:', out)
