# -*- coding: utf-8 -*-
"""Verify production React cache components with isolated server-menu fixtures."""
from pathlib import Path
import os
import tempfile
from playwright.sync_api import sync_playwright, expect

base = os.environ.get('WORKBENCH_TEST_URL', 'http://127.0.0.1:5178')
output = Path(tempfile.gettempdir()) / 'zsjos-menu-cache-browser'
output.mkdir(exist_ok=True)

with sync_playwright() as p:
    browser = p.chromium.launch(channel='chrome', headless=True)
    for width in (1440, 390):
        page = browser.new_page(viewport={'width': width, 'height': 900})
        errors = []
        page.on('pageerror', lambda error: errors.append(str(error)))
        page.goto(base + '/test/menu-cache.html')
        route = page.get_by_test_id('active-route')
        expect(route).to_have_text('/home')
        assert page.evaluate('window.menuCacheFixture.mounts["/cached"] || 0') == 0
        page.get_by_role('button', name='打开缓存页 A', exact=True).click()
        cached_input = page.get_by_role('textbox', name='缓存页输入')
        cached_input.fill('保留输入')
        mounts = page.evaluate('window.menuCacheFixture.mounts["/cached"]')
        page.get_by_role('button', name='打开普通页', exact=True).click()
        expect(page.get_by_test_id('query/cached')).to_have_text('?record=A')
        page.get_by_role('textbox', name='普通页输入').fill('应当清空')
        page.get_by_role('button', name='打开首页', exact=True).click()
        page.get_by_role('button', name='打开普通页', exact=True).click()
        expect(page.get_by_role('textbox', name='普通页输入')).to_have_value('')
        page.get_by_role('tab', name='缓存页', exact=True).click()
        expect(route).to_have_text('/cached?record=A')
        expect(cached_input).to_have_value('保留输入')
        assert page.evaluate('window.menuCacheFixture.mounts["/cached"]') == mounts
        page.get_by_role('button', name='打开缓存页 B', exact=True).click()
        expect(page.get_by_test_id('query/cached')).to_have_text('?record=B')
        expect(cached_input).to_have_value('保留输入')
        page.get_by_role('switch', name='缓存页未保存', exact=True).click()
        page.get_by_role('button', name='打开首页', exact=True).click()
        expect(route).to_have_text('/home')
        close_cached = page.locator('.ant-tabs-tab').filter(has=page.get_by_role('tab', name='缓存页', exact=True)).locator('.ant-tabs-tab-remove')
        close_cached.click()
        page.get_by_role('button', name='继续编辑', exact=True).click()
        expect(page.get_by_role('tab', name='缓存页', exact=True)).to_have_count(1)
        close_cached.click()
        page.get_by_role('button', name='确认放弃', exact=True).click()
        expect(page.get_by_test_id('page/cached')).to_have_count(0)
        page.get_by_role('button', name='打开缓存页 A', exact=True).click()
        expect(cached_input).to_have_value('')
        cached_input.fill('关闭开关后清除')
        page.get_by_role('button', name='打开首页', exact=True).click()
        page.get_by_role('switch', name='服务端缓存', exact=True).click()
        expect(page.get_by_test_id('page/cached')).to_have_count(0)
        page.get_by_role('button', name='打开缓存页 A', exact=True).click()
        expect(cached_input).to_have_value('')
        cached_input.fill('未保存编辑')
        page.get_by_role('switch', name='缓存页未保存', exact=True).click()
        page.get_by_role('button', name='打开首页', exact=True).click()
        page.get_by_role('button', name='继续编辑', exact=True).click()
        expect(route).to_have_text('/cached?record=A')
        expect(cached_input).to_have_value('未保存编辑')
        page.get_by_role('tab', name='首页', exact=True).click()
        page.get_by_role('button', name='确认放弃', exact=True).click()
        expect(route).to_have_text('/home')
        expect(page.get_by_test_id('page/cached')).to_have_count(0)
        page.get_by_role('switch', name='服务端缓存', exact=True).click()
        page.get_by_role('button', name='打开缓存页 A', exact=True).click()
        cached_input.fill('单页签不保留')
        page.get_by_role('switch', name='多页签', exact=True).click()
        page.get_by_role('button', name='打开首页', exact=True).click()
        expect(page.get_by_test_id('page/cached')).to_have_count(0)
        page.get_by_role('button', name='打开缓存页 A', exact=True).click()
        expect(cached_input).to_have_value('')
        page.get_by_role('switch', name='多页签', exact=True).click()
        cached_input.fill('权限撤销后清除')
        page.get_by_role('button', name='打开首页', exact=True).click()
        page.get_by_role('switch', name='授权', exact=True).click()
        expect(page.get_by_test_id('page/cached')).to_have_count(0)
        page.get_by_role('button', name='打开缓存页 A', exact=True).click()
        expect(route).to_have_text('/home')
        page.get_by_role('switch', name='授权', exact=True).click()
        page.get_by_role('button', name='打开缓存页 A', exact=True).click()
        expect(cached_input).to_have_value('')
        cached_input.fill('租户隔离')
        page.get_by_role('button', name='打开首页', exact=True).click()
        page.get_by_role('button', name='切换租户身份', exact=True).click()
        page.get_by_role('tab', name='缓存页', exact=True).click()
        expect(cached_input).to_have_value('')
        page.screenshot(path=str(output / f'menu-cache-{width}.png'), full_page=True)
        assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth'), 'horizontal overflow'
        assert not errors, errors
        print(f'PASS width={width}: cache on/off, query isolation, close/leave guards, tabs, authorization, tenant scope')
        page.close()
    browser.close()
print(f'Screenshots: {output}')
