# UTF-8. Local synthetic transport; no production mutations.
from pathlib import Path
from playwright.sync_api import sync_playwright, expect
import re

with sync_playwright() as p:
    browser = p.chromium.launch(channel='chrome', headless=True)
    page = browser.new_page(viewport={'width': 1440, 'height': 1000})
    errors = []
    page.on('pageerror', lambda error: errors.append(str(error)))
    base = 'http://localhost:5174/test/production-ticket-redesign.html'
    page.goto(base)
    expect(page.locator('.production-ticket-count')).to_have_text('共 42 条工单')
    expect(page.locator('.production-ticket-list-item')).to_have_count(20)
    page.get_by_title('下一页').click()
    expect(page.locator('.production-ticket-list-item').first).to_contain_text('PT-DEMO-21')
    page.get_by_placeholder('搜索工单编号').fill('PT-DEMO-1')
    page.get_by_placeholder('搜索工单编号').press('Enter')
    expect(page.locator('.production-ticket-count')).to_have_text('共 11 条工单')
    page.locator('.production-ticket-search > button').click()
    page.get_by_role('button', name=re.compile(r'^清\s*空$')).click()
    expect(page.locator('.production-ticket-list-item')).to_have_count(20)
    page.locator('.production-ticket-list-item').nth(1).click()
    page.locator('.production-ticket-list-item').nth(2).click()
    expect(page.locator('.production-ticket-heading h2')).to_have_text('PT-DEMO-3')
    page.wait_for_timeout(500)
    expect(page.locator('.production-ticket-heading h2')).to_have_text('PT-DEMO-3')
    expect(page.locator('.production-ticket-accounts .media-ticket-account-content')).to_have_count(2)
    for width in [1440, 1024, 390]:
        page.set_viewport_size({'width': width, 'height': 1000})
        assert page.evaluate('document.documentElement.scrollWidth <= innerWidth')
        main = page.locator('.production-ticket-main').bounding_box()
        aside = page.locator('.production-ticket-aside').bounding_box()
        if width == 1440: assert aside['x'] >= main['x'] + main['width']
        if width == 390: assert aside['y'] < main['y']
        page.screenshot(path=f'D:/ZSJ-OS-backups/production-redesign-{width}.png', full_page=True)
    page.get_by_role('button', name='返回列表').click()
    expect(page.locator('.production-ticket-list-pane')).to_be_visible()
    page.set_viewport_size({'width': 1440, 'height': 1000})
    page.get_by_role('tab', name='抢单池', exact=True).click()
    expect(page.locator('.production-ticket-pool-card')).to_have_count(12)
    page.screenshot(path='D:/ZSJ-OS-backups/production-redesign-pool.png', full_page=True)
    page.locator('.production-ticket-pool-card').first.click()
    page.get_by_role('button', name='返回抢单池').click()
    expect(page.locator('.production-ticket-pool-card')).to_have_count(12)
    page.locator('.production-ticket-pool-card').first.click()
    page.get_by_role('button', name=re.compile(r'^抢\s*单$')).click()
    expect(page.get_by_role('tab', name='我的工单', exact=True)).to_have_attribute('aria-selected', 'true')
    page.get_by_role('button', name='开始制作', exact=True).click()
    page.get_by_role('button', name='提交成品', exact=True).click()
    dialog = page.get_by_role('dialog')
    dialog.get_by_label('成品链接').fill('https://example.com/delivery')
    dialog.get_by_label('提交备注（可选）').fill('成品交付测试')
    dialog.get_by_role('button', name=re.compile(r'^确\s*认$')).click()
    expect(page.locator('.media-ticket-detail')).to_contain_text('成品交付测试')
    page.get_by_role('button', name=re.compile(r'^返\s*工$')).click()
    dialog.get_by_label('原因').fill('补充清晰字幕')
    dialog.get_by_role('button', name=re.compile(r'^确\s*认$')).click()
    expect(page.locator('.production-ticket-rework')).to_contain_text('补充清晰字幕')
    page.get_by_role('button', name='重新接单', exact=True).click()
    expect(page.get_by_role('button', name='开始制作', exact=True)).to_be_visible()
    page.goto(base + '?deep')
    expect(page.locator('.production-ticket-heading h2')).to_have_text('PT-DEMO-65')
    page.goto(base + '?denied&deep')
    expect(page.locator('.production-ticket-detail-pane')).to_contain_text('无权查看该工单')
    page.goto(base + '?conflict')
    page.get_by_role('tab', name='抢单池', exact=True).click()
    page.locator('.production-ticket-pool-card').first.click()
    page.get_by_role('button', name=re.compile(r'^抢\s*单$')).click()
    expect(page.locator('.production-ticket-actions')).to_contain_text('已完成')
    assert not errors, errors
    print('PASS: pagination/search/race/multi-account/responsive/pool/claim/submit/rework/deep-link/denied/conflict')
    browser.close()
