# -*- coding: utf-8 -*-
from pathlib import Path
from tempfile import gettempdir
from playwright.sync_api import sync_playwright, expect

with sync_playwright() as p:
 browser=p.chromium.launch(channel='chrome',headless=True)
 page=browser.new_page(viewport={'width':1280,'height':900})
 page.on('pageerror',lambda e: print('PAGE ERROR:',str(e)[:300]))
 page.goto('http://127.0.0.1:5174/test/student-partner-invitation.html')
 page.get_by_role('button',name='开通兼职账号').click()
 modal=page.get_by_role('dialog',name='开通学员兼职账号')
 expect(modal.get_by_text('测试运营甲',exact=True)).to_be_visible()
 modal.get_by_role('combobox',name='归属运营').click()
 page.get_by_title('测试运营乙',exact=True).click()
 modal.get_by_role('textbox',name='注册手机号').fill('13800000000')
 page.wait_for_timeout(350)
 page.screenshot(path=str(Path(gettempdir())/'student-invitation-form.png'))
 modal.get_by_role('button',name='确 定').click()
 result=page.get_by_role('dialog',name='兼职账号邀请码',exact=True)
 expect(result.get_by_text('TEST1234',exact=True)).to_be_visible()
 expect(result.get_by_text('测试运营乙',exact=True)).to_be_visible()
 assert page.evaluate('railFixture.invitation.assignedOperatorUserId')==10
 page.context.grant_permissions(['clipboard-read','clipboard-write'])
 result.get_by_role('button',name='复制邀请码').click()
 assert page.evaluate('navigator.clipboard.readText()')=='TEST1234'
 result.get_by_role('button',name='Close',exact=True).click()
 page.get_by_role('button',name='查看兼职邀请码').click()
 expect(result.get_by_text('TEST1234',exact=True)).to_be_visible()
 assert page.evaluate('railFixture.created')==1
 page.reload()
 page.get_by_role('button',name='查看兼职邀请码').click()
 expect(result.get_by_text('TEST1234',exact=True)).to_be_visible()
 page.wait_for_timeout(350)
 page.screenshot(path=str(Path(gettempdir())/'student-invitation-result.png'))
 page.evaluate("railFixture.opened=true;window.dispatchEvent(new Event('focus'))")
 expect(result).not_to_be_visible()
 expect(page.get_by_text('兼职账号已开通',exact=True)).to_be_visible()
 expect(page.get_by_role('button',name='开通兼职账号')).to_have_count(0)
 expect(page.get_by_role('button',name='查看兼职邀请码')).to_have_count(0)
 page.evaluate("railFixture.opened=false;railFixture.invitation.status='expired';railFixture.operator=undefined;window.dispatchEvent(new Event('focus'))")
 page.get_by_role('button',name='重新生成兼职邀请码').click()
 expect(modal.get_by_text('原邀请码已失效，重新生成后请发送新邀请码。')).to_be_visible()
 expect(modal.get_by_role('combobox',name='归属运营')).to_have_value('')
 modal.get_by_role('textbox',name='注册手机号').fill('13800000000')
 modal.get_by_role('button',name='确 定').click()
 expect(modal.get_by_text('请选择归属运营',exact=True).last).to_be_visible()
 modal.get_by_role('combobox',name='归属运营').click()
 page.get_by_title('测试运营甲',exact=True).click()
 page.evaluate("railFixture.mode='create-error'")
 modal.get_by_role('button',name='确 定').click()
 expect(page.get_by_text('测试生成失败',exact=True)).to_be_visible()
 expect(modal.get_by_role('textbox',name='注册手机号')).to_have_value('13800000000')
 page.evaluate("railFixture.mode='success'")
 modal.get_by_role('button',name='确 定').click()
 expect(result).to_be_visible()
 result.get_by_role('button',name='Close',exact=True).click()
 page.evaluate("railFixture.mode='context-error';window.dispatchEvent(new Event('focus'))")
 expect(page.get_by_text('兼职状态加载失败',exact=True)).to_be_visible()
 expect(page.get_by_role('button',name='开通兼职账号')).to_have_count(0)
 page.evaluate("railFixture.mode='success'")
 page.get_by_role('button',name='重试加载兼职状态').click()
 expect(page.get_by_role('button',name='查看兼职邀请码')).to_be_visible()
 page.evaluate("railFixture.invitation=null;railFixture.mode='operator-error';window.dispatchEvent(new Event('focus'))")
 page.get_by_role('button',name='开通兼职账号').click()
 expect(modal.get_by_text('运营加载失败',exact=True)).to_be_visible()
 page.evaluate("railFixture.mode='success'")
 modal.get_by_role('button',name='重试加载运营').click()
 expect(modal.get_by_role('combobox',name='归属运营')).to_be_enabled()
 page.set_viewport_size({'width':390,'height':844})
 page.wait_for_timeout(350)
 page.screenshot(path=str(Path(gettempdir())/'student-invitation-mobile.png'))
 assert page.evaluate('document.documentElement.scrollWidth<=window.innerWidth')
 modal.get_by_role('button',name='取 消',exact=True).click()
 page.evaluate("railFixture.mode='denied';window.dispatchEvent(new Event('focus'))")
 expect(page.get_by_text('无权查看兼职状态',exact=True)).to_be_visible()
 page.evaluate("railFixture.mode='success';railFixture.conflict=true;railFixture.operator=undefined")
 page.get_by_role('button',name='重试加载兼职状态').click()
 page.get_by_role('button',name='开通兼职账号').click()
 expect(modal.get_by_text('学员运营归属不一致，请明确选择本次兼职的归属运营。')).to_be_visible()
 modal.get_by_role('button',name='取 消',exact=True).click()
 page.evaluate("railFixture.mode='empty-operators'")
 page.get_by_role('button',name='开通兼职账号').click()
 modal.get_by_role('combobox',name='归属运营').click()
 expect(page.get_by_text('暂无可用运营',exact=True)).to_be_visible()
 page.goto('http://127.0.0.1:5174/test/student-partner-invitation.html?no-permission')
 expect(page.get_by_text('学员档案',exact=True)).to_be_visible()
 expect(page.get_by_role('button',name='查看兼职邀请码')).to_have_count(0)
 expect(page.get_by_role('button',name='开通兼职账号')).to_have_count(0)
 print('PASS operator prefill/change, persistence/reopen/reload, bound-state refresh, expired recreation, required operator, create failure retention, status/candidates retry, permission and mobile layout')
 browser.close()
