<template>
  <ContentWrap><div class="toolbar"><el-select v-model="selectedTypeId" clearable placeholder="全部计划类型" @change="loadTemplates"><el-option v-for="item in types" :key="item.id" :label="item.name" :value="item.id" /></el-select><el-button v-hasPermi="['zsjos:work-plan-config:create']" type="primary" @click="typeDialog = true">新增计划类型</el-button><el-button v-hasPermi="['zsjos:work-plan-config:create']" @click="openCreate">新增计划模板</el-button></div></ContentWrap>
  <ContentWrap v-loading="loading"><el-alert v-if="error" :title="error" type="error" show-icon><template #default><el-button link @click="loadAll">重试</el-button></template></el-alert><el-empty v-else-if="!templates.length" description="暂无计划模板" /><el-table v-else :data="templates"><el-table-column prop="name" label="模板名称" min-width="180" /><el-table-column label="计划类型" width="140"><template #default="{ row }">{{ typeName(row.typeId) }}</template></el-table-column><el-table-column label="默认周期" width="110"><template #default="{ row }">{{ periodLabels[row.periodMode || 'custom'] }}</template></el-table-column><el-table-column label="配置内容" min-width="180"><template #default="{ row }">{{ row.fields?.length || 0 }} 个字段 / {{ row.presetItems?.length || 0 }} 个默认任务</template></el-table-column><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag>{{ statusLabels[row.status] }}</el-tag></template></el-table-column><el-table-column label="操作" width="260" fixed="right"><template #default="{ row }"><el-button v-if="row.versionStatus === 'draft'" link type="primary" @click="openEdit(row)">编辑草稿</el-button><el-button v-if="row.versionStatus === 'draft'" link type="primary" @click="publish(row)">发布</el-button><el-button v-if="row.versionStatus === 'published'" link type="primary" @click="copyVersion(row)">复制新版本</el-button><el-button v-if="row.status === 'published'" link type="danger" @click="disable(row)">停用</el-button></template></el-table-column></el-table></ContentWrap>
  <el-dialog v-model="typeDialog" title="新增计划类型" width="500px"><el-form :model="typeForm" label-width="90px"><el-form-item label="类型名称" required><el-input v-model="typeForm.name" /></el-form-item><el-form-item label="说明"><el-input v-model="typeForm.description" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="typeDialog = false">取消</el-button><el-button type="primary" @click="saveType">保存</el-button></template></el-dialog>
  <el-dialog v-model="templateDialog" :title="editingId ? '编辑模板草稿' : '新增计划模板'" width="1080px" top="3vh">
    <el-form :model="templateForm" label-width="100px">
      <el-tabs v-model="activeSection">
        <el-tab-pane label="基本设置" name="basic">
          <div class="form-grid"><el-form-item label="计划类型" required><el-select v-model="templateForm.typeId"><el-option v-for="item in types" :key="item.id" :label="item.name" :value="item.id" /></el-select></el-form-item><el-form-item label="模板名称" required><el-input v-model="templateForm.name" /></el-form-item><el-form-item label="默认周期" required><el-select v-model="templateForm.periodMode"><el-option v-for="(label, value) in periodLabels" :key="value" :label="label" :value="value" /></el-select></el-form-item><el-form-item label="模板说明"><el-input v-model="templateForm.description" type="textarea" /></el-form-item></div>
        </el-tab-pane>
        <el-tab-pane v-for="section in sections" :key="section.key" :label="section.label" :name="section.key">
          <el-alert :title="section.help" type="info" :closable="false" class="mb-12px" /><div v-for="(field, index) in sectionFields(section.key)" :key="fieldKey(field, index)" class="field-card"><div class="field-grid"><el-input v-model="field.label" placeholder="字段名称" /><el-select v-model="field.fieldType"><el-option v-for="(label, value) in fieldTypeLabels" :key="value" :label="label" :value="value" /></el-select><el-input v-model="field.unit" placeholder="单位（可选）" /><el-input v-model="field.placeholder" placeholder="填写提示" /><el-checkbox v-model="field.required">必填</el-checkbox><el-checkbox v-model="field.exportable">导出</el-checkbox><el-checkbox v-if="section.key === 'plan' && field.fieldType !== 'attachment'" v-model="field.filterable">筛选</el-checkbox><el-button text type="danger" @click="removeField(field)">删除</el-button></div><div v-if="['select','multi_select'].includes(field.fieldType)" class="options"><el-tag v-for="(option, optionIndex) in optionList(field)" :key="optionIndex" closable @close="removeOption(field, optionIndex)">{{ option.label }}</el-tag><el-input v-model="optionDraft[fieldKey(field, index)]" placeholder="输入选项后回车" @keyup.enter="addOption(field, index)" /></div></div><el-button type="primary" plain @click="addField(section.key)">新增{{ section.label }}字段</el-button>
        </el-tab-pane>
        <el-tab-pane label="默认任务" name="tasks">
          <div v-for="(task, index) in templateForm.presetItems" :key="index" class="task-row"><el-input v-model="task.title" placeholder="任务名称" /><el-input v-model="task.deliverableRequirement" placeholder="交付要求" /><el-input-number v-model="task.dueOffsetDays" :min="0" /><el-checkbox v-model="task.confirmationRequired">需要确认</el-checkbox><el-button text type="danger" @click="templateForm.presetItems?.splice(index, 1)">删除</el-button></div><el-button type="primary" plain @click="templateForm.presetItems?.push(newTask())">新增默认任务</el-button>
        </el-tab-pane>
        <el-tab-pane label="适用范围" name="scope">
          <el-form-item label="适用部门"><el-select v-model="templateForm.applicableDeptIds" multiple filterable placeholder="不选择表示全公司"><el-option v-for="dept in departments" :key="dept.id" :label="dept.name" :value="dept.id" /></el-select></el-form-item><el-form-item label="包含下级"><el-switch v-model="templateForm.includeChildDepartments" /></el-form-item>
        </el-tab-pane>
        <el-tab-pane label="预览" name="preview">
          <el-card v-for="section in sections" :key="section.key" shadow="never" class="mb-12px"><template #header>{{ section.label }}</template><el-empty v-if="!sectionFields(section.key).length" description="未配置字段" :image-size="48" /><el-descriptions v-else :column="2" border><el-descriptions-item v-for="field in sectionFields(section.key)" :key="field.fieldKey || field.label" :label="field.label || '未命名字段'">{{ field.placeholder || fieldTypeLabels[field.fieldType] }}</el-descriptions-item></el-descriptions></el-card>
        </el-tab-pane>
      </el-tabs>
    </el-form><template #footer><el-button @click="templateDialog = false">取消</el-button><el-button type="primary" :loading="saving" @click="saveTemplate">保存草稿</el-button></template>
  </el-dialog>
</template>

<script lang="ts" setup>
import { cloneDeep } from 'lodash-es'
import * as DeptApi from '@/api/system/dept'
import * as ConfigApi from '@/api/zsjos/workPlanConfig'
defineOptions({ name: 'ZsjosWorkPlanConfig' })
const message = useMessage(); const types = ref<ConfigApi.WorkPlanTypeVO[]>([]); const templates = ref<ConfigApi.WorkPlanTemplateVO[]>([]); const departments = ref<DeptApi.DeptVO[]>([]); const selectedTypeId = ref<number>(); const loading = ref(false); const saving = ref(false); const error = ref(''); const typeDialog = ref(false); const templateDialog = ref(false); const editingId = ref<number>(); const activeSection = ref('basic'); const optionDraft = reactive<Record<string, string>>({}); const typeForm = reactive<ConfigApi.WorkPlanTypeSaveReqVO>({ name: '', description: '' })
const sections = [{ key: 'plan', label: '计划目标', help: '整张计划的目标、预算和指标。只有这里的标准字段可以用于监管筛选。' }, { key: 'task', label: '任务要求', help: '所有工作任务共用的要求字段。' }, { key: 'report', label: '完成汇报', help: '责任人提交完成汇报时填写。' }, { key: 'summary', label: '计划总结', help: '全部任务结束后，由计划负责人统一填写。' }] as const
const emptyTemplate = (): ConfigApi.WorkPlanTemplateSaveReqVO => ({ typeId: undefined as unknown as number, name: '', description: '', periodMode: 'month', fields: [], applicableDeptIds: [], includeChildDepartments: true, presetItems: [] }); const templateForm = reactive<ConfigApi.WorkPlanTemplateSaveReqVO>(emptyTemplate()); const periodLabels: Record<string, string> = { day: '日', week: '周', month: '月', quarter: '季度', year: '年度', custom: '自定义' }; const statusLabels: Record<string, string> = { draft: '草稿', published: '已发布', disabled: '已停用' }; const fieldTypeLabels: Record<string, string> = { text: '单行文本', multi_text: '多行文本', integer: '整数', decimal: '小数', money: '金额', date: '日期', datetime: '日期时间', select: '单选', multi_select: '多选', user: '用户', department: '部门', dict: 'System 字典', attachment: '附件', link: '链接' }
const typeName = (id: number) => types.value.find((item) => item.id === id)?.name || '-'; const sectionFields = (section: string) => templateForm.fields.filter((field) => field.section === section); const fieldKey = (field: ConfigApi.WorkPlanTemplateFieldVO, index: number) => field.fieldKey || `${field.section}-${index}`; const newField = (section: ConfigApi.WorkPlanTemplateFieldVO['section']): ConfigApi.WorkPlanTemplateFieldVO => ({ label: '', section, fieldType: 'text', required: false, filterable: false, exportable: true }); const newTask = (): ConfigApi.WorkPlanTemplateTaskVO => ({ title: '', confirmationRequired: false }); const addField = (section: ConfigApi.WorkPlanTemplateFieldVO['section']) => templateForm.fields.push(newField(section)); const removeField = (field: ConfigApi.WorkPlanTemplateFieldVO) => templateForm.fields.splice(templateForm.fields.indexOf(field), 1)
const optionList = (field: ConfigApi.WorkPlanTemplateFieldVO): Array<{ label: string; value: string }> => { try { return JSON.parse(field.optionsJson || '[]') } catch { return [] } }; const writeOptions = (field: ConfigApi.WorkPlanTemplateFieldVO, options: Array<{ label: string; value: string }>) => { field.optionsJson = JSON.stringify(options) }; const addOption = (field: ConfigApi.WorkPlanTemplateFieldVO, index: number) => { const key = fieldKey(field, index); const label = optionDraft[key]?.trim(); if (!label) return; writeOptions(field, [...optionList(field), { label, value: label }]); optionDraft[key] = '' }; const removeOption = (field: ConfigApi.WorkPlanTemplateFieldVO, index: number) => { const options = optionList(field); options.splice(index, 1); writeOptions(field, options) }
const loadTemplates = async () => { templates.value = await ConfigApi.getTemplates(selectedTypeId.value) }; const loadAll = async () => { loading.value = true; error.value = ''; try { const [typeList, deptList] = await Promise.all([ConfigApi.getTypes(), DeptApi.getSimpleDeptList()]); types.value = typeList; departments.value = deptList; await loadTemplates() } catch (e: any) { error.value = e?.msg || e?.message || '计划配置加载失败' } finally { loading.value = false } }; const openCreate = () => { editingId.value = undefined; activeSection.value = 'basic'; Object.assign(templateForm, emptyTemplate()); templateDialog.value = true }; const openEdit = (row: ConfigApi.WorkPlanTemplateVO) => { editingId.value = row.id; activeSection.value = 'basic'; Object.assign(templateForm, { typeId: row.typeId, name: row.name, description: row.description, periodMode: row.periodMode || 'month', fields: cloneDeep(row.fields || []), applicableDeptIds: [...(row.applicableDeptIds || [])], includeChildDepartments: row.includeChildDepartments, presetItems: cloneDeep(row.presetItems || []) }); templateDialog.value = true }
const saveType = async () => { if (!typeForm.name.trim()) return message.warning('请输入类型名称'); await ConfigApi.createType(typeForm); typeDialog.value = false; Object.assign(typeForm, { name: '', description: '' }); await loadAll() }; const saveTemplate = async () => { if (!templateForm.name.trim() || !templateForm.typeId) return message.warning('请填写模板名称并选择计划类型'); saving.value = true; try { editingId.value ? await ConfigApi.updateTemplate(editingId.value, templateForm) : await ConfigApi.createTemplate(templateForm); message.success('模板草稿已保存'); templateDialog.value = false; await loadTemplates() } finally { saving.value = false } }; const copyVersion = async (row: ConfigApi.WorkPlanTemplateVO) => { await ConfigApi.copyTemplateVersion(row.id); message.success('已生成新草稿版本'); await loadTemplates() }; const publish = async (row: ConfigApi.WorkPlanTemplateVO) => { await ConfigApi.publishTemplate(row.id); message.success('模板已发布'); await loadTemplates() }; const disable = async (row: ConfigApi.WorkPlanTemplateVO) => { await ConfigApi.disableTemplate(row.id); message.success('模板已停用'); await loadTemplates() }
onMounted(loadAll)
</script>
<style scoped>.toolbar{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 16px}.field-card{padding:12px 0;border-bottom:1px solid var(--el-border-color-lighter)}.field-grid{display:grid;grid-template-columns:1.2fr 140px 100px 1.2fr auto auto auto auto;gap:8px;align-items:center}.options{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:10px}.options .el-input{width:220px}.task-row{display:grid;grid-template-columns:1.2fr 1.5fr 130px auto auto;gap:8px;margin-bottom:10px;align-items:center}@media(width <= 900px){.form-grid,.field-grid,.task-row{grid-template-columns:1fr}}</style>
