package cn.iocoder.yudao.module.zsjos.dal.mysql.performance;
import org.apache.ibatis.annotations.*;
import java.util.*;
@Mapper public interface PerformanceFactMapper {
 @Select("""
<script>SELECT o.id,o.order_no number,o.lead_id,o.formal_sales_user_id user_id,a.user_name,o.submitted_at occurred_at,o.total_amount amount,o.order_type,COALESCE(a.received_at,(SELECT MAX(h.occurred_at) FROM zsjos_lead_assignment_history h WHERE h.tenant_id=o.tenant_id AND h.deleted=0 AND h.lead_id=o.lead_id AND h.to_owner_user_id=o.formal_sales_user_id AND h.action_type IN ('accept','claim','transfer') AND h.occurred_at &lt;= o.submitted_at)) received_at,a.assignment_id,a.source_group group_key,a.channel_label label,a.channel_code,a.dept_id,a.center_id FROM zsjos_order o LEFT JOIN zsjos_performance_attribution a ON a.fact_type='ORDER' AND a.fact_id=o.id AND a.tenant_id=o.tenant_id AND a.deleted=0 WHERE o.tenant_id=#{tenant} AND o.deleted=0 AND o.status='effective' <choose><when test="type == 'SELF' or type == 'USER'">AND o.formal_sales_user_id=#{id}</when><when test="type == 'DEPT'">AND a.dept_id=#{id}</when><otherwise>AND a.center_id=#{id}</otherwise></choose> ORDER BY o.submitted_at DESC</script>
 """)
 List<PerformanceFact> orders(@Param("tenant") Long tenant,@Param("type") String type,@Param("id") Long id);
 @Select("""
<script>SELECT h.id,h.lead_id,l.lead_no number,h.to_owner_user_id user_id,a.user_name,h.occurred_at,COALESCE(a.received_at,h.occurred_at) received_at,h.id assignment_id,a.dept_id,a.center_id,l.status,l.lead_category_label_snapshot category,l.sales_stage_label_snapshot stage FROM zsjos_lead_assignment_history h JOIN zsjos_lead l ON l.id=h.lead_id AND l.tenant_id=h.tenant_id AND l.deleted=0 LEFT JOIN zsjos_performance_attribution a ON a.fact_type='ASSIGNMENT' AND a.fact_id=h.id AND a.tenant_id=h.tenant_id AND a.deleted=0 WHERE h.tenant_id=#{tenant} AND h.deleted=0 AND h.action_type IN ('accept','claim','transfer') AND h.to_owner_user_id IS NOT NULL <choose><when test="type == 'SELF' or type == 'USER'">AND h.to_owner_user_id=#{id}</when><when test="type == 'DEPT'">AND a.dept_id=#{id}</when><otherwise>AND a.center_id=#{id}</otherwise></choose> ORDER BY h.occurred_at DESC</script>
 """)
 List<PerformanceFact> receipts(@Param("tenant") Long tenant,@Param("type") String type,@Param("id") Long id);
 @Select("""
<script>SELECT t.id,a.dept_id,a.center_id,l.lead_no number,t.biz_id lead_id,t.assignee_id user_id,t.create_time occurred_at,t.due_at,COALESCE(a.completed_at,t.completed_at) completed_at,a.outcome,t.cancelled_at ended_at,a.assignment_id,(a.assignment_id=l.current_assignment_history_id) current_assignment,(t.assignee_id=l.owner_user_id AND t.idempotency_key=CONCAT('lead-qualification:',l.id,':',l.qualification_round_no)) current_qualification,t.status,t.task_type group_key,t.cancel_reason label FROM zsjos_business_task t LEFT JOIN zsjos_performance_attribution a ON a.fact_type IN ('QUALIFICATION','TASK') AND a.fact_id=t.id AND a.tenant_id=t.tenant_id AND a.deleted=0 LEFT JOIN zsjos_lead l ON l.id=t.biz_id AND l.tenant_id=t.tenant_id AND l.deleted=0 WHERE t.tenant_id=#{tenant} AND t.deleted=0 AND t.task_type IN ('lead_assignment_accept','lead_qualification','lead_first_follow_up','lead_follow_up_reminder') <choose><when test="type == 'SELF' or type == 'USER'"> AND t.assignee_id=#{id}</when><when test="type == 'DEPT'"> AND a.dept_id=#{id}</when><otherwise> AND a.center_id=#{id}</otherwise></choose> ORDER BY t.id DESC</script>
 """)
 List<PerformanceFact> tasks(@Param("tenant") Long tenant,@Param("type") String type,@Param("id") Long id);
 @Select("""
<script>SELECT i.id,a.dept_id,a.center_id,o.order_no number,o.submitted_at occurred_at,i.payable_amount amount,i.order_id lead_id,i.product_ref group_key,JSON_UNQUOTE(JSON_EXTRACT(i.product_snapshot,'$.name')) label FROM zsjos_order_item i JOIN zsjos_order o ON o.id=i.order_id AND o.tenant_id=i.tenant_id AND o.deleted=0 LEFT JOIN zsjos_performance_attribution a ON a.fact_type='ORDER' AND a.fact_id=o.id AND a.tenant_id=o.tenant_id AND a.deleted=0 WHERE i.tenant_id=#{tenant} AND i.deleted=0 AND o.status='effective' <choose><when test="type == 'SELF' or type == 'USER'">AND o.formal_sales_user_id=#{id}</when><when test="type == 'DEPT'">AND a.dept_id=#{id}</when><otherwise>AND a.center_id=#{id}</otherwise></choose></script>
 """)
 List<PerformanceFact> products(@Param("tenant") Long tenant,@Param("type") String type,@Param("id") Long id);

 @Select("""
<script>SELECT h.id,a.dept_id,a.center_id,h.lead_id,l.lead_no number,h.candidate_user_id user_id,h.occurred_at,h.action_type group_key FROM zsjos_lead_assignment_history h LEFT JOIN zsjos_performance_attribution a ON a.fact_type='DISPATCH' AND a.fact_id=h.id AND a.tenant_id=h.tenant_id AND a.deleted=0 LEFT JOIN zsjos_lead l ON l.id=h.lead_id AND l.tenant_id=h.tenant_id AND l.deleted=0 WHERE h.tenant_id=#{tenant} AND h.deleted=0 AND h.action_type IN ('dispatch','timeout') <choose><when test="type == 'SELF' or type == 'USER'"> AND h.candidate_user_id=#{id}</when><when test="type == 'DEPT'"> AND a.dept_id=#{id}</when><otherwise> AND a.center_id=#{id}</otherwise></choose></script>
 """)
 List<PerformanceFact> assignments(@Param("tenant") Long tenant,@Param("type") String type,@Param("id") Long id);
 @Select("""
<script>SELECT f.id,a.dept_id,a.center_id,f.lead_id,l.lead_no number,f.operator_user_id user_id,f.occurred_at,f.result_label_snapshot label FROM zsjos_lead_follow_up_record f LEFT JOIN zsjos_performance_attribution a ON a.fact_type='FOLLOW_UP' AND a.fact_id=f.id AND a.tenant_id=f.tenant_id AND a.deleted=0 LEFT JOIN zsjos_lead l ON l.id=f.lead_id AND l.tenant_id=f.tenant_id AND l.deleted=0 WHERE f.tenant_id=#{tenant} AND f.deleted=0 <choose><when test="type == 'SELF' or type == 'USER'"> AND f.operator_user_id=#{id}</when><when test="type == 'DEPT'"> AND a.dept_id=#{id}</when><otherwise> AND a.center_id=#{id}</otherwise></choose> UNION ALL SELECT f.id,a.dept_id,a.center_id,f.lead_id,l.lead_no number,f.operator_user_id user_id,f.occurred_at,f.result_label_snapshot label FROM zsjos_opportunity_follow_up_record f LEFT JOIN zsjos_performance_attribution a ON a.fact_type='OPPORTUNITY_FU' AND a.fact_id=f.id AND a.tenant_id=f.tenant_id AND a.deleted=0 LEFT JOIN zsjos_lead l ON l.id=f.lead_id AND l.tenant_id=f.tenant_id AND l.deleted=0 WHERE f.tenant_id=#{tenant} AND f.deleted=0 <choose><when test="type == 'SELF' or type == 'USER'"> AND f.operator_user_id=#{id}</when><when test="type == 'DEPT'"> AND a.dept_id=#{id}</when><otherwise> AND a.center_id=#{id}</otherwise></choose></script>
 """)
 List<PerformanceFact> followUps(@Param("tenant") Long tenant,@Param("type") String type,@Param("id") Long id);
 @Select("""
<script>SELECT MIN(a.create_time) FROM zsjos_performance_attribution a WHERE a.tenant_id=#{tenant} AND a.deleted=0 <choose><when test="type == 'SELF' or type == 'USER'">AND a.user_id=#{id}</when><when test="type == 'DEPT'">AND a.dept_id=#{id}</when><otherwise>AND a.center_id=#{id}</otherwise></choose></script>
 """)
 java.time.LocalDateTime availableSince(@Param("tenant") Long tenant,@Param("type") String type,@Param("id") Long id);
}
