import { CalendarOutlined, DeleteOutlined, EditOutlined, PlusOutlined, ReloadOutlined } from '@ant-design/icons'
import { Alert, Button, Calendar, DatePicker, Empty, Form, Input, Modal, Popconfirm, Select, Space, Spin, Typography } from 'antd'
import dayjs, { type Dayjs } from 'dayjs'
import { useCallback, useEffect, useState } from 'react'
import { DICT_TYPE } from '../constants'
import { api, type CourseCalendarEvent, type DictData } from '../services/api'

export default function CourseCalendarPage({ permissions }: { permissions: string[] }) {
  const canManage = permissions.includes('zsjos:course-calendar:manage')
  const [anchor, setAnchor] = useState(dayjs()), [rows, setRows] = useState<CourseCalendarEvent[]>([]), [dict, setDict] = useState<DictData[]>([])
  const [loading, setLoading] = useState(false), [error, setError] = useState(''), [editing, setEditing] = useState<CourseCalendarEvent>(), [open, setOpen] = useState(false), [saving, setSaving] = useState(false)
  const [form] = Form.useForm()
  const load = useCallback(async () => { setLoading(true); setError(''); try { setRows(await api.courseCalendar.page({ rangeStart: anchor.startOf('month').startOf('week').format('YYYY-MM-DDTHH:mm:ss'), rangeEnd: anchor.endOf('month').endOf('week').format('YYYY-MM-DDTHH:mm:ss') })) } catch (e) { setError(e instanceof Error ? e.message : '课程日历加载失败') } finally { setLoading(false) } }, [anchor])
  useEffect(() => { void load(); void api.dictDataByType(DICT_TYPE.COURSE_FORM).then(setDict).catch(() => setDict([])) }, [load])
  const openEditor = (row?: CourseCalendarEvent, date?: Dayjs) => { setEditing(row); form.setFieldsValue(row ? { ...row, range: [dayjs(row.startTime), dayjs(row.endTime)] } : { range: [date?.hour(9).minute(0), date?.hour(10).minute(0)] }); setOpen(true) }
  const save = async () => { const values = await form.validateFields(); const data = { courseName: values.courseName, courseFormValue: values.courseFormValue, startTime: values.range[0].format('YYYY-MM-DDTHH:mm:ss'), endTime: values.range[1].format('YYYY-MM-DDTHH:mm:ss'), remark: values.remark, attachmentIds: [] }; setSaving(true); try { editing ? await api.courseCalendar.update(editing.id, data) : await api.courseCalendar.create(data); setOpen(false); await load() } finally { setSaving(false) } }
  const remove = async (id: number) => { await api.courseCalendar.delete(id); await load() }
  return <section className="workspace-page"><div className="page-heading"><div><Typography.Title level={4}><CalendarOutlined /> 课程日历</Typography.Title><Typography.Text type="secondary">租户内统一课程安排</Typography.Text></div><Space><Button icon={<ReloadOutlined />} aria-label="刷新" onClick={() => void load()} />{canManage && <Button type="primary" icon={<PlusOutlined />} onClick={() => openEditor(undefined, anchor)}>新增课程</Button>}</Space></div>{error ? <Alert type="error" showIcon message={error} action={<Button onClick={() => void load()}>重试</Button>} /> : <Spin spinning={loading}><Calendar value={anchor} onChange={setAnchor} onSelect={(date) => canManage && openEditor(undefined, date)} cellRender={(date, info) => info.type !== 'date' ? info.originNode : <div>{date.date()} {rows.filter(r => dayjs(r.startTime).isSame(date, 'day')).slice(0, 3).map(r => <div key={r.id}><Button type="link" size="small" onClick={e => { e.stopPropagation(); openEditor(r) }}>{r.courseName}</Button>{canManage && <><Button type="text" size="small" icon={<EditOutlined />} aria-label="编辑课程" onClick={e => { e.stopPropagation(); openEditor(r) }} /><Popconfirm title="删除课程安排？" onConfirm={() => void remove(r.id)}><Button type="text" danger size="small" icon={<DeleteOutlined />} aria-label="删除课程" onClick={e => e.stopPropagation()} /></Popconfirm></>}</div>)}</div>} /></Spin>}<Modal title={editing ? '编辑课程安排' : '新增课程安排'} open={open} confirmLoading={saving} onCancel={() => setOpen(false)} onOk={() => void save()} destroyOnHidden><Form form={form} layout="vertical"><Form.Item name="courseName" label="课程名称" rules={[{ required: true }]}><Input maxLength={200} /></Form.Item><Form.Item name="courseFormValue" label="课程形式" rules={[{ required: true }]}><Select options={dict.map(v => ({ value: v.value, label: v.label }))} /></Form.Item><Form.Item name="range" label="课程时间" rules={[{ required: true }]}><DatePicker.RangePicker showTime format="YYYY-MM-DD HH:mm" /></Form.Item><Form.Item name="remark" label="备注"><Input.TextArea rows={4} maxLength={2000} /></Form.Item><Form.Item label="附件"><Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="附件上传接口接入后可用" /></Form.Item></Form></Modal></section>
}
