import { App, Alert, Button, Card, Checkbox, Empty, Form, Input, InputNumber, Space, Spin, Tabs, Tag, Typography } from 'antd'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { api, type DictData, type DirectorConfig, type DirectorTemplate, type StudentContactFormField } from '../services/api'

const enumTypes = new Set(['select', 'multi_select', 'radio', 'checkbox_group'])

export function DirectorTemplateConfigPage({ positioning = false }: { positioning?: boolean }) {
  const { message } = App.useApp(); const [loading,setLoading]=useState(true),[error,setError]=useState(''),[templates,setTemplates]=useState<DirectorTemplate[]>([]),[selected,setSelected]=useState<number>(),[fields,setFields]=useState<StudentContactFormField[]>([]),[active,setActive]=useState(0),[dicts,setDicts]=useState<Record<string,DictData[]>>({})
  const current=useMemo(()=>templates.find(x=>x.id===selected),[templates,selected]), field=fields[active]
  const load=useCallback(async()=>{setLoading(true);setError('');try{const rows=await api.directorConfig.templates(positioning);setTemplates(rows);setSelected(value=>rows.some(x=>x.id===value)?value:rows[0]?.id)}catch(e){setError(e instanceof Error?e.message:'加载失败')}finally{setLoading(false)}},[positioning])
  useEffect(()=>{void load()},[load]); useEffect(()=>{const version=current?.draft||current?.published;setFields((version?.fields||[]).map(x=>({...x})));setActive(0)},[current])
  useEffect(()=>{if(!field?.dictType||dicts[field.dictType])return;api.dictDataByType(field.dictType).then(rows=>setDicts(x=>({...x,[field.dictType!]:rows}))).catch(()=>setError('字典加载失败，请重试'))},[field?.dictType,dicts])
  const update=(patch:Partial<StudentContactFormField>)=>setFields(rows=>rows.map((x,i)=>i===active?{...x,...patch}:x)); const move=(index:number,delta:number)=>{const rows=[...fields];[rows[index],rows[index+delta]]=[rows[index+delta],rows[index]];setFields(rows.map((x,i)=>({...x,sort:(i+1)*10})));setActive(index+delta)}
  const copy=async()=>{if(!current)return;await api.directorConfig.copyDraft(positioning,current.id,current.version);await load()}; const save=async()=>{if(!current?.draft)return message.warning('请先复制为草稿');if(fields.some(x=>enumTypes.has(x.type)&&!x.dictType))return message.error('枚举字段必须关联系统字典');await api.directorConfig.saveDraft(positioning,current.id,{versionId:current.draft.id,version:current.draft.version,name:current.name,defaultTemplate:current.defaultTemplate,fields});message.success('草稿已保存');await load()}; const publish=async()=>{if(!current?.draft)return;await api.directorConfig.publish(positioning,current.id,{versionId:current.draft.id,version:current.draft.version});message.success('已发布');await load()}
  if(loading)return <Spin/>; if(error&&!templates.length)return <Alert type="error" message={error} action={<Button onClick={()=>void load()}>重试</Button>}/>; if(!templates.length)return <Empty description="暂无模板"/>
  return <div className="page-stack"><Typography.Title level={3}>{positioning?'定位卡模板配置':'采访表单配置'}</Typography.Title>{error&&<Alert type="warning" message={error}/>}<Tabs activeKey={String(selected)} onChange={v=>setSelected(Number(v))} items={templates.map(x=>({key:String(x.id),label:x.name}))}/><div style={{display:'grid',gridTemplateColumns:'minmax(260px,1fr) minmax(320px,1fr)',gap:16}}><Card size="small" title="字段列表">{fields.map((x,i)=><button key={x.key} onClick={()=>setActive(i)} style={{display:'flex',width:'100%',border:0,borderBottom:'1px solid #eee',background:i===active?'#f0f7ff':'transparent',padding:12,justifyContent:'space-between',textAlign:'left'}}><span><b>{x.title}</b><small style={{display:'block'}}>{x.key} · {x.type}</small></span><Space><Button size="small" disabled={!i} onClick={e=>{e.stopPropagation();move(i,-1)}}>上移</Button><Button size="small" disabled={i===fields.length-1} onClick={e=>{e.stopPropagation();move(i,1)}}>下移</Button></Space></button>)}</Card>{field&&<Card size="small" title={<Space>字段属性{field.systemField&&<Tag>系统字段</Tag>}</Space>}><Form layout="vertical"><Form.Item label="标题"><Input value={field.title} onChange={e=>update({title:e.target.value})}/></Form.Item><Form.Item label="填写备注"><Input.TextArea value={field.description} maxLength={500} showCount onChange={e=>update({description:e.target.value})}/></Form.Item>{enumTypes.has(field.type)&&<Form.Item label="系统字典" required><Input value={field.dictType} disabled/><div>当前启用项 {(dicts[field.dictType||'']||[]).length} 个</div></Form.Item>}<Space><Checkbox checked={field.enabled} onChange={e=>update({enabled:e.target.checked})}>启用</Checkbox><Checkbox checked={field.required} onChange={e=>update({required:e.target.checked})}>必填</Checkbox></Space></Form></Card>}</div><Space><Button onClick={()=>void copy()}>复制为草稿</Button><Button type="primary" onClick={()=>void save()}>保存草稿</Button><Button type="primary" onClick={()=>void publish()}>发布</Button></Space></div>
}

export function DirectorSlaConfigPage(){const{message}=App.useApp();const[form]=Form.useForm<DirectorConfig>();const[loading,setLoading]=useState(true),[error,setError]=useState('');const load=useCallback(async()=>{setLoading(true);setError('');try{form.setFieldsValue(await api.directorConfig.get())}catch(e){setError(e instanceof Error?e.message:'加载失败')}finally{setLoading(false)}},[form]);useEffect(()=>{void load()},[load]);const save=async()=>{const values=await form.validateFields();await api.directorConfig.update(values);message.success('已保存');await load()};return <Card title="编导时效配置" loading={loading}>{error&&<Alert type="error" message={error} action={<Button onClick={()=>void load()}>重试</Button>}/>}<Form form={form} layout="vertical" style={{maxWidth:520}}><Form.Item name="interviewAppointmentHours" label="采访预约默认时限（小时）" rules={[{required:true}]}><InputNumber min={1} max={720}/></Form.Item><Form.Item name="positioningDueHours" label="定位任务默认时限（小时）" rules={[{required:true}]}><InputNumber min={1} max={720}/></Form.Item><Form.Item name="trialDays" label="试运行默认周期（天）" rules={[{required:true}]}><InputNumber min={1} max={365}/></Form.Item><Form.Item name="version" hidden><Input/></Form.Item><Button type="primary" onClick={()=>void save()}>保存</Button></Form></Card>}
