import { useCallback, useEffect, useState } from 'react'
import { Alert, Avatar, Button, Drawer, Empty, Form, Image, Input, List, Modal, Skeleton, Space, Spin, Tabs, Tag, Typography, message } from 'antd'
import { ReloadOutlined } from '@ant-design/icons'
import { api, type LeadAppeal, type LeadAppealEvidence } from '../services/api'
import { formatTimestamp } from '../services/time'
import LeadAppealEvidenceUpload from '../components/LeadAppealEvidenceUpload'
import { uploadDeferredFiles, type DeferredUploadItem } from '../services/deferredUpload'
import { useSubmissionGuard } from '../services/submissionGuard'
import { invalidReasonSnapshotLabel } from '../services/leadManagement'
import IrreversiblePopconfirm from '../components/IrreversiblePopconfirm'

const statusLabel: Record<string, string> = { sales_manager_reviewing: '销售主管复核中', quality_reviewing: '质控复核中', chairman_reviewing: '董事长终审中', overturned: '已改判有效', upheld: '维持无效', withdrawn: '已撤回' }
const stageLabel: Record<string, string> = { sales_manager: '销售主管', quality: '质控部门', chairman: '董事长' }

function Detail({ item, onDecision }: { item: LeadAppeal; onDecision: (type: 'overturn' | 'uphold') => void }) {
  const evidence = (items: LeadAppealEvidence[]) => items.length ? <Image.PreviewGroup><div className="appeal-evidence-grid">{items.map(file => <Image key={file.infraFileId} src={file.fileUrl} alt={file.originalName}/>)}</div></Image.PreviewGroup> : null
  return <article className="message-inbox-detail">
    <div className="message-detail-hero"><Avatar>{item.leadName.slice(0, 1)}</Avatar><div className="message-detail-heading"><Typography.Title level={4}>客资 #{item.leadId} · {item.leadName}</Typography.Title><Space wrap><Tag>第 {item.roundNo} 次申诉</Tag><Tag color="processing">{stageLabel[item.reviewStage]}</Tag><Tag color={item.status === 'upheld' ? 'error' : 'processing'}>{statusLabel[item.status]}</Tag></Space></div></div>
    <div className="message-detail-section"><Typography.Text type="secondary">申诉理由</Typography.Text><Typography.Paragraph>{item.reason}</Typography.Paragraph>{evidence(item.evidence)}</div>
    <div className="message-detail-section"><Typography.Text type="secondary">原无效结论</Typography.Text><Typography.Paragraph>{[invalidReasonSnapshotLabel(item.invalidReasonSnapshot), item.invalidDescriptionSnapshot].filter(Boolean).join('：') || '-'}</Typography.Paragraph>{evidence(item.invalidEvidenceSnapshot)}</div>
    {item.decisionReason && <div className="message-detail-section"><Typography.Text type="secondary">裁决意见</Typography.Text><Typography.Paragraph>{item.decisionReason}</Typography.Paragraph>{evidence(item.decisionEvidence)}</div>}
    <dl className="message-detail-meta"><div><dt>提交时间</dt><dd>{formatTimestamp(item.submittedAt)}</dd></div><div><dt>处理人</dt><dd>{item.reviewerUserName || '-'}</dd></div><div><dt>处理时间</dt><dd>{formatTimestamp(item.decidedAt)}</dd></div></dl>
    {item.taskId && item.status.endsWith('reviewing') && <Space className="appeal-decision-actions"><Button type="primary" onClick={() => onDecision('overturn')}>改判有效</Button><Button danger onClick={() => onDecision('uphold')}>维持无效</Button></Space>}
  </article>
}

export default function LeadAppealPage() {
  const [handled, setHandled] = useState(false); const [items, setItems] = useState<LeadAppeal[]>([]); const [selected, setSelected] = useState<LeadAppeal>(); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [decision, setDecisionState] = useState<'overturn' | 'uphold'>(); const [reason, setReason] = useState(''); const [evidence, setEvidence] = useState<DeferredUploadItem<LeadAppealEvidence>[]>([]); const [drawerOpen, setDrawerOpen] = useState(false)
  const { submitting: saving, run: runDecision, resetIntent } = useSubmissionGuard()
  const [confirmOpen, setConfirmOpen] = useState(false)
  const load = useCallback(async () => { setLoading(true); setError(''); try { const result = await api.leadAppealInboxPage(handled, { pageNo: 1, pageSize: 50 }); setItems(result.list); setSelected(current => result.list.find(item => item.id === current?.id) || result.list[0]) } catch (e) { setError(e instanceof Error ? e.message : '申诉处理列表加载失败') } finally { setLoading(false) } }, [handled])
  useEffect(() => { void load() }, [load])
  const setDecision = (next: 'overturn' | 'uphold' | undefined) => { setConfirmOpen(false); if (next) resetIntent(); setDecisionState(next) }
  const submitDecision = async () => { setConfirmOpen(false); if (!selected?.taskId || !decision) return; const appeal = selected; const nextDecision = decision; await runDecision(async ({ idempotencyKey, complete }) => { const uploadResult = await uploadDeferredFiles(evidence, api.uploadLeadAppealImage, setEvidence); if (uploadResult.failed) { message.error('有裁决图片上传失败，请重试失败项'); return } await api.decideLeadAppeal(appeal.id, nextDecision, { taskId: appeal.taskId!, reason: reason.trim(), attachments: uploadResult.items.filter(item => item.uploaded).map(item => ({ infraFileId: item.uploaded!.infraFileId })), idempotencyKey }); complete(); message.success(nextDecision === 'overturn' ? '已改判有效' : '已维持无效'); setDecisionState(undefined); setReason(''); setEvidence([]); await load() }).catch(saveError => message.error(saveError instanceof Error ? saveError.message : '申诉裁决失败')) }
  const prepareDecision = () => { if (!selected?.taskId || !reason.trim() || !decision) { message.warning('裁决理由为必填项'); return }; setConfirmOpen(true) }
  const detail = selected ? <Detail item={selected} onDecision={setDecision}/> : <Empty description="从左侧选择一条申诉"/>
  return <section className="workspace-page message-inbox-page"><header className="message-inbox-header"><Typography.Title level={3}>申诉处理</Typography.Title><Tabs activeKey={handled ? 'done' : 'todo'} onChange={key => setHandled(key === 'done')} items={[{ key: 'todo', label: '待处理' }, { key: 'done', label: '已处理' }]}/><Button icon={<ReloadOutlined/>} onClick={() => void load()}>刷新</Button></header>{error && <Alert type="error" showIcon message={error} action={<Button size="small" onClick={() => void load()}>重试</Button>}/>}<div className="message-inbox-layout"><aside className="message-inbox-list-pane"><div className="message-inbox-list">{loading ? <Skeleton active paragraph={{ rows: 8 }}/> : items.length ? <List dataSource={items} renderItem={item => <button type="button" className={`message-inbox-item${selected?.id === item.id ? ' active' : ''}`} onClick={() => { setSelected(item); setDrawerOpen(true) }}><div className="message-inbox-item-main"><Avatar>{item.leadName.slice(0, 1)}</Avatar><div className="message-inbox-item-copy"><div className="message-inbox-item-title"><strong>{item.leadName}</strong><Tag>{statusLabel[item.status]}</Tag></div><span>第 {item.roundNo} 次 · {stageLabel[item.reviewStage]}</span><span>{item.reason}</span></div></div><div className="message-inbox-item-meta"><span>{formatTimestamp(item.submittedAt)}</span></div></button>}/>:<Empty description="暂无申诉"/>}</div></aside><main className="message-inbox-detail-pane">{detail}</main></div><Drawer className="message-inbox-mobile-drawer" open={drawerOpen} onClose={() => setDrawerOpen(false)} title="申诉详情" placement="right" width="100%">{detail}</Drawer><Modal title={decision === 'overturn' ? '改判有效' : '维持无效'} open={Boolean(decision)} onCancel={() => setDecision(undefined)} footer={<Space><Button onClick={() => setDecision(undefined)}>取消</Button><IrreversiblePopconfirm action={decision === 'overturn' ? `将客资「${selected?.leadName || ''}」改判为有效` : `维持客资「${selected?.leadName || ''}」的无效结论`} danger={decision === 'uphold'} open={confirmOpen} onOpenChange={setConfirmOpen} onConfirm={submitDecision}><Button type="primary" danger={decision === 'uphold'} loading={saving} onClick={prepareDecision}>提交裁决</Button></IrreversiblePopconfirm></Space>}><Space direction="vertical" style={{ width: '100%' }}><Form.Item label="裁决理由" required><Input.TextArea rows={5} maxLength={1000} showCount value={reason} onChange={e => setReason(e.target.value)} placeholder="填写裁决理由"/></Form.Item><Form.Item label={`裁决附件${evidence.some(item => item.status === 'uploading') ? '（上传中）' : ''}`}><LeadAppealEvidenceUpload value={evidence} onChange={setEvidence} disabled={saving}/></Form.Item></Space></Modal></section>
}
