import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import {
  Alert, Avatar, Button, Descriptions, Drawer, Empty, Form, Input, InputNumber, Modal, Popconfirm, Radio,
  Select, Space, Spin, Switch, Table, Tabs, Tag, Typography, Upload, message
} from 'antd'
import {
  CheckOutlined, CloseOutlined, DeleteOutlined, EditOutlined, PlusOutlined,
  ReloadOutlined, SafetyCertificateOutlined, StopOutlined, UploadOutlined
} from '@ant-design/icons'
import { formatTimestamp } from '../services/time'
import {
  managementApi, type BusinessAudit, type Cashback, type ImpersonationAudit, type NotifyRule,
  type Partner, type PartnerCreate, type PersonnelState, type RelationScene,
  type UserRelation, type UserRelationLog, type Withdrawal
} from '../services/managementApi'
import type { SimpleDept, SimpleUser } from '../services/api'
import { getStoredImpersonation, IMPERSONATION_CHANGE_EVENT, storeImpersonation } from '../services/impersonation'
import { availableAuditTabs, canUpdateMaintenance, hasPermission, withdrawalDetailScope } from '../services/managementAccess'
import DetailFieldGrid from '../components/DetailFieldGrid'
import DateTimeText from '../components/DateTimeText'

const errorText = (error: unknown, fallback: string) => error instanceof Error ? error.message : fallback
const money = (value?: number) => value == null ? '-' : `¥${Number(value).toFixed(2)}`
const pageTitle = (title: string, description: string, actions?: React.ReactNode) => <div className="page-heading">
  <div><Typography.Title level={4}>{title}</Typography.Title><Typography.Text type="secondary">{description}</Typography.Text></div>{actions}
</div>

function LoadError({ error, retry }: { error: string; retry: () => void }) {
  return <Alert type="error" showIcon message={error} action={<Button size="small" icon={<ReloadOutlined/>} onClick={retry}>重试</Button>}/>
}

export function PersonnelPage({ permissions }: { permissions: string[] }) {
  const [users, setUsers] = useState<SimpleUser[]>([]), [selected, setSelected] = useState<number>(), [keyword, setKeyword] = useState('')
  const [state, setState] = useState<PersonnelState>(), [loading, setLoading] = useState(false), [detailLoading, setDetailLoading] = useState(false), [error, setError] = useState('')
  const [change, setChange] = useState<PersonnelState['state']>(), [reason, setReason] = useState('')
  const [drawerOpen, setDrawerOpen] = useState(false), [saving, setSaving] = useState(false)
  const stateRequest = useRef(0)
  const loadUsers = useCallback(async () => { setLoading(true); setError(''); try { const result = await managementApi.users(); setUsers(result); setSelected(current => current && result.some(user => user.id === current) ? current : result[0]?.id) } catch (e) { setUsers([]); setSelected(undefined); setError(errorText(e, '人员列表加载失败')) } finally { setLoading(false) } }, [])
  const loadState = useCallback(async (userId: number) => { const request = ++stateRequest.current; setDetailLoading(true); setState(undefined); setError(''); try { const result = await managementApi.personnelState(userId); if (request === stateRequest.current) setState(result) } catch (e) { if (request === stateRequest.current) { setState(undefined); setError(errorText(e, '人员状态加载失败')) } } finally { if (request === stateRequest.current) setDetailLoading(false) } }, [])
  useEffect(() => { void loadUsers() }, [loadUsers])
  useEffect(() => { if (selected) void loadState(selected); else setState(undefined) }, [loadState, selected])
  const submit = async () => { if (!selected || !change || !reason.trim()) return; setSaving(true); try { await managementApi.updatePersonnelState(selected, change, reason.trim()); message.success('人员状态已更新'); setChange(undefined); setReason(''); await loadState(selected) } catch (e) { message.error(errorText(e, '人员状态更新失败')) } finally { setSaving(false) } }
  const labels = { enabled: '启用', disabled: '停用', departed: '离职' }
  const visibleUsers = useMemo(() => { const term = keyword.trim().toLowerCase(); return term ? users.filter(user => [user.nickname, user.username, user.deptName].some(value => value?.toLowerCase().includes(term))) : users }, [keyword, users])
  const selectedUser = useMemo(() => users.find(user => user.id === selected), [selected, users])
  const detailContent = detailLoading ? <Spin/> : error && selected ? <LoadError error={error} retry={() => void loadState(selected)}/> : selectedUser && state ? <div className="business-inbox-detail">
    <header className="business-inbox-detail-hero"><div className="business-inbox-detail-heading"><Avatar src={selectedUser.avatar}>{selectedUser.nickname.slice(0, 1)}</Avatar><div><Typography.Title level={4}>{selectedUser.nickname}</Typography.Title><Typography.Text type="secondary">{selectedUser.username || '未设置账号'}</Typography.Text></div></div><Tag color={state.state === 'enabled' ? 'success' : state.state === 'disabled' ? 'warning' : 'default'}>{labels[state.state]}</Tag></header>
    <section className="business-inbox-card"><Typography.Title level={5}>账号与业务状态</Typography.Title><DetailFieldGrid items={[
      { key: 'nickname', label: '姓名', value: selectedUser.nickname }, { key: 'username', label: '账号', value: selectedUser.username },
      { key: 'department', label: '部门', value: selectedUser.deptName }, { key: 'accountState', label: '账号状态', value: selectedUser.status === 0 ? '启用' : selectedUser.status === 1 ? '停用' : undefined },
      { key: 'businessState', label: '业务状态', value: <Tag>{labels[state.state]}</Tag> }, { key: 'changedAt', label: '变更时间', value: formatTimestamp(state.changedAt) },
      { key: 'reason', label: '最近原因', value: state.reason, span: 2 }
    ]}/></section>
    {hasPermission(permissions, 'zsjos:personnel:update-state') && <section className="business-inbox-card"><Typography.Title level={5}>状态操作</Typography.Title><Space wrap className="business-inbox-detail-actions"><Button icon={<CheckOutlined/>} onClick={() => setChange('enabled')}>启用</Button><Button icon={<StopOutlined/>} onClick={() => setChange('disabled')}>停用</Button><Button danger icon={<CloseOutlined/>} onClick={() => setChange('departed')}>离职</Button></Space></section>}
  </div> : <Empty description="从左侧选择一名人员"/>
  return <section className="workspace-page business-inbox-page personnel-page">
    <div className="business-inbox-layout"><aside className="business-inbox-list-pane"><div className="business-inbox-toolbar"><Input.Search allowClear value={keyword} onChange={event => setKeyword(event.target.value)} placeholder="搜索姓名 / 账号 / 部门"/></div>
      {error && !selected && <LoadError error={error} retry={() => void loadUsers()}/>}<div className="business-inbox-scroll">{loading ? <Spin/> : !visibleUsers.length && !error ? <Empty description="暂无人员"/> : visibleUsers.map(user => <button key={user.id} type="button" className={`business-inbox-item${user.id === selected ? ' active' : ''}`} onClick={() => { setSelected(user.id); if (window.matchMedia('(max-width: 768px)').matches) setDrawerOpen(true) }}><div className="business-inbox-item-main"><Avatar src={user.avatar}>{user.nickname.slice(0, 1)}</Avatar><div className="business-inbox-item-copy"><div className="business-inbox-item-title"><strong>{user.nickname}</strong>{user.id === selected && state && <Tag color={state.state === 'enabled' ? 'success' : 'default'}>{labels[state.state]}</Tag>}</div><span>{user.username || '未设置账号'}</span><span>{user.deptName || '未设置部门'}</span></div></div></button>)}</div>
    </aside><main className="business-inbox-detail-pane">{detailContent}</main></div>
    <Drawer className="business-inbox-mobile-drawer" open={drawerOpen} onClose={() => setDrawerOpen(false)} title="人员详情" width="100%">{detailContent}</Drawer>
    <Modal title="变更人员状态" open={Boolean(change)} confirmLoading={saving} onCancel={() => { setChange(undefined); setReason('') }} onOk={() => void submit()} okButtonProps={{ disabled: !reason.trim() }}><Input.TextArea rows={4} maxLength={500} showCount value={reason} onChange={e => setReason(e.target.value)} placeholder="填写变更原因（必填）"/></Modal>
  </section>
}

export function PartnerPage({ permissions }: { permissions: string[] }) {
  const [items, setItems] = useState<Partner[]>([]), [departments, setDepartments] = useState<SimpleDept[]>([]), [loading, setLoading] = useState(false), [error, setError] = useState('')
  const [createOpen, setCreateOpen] = useState(false), [convert, setConvert] = useState<Partner>(), [stateChange, setStateChange] = useState<{ row: Partner; enabled: boolean }>(), [reason, setReason] = useState('')
  const [createForm] = Form.useForm<PartnerCreate>(), [convertForm] = Form.useForm<{ username: string; password: string; targetType: string; deptId: number; migrateHistoricalOrganization: boolean; reason: string }>()
  const load = useCallback(async () => { setLoading(true); setError(''); try { setItems(await managementApi.partners()) } catch (e) { setItems([]); setError(errorText(e, '兼职列表加载失败')) } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  const submitCreate = async () => { try { const values = await createForm.validateFields(); await managementApi.createPartner(values); message.success('兼职账号已创建'); setCreateOpen(false); createForm.resetFields(); await load() } catch (e) { if (e instanceof Error) message.error(e.message) } }
  const submitState = async () => { if (!stateChange || !reason.trim()) return; try { await managementApi.setPartnerEnabled(stateChange.row.id, stateChange.enabled, reason.trim()); message.success('兼职状态已更新'); setStateChange(undefined); setReason(''); await load() } catch (e) { message.error(errorText(e, '状态更新失败')) } }
  const openConvert = async (row: Partner) => { setConvert(row); convertForm.setFieldsValue({ targetType: 'new_media_employee', migrateHistoricalOrganization: false }); try { setDepartments(await managementApi.departments()) } catch (e) { message.error(errorText(e, '部门列表加载失败')) } }
  const submitConvert = async () => { if (!convert) return; try { const values = await convertForm.validateFields(); await managementApi.convertPartner(convert.id, values); message.success('兼职已转为员工'); setConvert(undefined); convertForm.resetFields(); await load() } catch (e) { if (e instanceof Error) message.error(e.message) } }
  const labels = { enabled: '启用', disabled: '停用', converted: '已转员工' }
  return <section className="workspace-page management-page">{pageTitle('兼职主体', '维护兼职账号及员工转换', hasPermission(permissions, 'zsjos:partner:create') ? <Button type="primary" icon={<PlusOutlined/>} onClick={() => setCreateOpen(true)}>新增兼职</Button> : undefined)}
    {error && <LoadError error={error} retry={() => void load()}/>}<Table rowKey="id" loading={loading} dataSource={items} locale={{ emptyText: <Empty description="暂无兼职主体"/> }} columns={[{ title: '兼职编号', dataIndex: 'partnerNo' }, { title: '姓名', dataIndex: 'name' }, { title: '手机号', dataIndex: 'mobile' }, { title: '状态', dataIndex: 'status', render: value => <Tag>{labels[value as keyof typeof labels] || value}</Tag> }, { title: '操作', render: (_, row) => <Space>{hasPermission(permissions, 'zsjos:partner:update-state') && row.status !== 'converted' && <Button type="link" onClick={() => { setReason(''); setStateChange({ row, enabled: row.status === 'disabled' }) }}>{row.status === 'disabled' ? '启用' : '停用'}</Button>}{hasPermission(permissions, 'zsjos:partner:convert') && row.status === 'enabled' && <Button type="link" onClick={() => void openConvert(row)}>转为员工</Button>}</Space> }]}/>
    <Modal title="新增兼职账号" open={createOpen} onCancel={() => setCreateOpen(false)} onOk={() => void submitCreate()}><Form form={createForm} layout="vertical"><Form.Item name="partnerNo" label="兼职编号" rules={[{ required: true }]}><Input/></Form.Item><Form.Item name="name" label="姓名" rules={[{ required: true }]}><Input/></Form.Item><Form.Item name="mobile" label="手机号" rules={[{ required: true }, { pattern: /^1\d{10}$/, message: '请输入正确的手机号' }]}><Input maxLength={11}/></Form.Item><Form.Item name="password" label="初始密码" rules={[{ required: true }, { pattern: /^(?=.*[A-Za-z])(?=.*\d).{8,20}$/, message: '8-20 位且包含字母和数字' }]}><Input.Password/></Form.Item><Form.Item name="channelId" label="渠道编号"><Input/></Form.Item></Form></Modal>
    <Modal title={stateChange?.enabled ? '启用兼职' : '停用兼职'} open={Boolean(stateChange)} onCancel={() => setStateChange(undefined)} onOk={() => void submitState()} okButtonProps={{ disabled: !reason.trim() }}><Input.TextArea value={reason} onChange={e => setReason(e.target.value)} rows={4} placeholder="填写变更原因（必填）"/></Modal>
    <Modal title="兼职转为员工" open={Boolean(convert)} onCancel={() => setConvert(undefined)} onOk={() => void submitConvert()}><Form form={convertForm} layout="vertical"><Form.Item name="targetType" label="员工类型" rules={[{ required: true }]}><Radio.Group options={[{ label: '新媒体员工', value: 'new_media_employee' }, { label: '新媒体主管', value: 'new_media_manager' }]}/></Form.Item><Form.Item name="username" label="员工用户名" rules={[{ required: true }, { pattern: /^[A-Za-z0-9_]{4,32}$/, message: '4-32 位字母、数字或下划线' }]}><Input/></Form.Item><Form.Item name="password" label="员工初始密码" rules={[{ required: true }, { pattern: /^(?=.*[A-Za-z])(?=.*\d).{8,20}$/, message: '8-20 位且包含字母和数字' }]}><Input.Password/></Form.Item><Form.Item name="deptId" label="归属部门" rules={[{ required: true }]}><Select showSearch optionFilterProp="label" options={departments.map(item => ({ label: item.name, value: item.id }))}/></Form.Item><Form.Item name="migrateHistoricalOrganization" label="迁移历史快照" valuePropName="checked"><Switch/></Form.Item><Form.Item name="reason" label="转换原因" rules={[{ required: true }]}><Input.TextArea rows={4} maxLength={500}/></Form.Item></Form></Modal>
  </section>
}

export function ImpersonationPage({ permissions }: { permissions: string[] }) {
  const [active, setActive] = useState(getStoredImpersonation()), [users, setUsers] = useState<SimpleUser[]>([]), [target, setTarget] = useState<number>(), [reason, setReason] = useState(''), [loading, setLoading] = useState(false), [usersLoading, setUsersLoading] = useState(false), [error, setError] = useState('')
  const load = useCallback(async () => { if (active) return; setUsersLoading(true); setError(''); try { setUsers(await managementApi.users()) } catch (e) { setUsers([]); setError(errorText(e, '账号列表加载失败')) } finally { setUsersLoading(false) } }, [active])
  useEffect(() => { void load() }, [load])
  useEffect(() => { const sync = () => setActive(getStoredImpersonation()); window.addEventListener(IMPERSONATION_CHANGE_EVENT, sync); return () => window.removeEventListener(IMPERSONATION_CHANGE_EVENT, sync) }, [])
  const start = async () => { if (!target || !reason.trim()) return; setLoading(true); try { const session = storeImpersonation(await managementApi.startImpersonation(target, reason.trim())); if (!session) throw new Error('服务端返回了无效的借视图会话'); setActive(session); message.success('只读借视图已开启') } catch (e) { message.error(errorText(e, '借视图开启失败')) } finally { setLoading(false) } }
  const end = async () => { if (!active) return; setLoading(true); try { await managementApi.endImpersonation(active.id); storeImpersonation(); setActive(undefined); message.success('借视图已结束') } catch (e) { message.error(errorText(e, '借视图结束失败')) } finally { setLoading(false) } }
  return <section className="workspace-page management-page">{pageTitle('只读借视图', '以目标账号的数据权限排查问题，写操作由服务端统一拒绝')}{active ? <section className="management-panel"><Alert type="warning" showIcon message={`正在以 ${active.targetNameSnapshot} 的权限只读查看`} description="30 分钟无活动后会话自动失效。"/><Descriptions bordered column={1} items={[{ key: 'target', label: '目标账号', children: active.targetNameSnapshot }, { key: 'time', label: '开始时间', children: formatTimestamp(active.startedAt) }, { key: 'reason', label: '借用原因', children: active.reason }]}/><Button danger loading={loading} onClick={() => void end()}>结束借视图</Button></section> : <section className="management-panel">{error && <LoadError error={error} retry={() => void load()}/>}<Form layout="vertical" className="management-form"><Form.Item label="目标账号" required><Select showSearch optionFilterProp="label" value={target} loading={usersLoading} notFoundContent={usersLoading ? <Spin size="small"/> : '暂无启用账号'} onChange={setTarget} options={users.map(user => ({ value: user.id, label: user.nickname }))}/></Form.Item><Form.Item label="借用原因" required><Input.TextArea rows={4} maxLength={500} showCount value={reason} onChange={e => setReason(e.target.value)}/></Form.Item>{hasPermission(permissions, 'zsjos:impersonation:start') && <Button type="primary" icon={<SafetyCertificateOutlined/>} loading={loading} disabled={!target || !reason.trim()} onClick={() => void start()}>开始只读借视图</Button>}</Form></section>}</section>
}

export function BusinessAuditPage({ permissions }: { permissions: string[] }) {
  const auditTabs = useMemo(() => availableAuditTabs(permissions), [permissions])
  const [tab, setTab] = useState<'business' | 'impersonation'>(() => auditTabs[0] || 'business'), [loading, setLoading] = useState(false), [error, setError] = useState('')
  const [business, setBusiness] = useState<BusinessAudit[]>([]), [impersonation, setImpersonation] = useState<ImpersonationAudit[]>([]), [total, setTotal] = useState(0), [page, setPage] = useState(1)
  const [actionCode, setActionCode] = useState(''), [targetType, setTargetType] = useState(''), [sessionId, setSessionId] = useState<number | null>(null)
  const auditRequest = useRef(0)
  const load = useCallback(async (targetPage = page) => { if (!auditTabs.includes(tab)) return; const request = ++auditRequest.current; setLoading(true); setError(''); try { const result = tab === 'business' ? await managementApi.businessAudits({ pageNo: targetPage, pageSize: 10, actionCode: actionCode || undefined, targetType: targetType || undefined }) : await managementApi.impersonationAudits({ pageNo: targetPage, pageSize: 10, sessionId: sessionId || undefined }); if (request !== auditRequest.current) return; if (tab === 'business') setBusiness(result.list as BusinessAudit[]); else setImpersonation(result.list as ImpersonationAudit[]); setTotal(result.total); setPage(targetPage) } catch (e) { if (request === auditRequest.current) setError(errorText(e, '审计记录加载失败')) } finally { if (request === auditRequest.current) setLoading(false) } }, [actionCode, auditTabs, page, sessionId, tab, targetType])
  useEffect(() => { void load(1) }, [tab]) // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { if (!auditTabs.includes(tab) && auditTabs[0]) setTab(auditTabs[0]) }, [auditTabs, tab])
  const businessColumns = [{ title: '操作人', dataIndex: 'operatorNameSnapshot' }, { title: '角色快照', dataIndex: 'operatorRoleSnapshot' }, { title: '动作编码', dataIndex: 'actionCode' }, { title: '目标', render: (_: unknown, row: BusinessAudit) => `${row.targetType} / ${row.targetId}` }, { title: '来源 IP', dataIndex: 'sourceIp' }, { title: '时间', dataIndex: 'occurredAt', width: 180, render: (value: BusinessAudit['occurredAt']) => <DateTimeText value={value} precision="second"/> }]
  const impersonationColumns = [{ title: '会话编号', dataIndex: 'sessionId' }, { title: '原管理员', dataIndex: 'administratorUserId' }, { title: '目标员工', dataIndex: 'targetUserId' }, { title: '方法', dataIndex: 'httpMethod' }, { title: '请求路径', dataIndex: 'requestPath' }, { title: '时间', dataIndex: 'occurredAt', width: 180, render: (value: ImpersonationAudit['occurredAt']) => <DateTimeText value={value} precision="second"/> }]
  return <section className="workspace-page management-page">{pageTitle('业务审计', '查询关键业务动作与借视图访问轨迹')} {!auditTabs.length ? <Alert type="warning" showIcon message="无权查看业务审计"/> : <><Tabs activeKey={tab} onChange={value => { setPage(1); setTab(value as 'business' | 'impersonation') }} items={auditTabs.map(key => ({ key, label: key === 'business' ? '业务审计' : '借视图请求审计' }))}/><Space wrap className="management-filters">{tab === 'business' ? <><Input value={actionCode} onChange={e => setActionCode(e.target.value)} placeholder="动作编码"/><Input value={targetType} onChange={e => setTargetType(e.target.value)} placeholder="目标类型"/></> : <InputNumber min={1} value={sessionId} onChange={setSessionId} placeholder="会话编号"/>}<Button type="primary" onClick={() => void load(1)}>查询</Button></Space>{error && <LoadError error={error} retry={() => void load()}/>} {tab === 'business' ? <Table<BusinessAudit> rowKey="id" loading={loading} dataSource={business} columns={businessColumns} pagination={{ current: page, total, pageSize: 10, onChange: next => void load(next) }} scroll={{ x: 900 }}/> : <Table<ImpersonationAudit> rowKey="id" loading={loading} dataSource={impersonation} columns={impersonationColumns} pagination={{ current: page, total, pageSize: 10, onChange: next => void load(next) }} scroll={{ x: 900 }}/>}</>}</section>
}

const cashbackStatuses = [{ value: 'pending_settlement', label: '待结算' }, { value: 'available', label: '可提现' }, { value: 'withdrawing', label: '提现中' }, { value: 'withdrawn', label: '已提现' }, { value: 'cancelled', label: '已取消' }]
export function CashbackPage({ permissions }: { permissions: string[] }) {
  const finance = hasPermission(permissions, 'zsjos:cashback:finance-query'), authorized = finance || hasPermission(permissions, 'zsjos:cashback:my-query'), [items, setItems] = useState<Cashback[]>([]), [loading, setLoading] = useState(false), [error, setError] = useState(authorized ? '' : '无权查看返现记录'), [page, setPage] = useState(1), [total, setTotal] = useState(0), [type, setType] = useState<string>(), [status, setStatus] = useState<string>()
  const load = useCallback(async (next = page) => { if (!authorized) return; setLoading(true); setError(''); try { const result = await managementApi.cashbacks(!finance, { pageNo: next, pageSize: 10, type, status }); setItems(result.list); setTotal(result.total); setPage(next) } catch (e) { setError(errorText(e, '返现记录加载失败')) } finally { setLoading(false) } }, [authorized, finance, page, status, type])
  useEffect(() => { void load(1) }, []) // eslint-disable-line react-hooks/exhaustive-deps
  return <section className="workspace-page management-page">{pageTitle(finance ? '返现管理' : '我的返现', finance ? '查看业务范围内返现台账' : '查看个人返现进度')}<Space wrap className="management-filters"><Select allowClear value={type} onChange={setType} placeholder="返现类型" options={[{ value: 'valid', label: '有效返现' }, { value: 'deal', label: '成交返现' }]}/><Select allowClear value={status} onChange={setStatus} placeholder="返现状态" options={cashbackStatuses}/><Button type="primary" onClick={() => void load(1)}>查询</Button></Space>{error && <LoadError error={error} retry={() => void load()}/>}<Table rowKey="id" loading={loading} dataSource={items} pagination={{ current: page, total, pageSize: 10, onChange: next => void load(next) }} columns={[{ title: '返现单号', dataIndex: 'cashbackNo' }, { title: '类型', dataIndex: 'type', render: v => v === 'valid' ? '有效返现' : '成交返现' }, { title: '产品', dataIndex: 'productNameSnapshot' }, { title: '金额', dataIndex: 'amount', render: money }, { title: '状态', dataIndex: 'status', render: value => <Tag>{cashbackStatuses.find(item => item.value === value)?.label || value}</Tag> }, { title: '可用时间', dataIndex: 'availableAt', render: value => formatTimestamp(value) }]} scroll={{ x: 850 }}/></section>
}

export function WithdrawalPage({ permissions }: { permissions: string[] }) {
  const detailScope = withdrawalDetailScope(permissions), own = detailScope === 'own', authorized = own ? hasPermission(permissions, 'zsjos:withdrawal:my-query') : true, [items, setItems] = useState<Withdrawal[]>([]), [loading, setLoading] = useState(false), [error, setError] = useState(authorized ? '' : '无权查看提现记录'), [page, setPage] = useState(1), [total, setTotal] = useState(0), [status, setStatus] = useState<string>(), [detail, setDetail] = useState<Withdrawal>()
  const [applyOpen, setApplyOpen] = useState(false), [available, setAvailable] = useState<Cashback[]>([]), [applyForm] = Form.useForm(), [selectedCashbacks, setSelectedCashbacks] = useState<number[]>([])
  const [action, setAction] = useState<'reject' | 'payout'>(), [actionForm] = Form.useForm(), [proofFileId, setProofFileId] = useState<number>()
  const load = useCallback(async (next = page) => { if (!authorized) return; setLoading(true); setError(''); try { const result = await managementApi.withdrawals(own, { pageNo: next, pageSize: 10, status }); setItems(result.list); setTotal(result.total); setPage(next) } catch (e) { setError(errorText(e, '提现记录加载失败')) } finally { setLoading(false) } }, [authorized, own, page, status])
  useEffect(() => { void load(1) }, []) // eslint-disable-line react-hooks/exhaustive-deps
  const openDetail = async (row: Withdrawal) => { try { setDetail(await managementApi.withdrawal(row.id, detailScope)) } catch (e) { message.error(errorText(e, '提现详情加载失败')) } }
  const openApply = async () => { setApplyOpen(true); setSelectedCashbacks([]); try { setAvailable((await managementApi.cashbacks(true, { pageNo: 1, pageSize: 100, status: 'available' })).list) } catch (e) { message.error(errorText(e, '可提现返现加载失败')) } }
  const submitApply = async () => { try { const values = await applyForm.validateFields(); if (!selectedCashbacks.length) return message.warning('请选择返现记录'); await managementApi.applyWithdrawal({ ...values, cashbackIds: selectedCashbacks }); message.success('提现申请已提交'); setApplyOpen(false); await load(1) } catch (e) { if (e instanceof Error) message.error(e.message) } }
  const cancel = async (id: number) => { try { await managementApi.cancelWithdrawal(id); message.success('提现申请已撤销'); await load() } catch (e) { message.error(errorText(e, '撤销失败')) } }
  const submitAction = async () => { if (!detail || !action) return; try { const values = await actionForm.validateFields(); if (action === 'reject') await managementApi.rejectWithdrawal(detail.id, values.reason); else { if (!proofFileId) return message.warning('请上传付款凭证'); await managementApi.payoutWithdrawal(detail.id, { bankTransactionNo: values.bankTransactionNo, proofFileId, remark: values.remark }) } message.success(action === 'reject' ? '已驳回提现' : '已登记打款'); setAction(undefined); setDetail(undefined); await load() } catch (e) { if (e instanceof Error) message.error(e.message) } }
  return <section className="workspace-page management-page">{pageTitle(own ? '我的提现' : '提现管理', own ? '提交并跟踪返现提现申请' : '审核与登记提现打款', own && hasPermission(permissions, 'zsjos:withdrawal:apply') ? <Button type="primary" icon={<PlusOutlined/>} onClick={() => void openApply()}>申请提现</Button> : undefined)}<Space className="management-filters"><Select allowClear value={status} onChange={setStatus} placeholder="提现状态" options={['pending_approval','approved','rejected','paid','cancelled'].map(value => ({ value, label: value }))}/><Button type="primary" onClick={() => void load(1)}>查询</Button></Space>{error && <LoadError error={error} retry={() => void load()}/>}<Table rowKey="id" loading={loading} dataSource={items} pagination={{ current: page, total, pageSize: 10, onChange: next => void load(next) }} columns={[{ title: '提现单号', dataIndex: 'withdrawalNo' }, { title: '申请金额', dataIndex: 'applicationAmount', render: money }, { title: '账户名', dataIndex: 'accountNameSnapshot' }, { title: '银行卡', dataIndex: 'maskedCardNumber' }, { title: '状态', dataIndex: 'status', render: value => <Tag>{value}</Tag> }, { title: '提交时间', dataIndex: 'submittedAt', render: value => formatTimestamp(value) }, { title: '操作', render: (_, row) => <Space><Button type="link" onClick={() => void openDetail(row)}>详情</Button>{own && row.status === 'pending_approval' && <Popconfirm title="确认撤销该提现申请？" onConfirm={() => void cancel(row.id)}><Button type="link" danger>撤销</Button></Popconfirm>}</Space> }]} scroll={{ x: 950 }}/>
    <Modal width={760} title="申请提现" open={applyOpen} onCancel={() => setApplyOpen(false)} onOk={() => void submitApply()}><Table rowKey="id" size="small" dataSource={available} rowSelection={{ selectedRowKeys: selectedCashbacks, onChange: keys => setSelectedCashbacks(keys as number[]) }} pagination={false} columns={[{ title: '返现单号', dataIndex: 'cashbackNo' }, { title: '产品', dataIndex: 'productNameSnapshot' }, { title: '金额', dataIndex: 'amount', render: money }]}/><Form form={applyForm} layout="vertical"><Form.Item name="accountName" label="账户名" rules={[{ required: true }]}><Input/></Form.Item><Form.Item name="cardNumber" label="银行卡号" rules={[{ required: true }]}><Input/></Form.Item><Form.Item name="bankName" label="开户银行" rules={[{ required: true }]}><Input/></Form.Item><Form.Item name="branchName" label="开户支行"><Input/></Form.Item><Form.Item name="saveCard" label="保存银行卡" valuePropName="checked" initialValue={false}><Switch/></Form.Item></Form></Modal>
    <Modal title="提现详情" open={Boolean(detail) && !action} onCancel={() => setDetail(undefined)} footer={detail && !own ? <Space>{hasPermission(permissions, 'zsjos:withdrawal:review') && detail.status === 'approved' && <Button danger onClick={() => { actionForm.resetFields(); setAction('reject') }}>驳回已通过申请</Button>}{hasPermission(permissions, 'zsjos:withdrawal:payout') && detail.status === 'approved' && <Button type="primary" onClick={() => { actionForm.resetFields(); setProofFileId(undefined); setAction('payout') }}>登记打款</Button>}</Space> : undefined}><Descriptions bordered column={1} items={detail ? [{ key: 'no', label: '提现单号', children: detail.withdrawalNo }, { key: 'amount', label: '金额', children: money(detail.applicationAmount) }, { key: 'account', label: '收款账户', children: `${detail.accountNameSnapshot} / ${detail.bankNameSnapshot} / ${detail.maskedCardNumber}` }, { key: 'status', label: '状态', children: detail.status }, { key: 'reason', label: '驳回原因', children: detail.rejectionReason || '-' }] : []}/></Modal>
    <Modal title={action === 'reject' ? '驳回提现' : '登记打款'} open={Boolean(action)} onCancel={() => setAction(undefined)} onOk={() => void submitAction()}><Form form={actionForm} layout="vertical">{action === 'reject' ? <Form.Item name="reason" label="驳回原因" rules={[{ required: true }]}><Input.TextArea rows={4}/></Form.Item> : <><Form.Item name="bankTransactionNo" label="银行流水号" rules={[{ required: true }]}><Input/></Form.Item><Form.Item label="付款凭证" required><Upload maxCount={1} onRemove={() => { setProofFileId(undefined) }} beforeUpload={async file => { setProofFileId(undefined); try { setProofFileId((await managementApi.uploadWithdrawalProof(file)).infraFileId); message.success('凭证已上传') } catch (e) { message.error(errorText(e, '凭证上传失败')) } return false }}><Button icon={<UploadOutlined/>}>上传凭证</Button></Upload></Form.Item><Form.Item name="remark" label="备注"><Input.TextArea rows={3}/></Form.Item></>}</Form></Modal>
  </section>
}

export function UserRelationPage({ permissions }: { permissions: string[] }) {
  const [items, setItems] = useState<RelationScene[]>([]), [loading, setLoading] = useState(false), [error, setError] = useState(''), [page, setPage] = useState(1), [total, setTotal] = useState(0), [editing, setEditing] = useState<RelationScene | null>(), [form] = Form.useForm<RelationScene>()
  const [scene, setScene] = useState<RelationScene>(), [relations, setRelations] = useState<UserRelation[]>([]), [logs, setLogs] = useState<UserRelationLog[]>([]), [targets, setTargets] = useState<{ label: string; value: number }[]>([]), [relationForm] = Form.useForm()
  const [relationLoading, setRelationLoading] = useState(false), [relationError, setRelationError] = useState(''), [relationPage, setRelationPage] = useState(1), [relationTotal, setRelationTotal] = useState(0)
  const [targetLoading, setTargetLoading] = useState(false), [targetError, setTargetError] = useState('')
  const [logLoading, setLogLoading] = useState(false), [logError, setLogError] = useState(''), [logPage, setLogPage] = useState(1), [logTotal, setLogTotal] = useState(0)
  const activeSceneCode = useRef<string | undefined>(undefined)
  const relationRequest = useRef(0), targetRequest = useRef(0), logRequest = useRef(0)
  const canViewLogs = hasPermission(permissions, 'zsjos:user-relation:log-query')
  const load = useCallback(async (next = page) => { setLoading(true); setError(''); try { const result = await managementApi.relationScenes({ pageNo: next, pageSize: 10 }); setItems(result.list); setTotal(result.total); setPage(next) } catch (e) { setError(errorText(e, '关系场景加载失败')) } finally { setLoading(false) } }, [page])
  useEffect(() => { void load(1) }, []) // eslint-disable-line react-hooks/exhaustive-deps
  const saveScene = async () => { try { const values = await form.validateFields(); if (editing?.id) await managementApi.updateRelationScene({ ...values, id: editing.id }); else await managementApi.createRelationScene(values); message.success('关系场景已保存'); setEditing(null); await load() } catch (e) { if (e instanceof Error) message.error(e.message) } }
  const remove = async (id: number) => { try { await managementApi.deleteRelationScene(id); message.success('关系场景已删除'); await load() } catch (e) { message.error(errorText(e, '删除失败')) } }
  const loadRelations = async (sceneCode: string, next = 1) => { const request = ++relationRequest.current; setRelationLoading(true); setRelationError(''); try { const result = await managementApi.relations(sceneCode, next, 20); if (activeSceneCode.current !== sceneCode || request !== relationRequest.current) return; setRelations(result.list); setRelationTotal(result.total); setRelationPage(next) } catch (e) { if (activeSceneCode.current !== sceneCode || request !== relationRequest.current) return; setRelations([]); setRelationError(errorText(e, '关系数据加载失败')) } finally { if (activeSceneCode.current === sceneCode && request === relationRequest.current) setRelationLoading(false) } }
  const loadTargets = async (sceneCode: string) => { const request = ++targetRequest.current; setTargetLoading(true); setTargetError(''); try { const result = await managementApi.relationTargets(sceneCode); if (activeSceneCode.current !== sceneCode || request !== targetRequest.current) return; setTargets(result.map(item => ({ value: item.id, label: item.nickname }))) } catch (e) { if (activeSceneCode.current !== sceneCode || request !== targetRequest.current) return; setTargets([]); setTargetError(errorText(e, '可选目标用户加载失败')) } finally { if (activeSceneCode.current === sceneCode && request === targetRequest.current) setTargetLoading(false) } }
  const loadLogs = async (sceneCode: string, next = 1) => { if (!canViewLogs) return; const request = ++logRequest.current; setLogLoading(true); setLogError(''); try { const result = await managementApi.relationLogs(sceneCode, next, 20); if (activeSceneCode.current !== sceneCode || request !== logRequest.current) return; setLogs(result.list); setLogTotal(result.total); setLogPage(next) } catch (e) { if (activeSceneCode.current !== sceneCode || request !== logRequest.current) return; setLogs([]); setLogError(errorText(e, '关系日志加载失败')) } finally { if (activeSceneCode.current === sceneCode && request === logRequest.current) setLogLoading(false) } }
  const openData = async (row: RelationScene) => { activeSceneCode.current = row.code; setScene(row); setRelations([]); setLogs([]); setTargets([]); setRelationPage(1); setRelationTotal(0); setLogPage(1); setLogTotal(0); setLogError(''); setTargetError(''); relationForm.resetFields(); await Promise.all([loadRelations(row.code, 1), loadTargets(row.code)]) }
  const saveRelation = async () => { if (!scene) return; try { const values = await relationForm.validateFields(); await managementApi.saveRelations({ sceneCode: scene.code, ...values }); message.success('关系数据已保存'); await loadRelations(scene.code, relationPage); if (canViewLogs) await loadLogs(scene.code, 1) } catch (e) { if (e instanceof Error) message.error(e.message) } }
  return <section className="workspace-page management-page">{pageTitle('用户关系场景', '配置组织关系场景、关系数据与变更日志', hasPermission(permissions, 'zsjos:user-relation-scene:create') ? <Button type="primary" icon={<PlusOutlined/>} onClick={() => { form.resetFields(); setEditing({} as RelationScene) }}>新增场景</Button> : undefined)}{error && <LoadError error={error} retry={() => void load()}/>}<Table rowKey="id" loading={loading} dataSource={items} pagination={{ current: page, total, pageSize: 10, onChange: next => void load(next) }} columns={[{ title: '场景名称', dataIndex: 'name' }, { title: '场景编码', dataIndex: 'code' }, { title: '关系方向', render: (_, row) => `${row.sourceLabel} → ${row.targetLabel}` }, { title: '状态', dataIndex: 'status', render: value => <Tag color={value === 0 ? 'green' : 'default'}>{value === 0 ? '启用' : '停用'}</Tag> }, { title: '操作', render: (_, row) => <Space>{hasPermission(permissions, 'zsjos:user-relation-scene:update') && <Button type="link" icon={<EditOutlined/>} onClick={() => { setEditing(row); form.setFieldsValue(row) }}>编辑</Button>}{hasPermission(permissions, 'zsjos:user-relation:query') && <Button type="link" onClick={() => void openData(row)}>关系数据</Button>}{hasPermission(permissions, 'zsjos:user-relation-scene:delete') && <Popconfirm title="确认删除该场景？" onConfirm={() => void remove(row.id!)}><Button type="link" danger icon={<DeleteOutlined/>}>删除</Button></Popconfirm>}</Space> }]} scroll={{ x: 850 }}/>
    <Modal title={editing?.id ? '编辑关系场景' : '新增关系场景'} open={Boolean(editing)} onCancel={() => setEditing(null)} onOk={() => void saveScene()}><Form form={form} layout="vertical"><Form.Item name="name" label="场景名称" rules={[{ required: true }]}><Input/></Form.Item><Form.Item name="code" label="场景编码" rules={[{ required: true }]}><Input disabled={Boolean(editing?.id)}/></Form.Item><Form.Item name="sourceLabel" label="来源称谓" rules={[{ required: true }]}><Input/></Form.Item><Form.Item name="targetLabel" label="目标称谓" rules={[{ required: true }]}><Input/></Form.Item><Form.Item name="sourcePostCode" label="来源岗位编码" rules={[{ required: true }]}><Input/></Form.Item><Form.Item name="targetPostCode" label="目标岗位编码" rules={[{ required: true }]}><Input/></Form.Item><Form.Item name="status" label="状态" initialValue={0}><Radio.Group options={[{ value: 0, label: '启用' }, { value: 1, label: '停用' }]}/></Form.Item><Form.Item name="remark" label="备注"><Input.TextArea rows={3}/></Form.Item></Form></Modal>
    <Modal width={960} title={scene ? `${scene.name} - 关系数据` : '关系数据'} open={Boolean(scene)} onCancel={() => setScene(undefined)} footer={null}><Tabs onChange={key => { if (key === 'logs' && scene && canViewLogs && !logs.length && !logLoading) void loadLogs(scene.code, 1) }} items={[{ key: 'data', label: '关系数据', children: <>{relationError && <LoadError error={relationError} retry={() => scene && void loadRelations(scene.code, relationPage)}/>}<Table<UserRelation> rowKey="id" size="small" loading={relationLoading} dataSource={relations} pagination={{ current: relationPage, total: relationTotal, pageSize: 20, showSizeChanger: false, onChange: next => scene && void loadRelations(scene.code, next) }} columns={[{ title: scene?.sourceLabel || '来源用户', dataIndex: 'nickname' }, { title: scene?.targetLabel || '目标用户', render: (_, row) => row.targetUsers.map(item => item.nickname).join('、') || '-' }, { title: '有效/失效', render: (_, row) => `${row.validTargetCount} / ${row.invalidTargetCount}` }]}/>{hasPermission(permissions, 'zsjos:user-relation:update') && <Form form={relationForm} layout="vertical" className="management-relation-form">{targetError && <LoadError error={targetError} retry={() => scene && void loadTargets(scene.code)}/>}<Form.Item name="sourceUserIds" label="来源用户" rules={[{ required: true }]}><Select mode="multiple" options={relations.map(item => ({ value: item.id, label: item.nickname }))}/></Form.Item><Form.Item name="targetUserIds" label="目标用户" rules={[{ required: true }]}><Select mode="multiple" loading={targetLoading} notFoundContent={targetLoading ? <Spin size="small"/> : '暂无可选目标用户'} options={targets}/></Form.Item><Form.Item name="mode" label="保存方式" initialValue="replace"><Radio.Group options={[{ value: 'append', label: '追加' }, { value: 'replace', label: '替换' }, { value: 'remove', label: '移除' }]}/></Form.Item><Button type="primary" disabled={targetLoading || Boolean(targetError)} onClick={() => void saveRelation()}>保存关系</Button></Form>}</> }, { key: 'logs', label: '变更日志', children: canViewLogs ? <>{logError && <LoadError error={logError} retry={() => scene && void loadLogs(scene.code, logPage)}/>}<Table<UserRelationLog> rowKey="id" size="small" loading={logLoading} dataSource={logs} pagination={{ current: logPage, total: logTotal, pageSize: 20, showSizeChanger: false, onChange: next => scene && void loadLogs(scene.code, next) }} columns={[{ title: '来源用户', dataIndex: 'sourceUsers' }, { title: '目标用户', dataIndex: 'targetUsers' }, { title: '方式', dataIndex: 'actionType' }, { title: '操作人', dataIndex: 'operatorName' }, { title: '时间', dataIndex: 'createTime', width: 180, render: value => <DateTimeText value={value} precision="second"/> }]}/></> : <Alert type="warning" message="无权查看关系日志"/> }]}/></Modal>
  </section>
}

export function MaintenancePage({ roles }: { roles: string[] }) {
  const [enabled, setEnabled] = useState(false), [loading, setLoading] = useState(true), [error, setError] = useState('')
  const canUpdate = canUpdateMaintenance(roles)
  const load = useCallback(async () => { setLoading(true); setError(''); try { setEnabled((await managementApi.maintenance()).enabled) } catch (e) { setError(errorText(e, '维护模式加载失败')) } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  const update = async (next: boolean) => { if (!canUpdate) return; setLoading(true); try { await managementApi.updateMaintenance(next); setEnabled(next); message.success(next ? '维护模式已开启' : '维护模式已关闭') } catch (e) { message.error(errorText(e, '维护模式更新失败')) } finally { setLoading(false) } }
  return <section className="workspace-page management-page">{pageTitle('维护模式', '控制系统维护窗口期间的访问状态')}<section className="management-panel management-maintenance">{error && <LoadError error={error} retry={() => void load()}/>}<Alert type={enabled ? 'warning' : 'success'} showIcon message={enabled ? '系统当前处于维护模式' : '系统当前正常运行'} description={enabled ? '普通用户将无法进入业务系统，请在维护完成后及时关闭。' : '业务访问未受维护模式限制。'}/><Space><Switch checked={enabled} loading={loading} disabled={!canUpdate} onChange={next => void update(next)}/><Typography.Text>{enabled ? '已开启' : '已关闭'}</Typography.Text></Space>{!canUpdate && <Typography.Text type="secondary">仅超级管理员可切换维护模式</Typography.Text>}</section></section>
}

export function NotifyRulePage({ permissions }: { permissions: string[] }) {
  const [items, setItems] = useState<NotifyRule[]>([]), [scenes, setScenes] = useState<Awaited<ReturnType<typeof managementApi.notifyScenes>>>([]), [templates, setTemplates] = useState<Awaited<ReturnType<typeof managementApi.notifyTemplates>>>([]), [users, setUsers] = useState<SimpleUser[]>([])
  const [loading, setLoading] = useState(false), [error, setError] = useState(''), [page, setPage] = useState(1), [total, setTotal] = useState(0), [editing, setEditing] = useState<NotifyRule | null>(), [form] = Form.useForm<NotifyRule>(), [name, setName] = useState(''), [sceneCode, setSceneCode] = useState<string>()
  const load = useCallback(async (next = page) => { setLoading(true); setError(''); try { const result = await managementApi.notifyRules({ pageNo: next, pageSize: 10, name: name || undefined, sceneCode }); setItems(result.list); setTotal(result.total); setPage(next) } catch (e) { setError(errorText(e, '业务通知规则加载失败')) } finally { setLoading(false) } }, [name, page, sceneCode])
  useEffect(() => { void Promise.allSettled([managementApi.notifyScenes().then(setScenes), managementApi.notifyTemplates().then(setTemplates), managementApi.users().then(setUsers)]).then(() => load(1)) }, []) // eslint-disable-line react-hooks/exhaustive-deps
  const currentSceneCode = Form.useWatch('sceneCode', form), currentScene = scenes.find(item => item.code === currentSceneCode), channel = Form.useWatch('channelCode', form)
  const open = async (row?: NotifyRule) => { const value = row?.id ? await managementApi.notifyRule(row.id) : { name: '', sceneCode: '', channelCode: 'in_app', recipientRoles: [], specifiedUserIds: [], actionType: 'message_detail', status: 0 } as NotifyRule; setEditing(value); form.setFieldsValue(value) }
  const save = async () => { try { const values = await form.validateFields(); if (!values.recipientRoles.length && !values.specifiedUserIds.length) return message.warning('至少选择一个事件角色或指定用户'); await managementApi.saveNotifyRule({ ...values, id: editing?.id }); message.success(editing?.id ? '规则已更新' : '规则已创建'); setEditing(null); await load() } catch (e) { if (e instanceof Error) message.error(e.message) } }
  const remove = async (id: number) => { try { await managementApi.deleteNotifyRule(id); message.success('规则已删除'); await load() } catch (e) { message.error(errorText(e, '删除失败')) } }
  const toggle = async (row: NotifyRule, checked: boolean) => { try { await managementApi.updateNotifyRuleStatus(row.id!, checked ? 0 : 1); await load() } catch (e) { message.error(errorText(e, '状态更新失败')) } }
  const sceneName = (code: string) => scenes.find(item => item.code === code)?.name || code
  return <section className="workspace-page management-page">{pageTitle('业务通知规则', '配置通知场景、接收人、模板与点击动作', hasPermission(permissions, 'system:notify-rule:create') ? <Button type="primary" icon={<PlusOutlined/>} onClick={() => void open()}>新增规则</Button> : undefined)}<Space wrap className="management-filters"><Input value={name} onChange={e => setName(e.target.value)} placeholder="规则名称"/><Select allowClear value={sceneCode} onChange={setSceneCode} placeholder="业务场景" options={scenes.map(item => ({ value: item.code, label: item.name }))}/><Button type="primary" onClick={() => void load(1)}>查询</Button></Space>{error && <LoadError error={error} retry={() => void load()}/>}<Table rowKey="id" loading={loading} dataSource={items} pagination={{ current: page, total, pageSize: 10, onChange: next => void load(next) }} columns={[{ title: '规则名称', dataIndex: 'name' }, { title: '业务场景', dataIndex: 'sceneCode', render: sceneName }, { title: '通知渠道', dataIndex: 'channelCode' }, { title: '接收角色', dataIndex: 'recipientRoles', render: value => value.join('、') || '-' }, { title: '状态', render: (_, row) => <Switch checked={row.status === 0} disabled={!hasPermission(permissions, 'system:notify-rule:update')} onChange={checked => void toggle(row, checked)}/> }, { title: '操作', render: (_, row) => <Space>{hasPermission(permissions, 'system:notify-rule:update') && <Button type="link" icon={<EditOutlined/>} onClick={() => void open(row)}>编辑</Button>}{hasPermission(permissions, 'system:notify-rule:delete') && <Popconfirm title="确认删除该规则？" onConfirm={() => void remove(row.id!)}><Button type="link" danger icon={<DeleteOutlined/>}>删除</Button></Popconfirm>}</Space> }]} scroll={{ x: 900 }}/>
    <Modal width={720} title={editing?.id ? '编辑通知规则' : '新增通知规则'} open={Boolean(editing)} onCancel={() => setEditing(null)} onOk={() => void save()}><Form form={form} layout="vertical"><Form.Item name="name" label="规则名称" rules={[{ required: true }]}><Input/></Form.Item><Form.Item name="sceneCode" label="业务场景" rules={[{ required: true }]}><Select options={scenes.map(item => ({ value: item.code, label: item.name }))} onChange={() => form.setFieldsValue({ templateId: undefined, recipientRoles: [] })}/></Form.Item><Form.Item name="channelCode" label="通知渠道" rules={[{ required: true }]}><Select options={[{ value: 'in_app', label: '站内信（含实时提醒）' }, { value: 'wecom', label: '企业微信' }]}/></Form.Item><Form.Item name="templateId" label="消息模板" rules={[{ required: true }]}><Select options={templates.filter(item => item.sceneCode === currentSceneCode && (!item.channelCode || item.channelCode === channel || (channel === 'websocket' && item.channelCode === 'in_app'))).map(item => ({ value: item.id, label: item.name }))}/></Form.Item><Form.Item name="recipientRoles" label="事件角色"><Select mode="multiple" options={(currentScene?.recipientRoles || []).map(item => ({ value: item.code, label: item.name }))}/></Form.Item><Form.Item name="specifiedUserIds" label="指定用户"><Select showSearch optionFilterProp="label" mode="multiple" options={users.map(item => ({ value: item.id, label: item.nickname }))}/></Form.Item><Form.Item name="actionType" label="点击动作" rules={[{ required: true }]}><Radio.Group options={(currentScene?.allowedActions || ['none']).map(value => ({ value, label: value === 'none' ? '无操作' : value === 'message_detail' ? '消息详情' : '业务详情' }))}/></Form.Item>{currentScene?.timed && <><Form.Item name="timingStage" label="提醒阶段"><Radio.Group options={[{ value: 'advance', label: '提前' }, { value: 'due', label: '到期' }, { value: 'overdue', label: '逾期' }]}/></Form.Item><Form.Item name="timingOffsetMinutes" label="偏移分钟"><InputNumber min={0} max={10080}/></Form.Item></>}<Form.Item name="status" label="状态"><Radio.Group options={[{ value: 0, label: '启用' }, { value: 1, label: '停用' }]}/></Form.Item></Form></Modal>
  </section>
}
