import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { expectSourceNotToContainTokens, expectSourceToContainTokens, sourceHasCall } from '../test/sourceGuard'

describe('director and operator My Students', () => {
  const page = readFileSync('src/pages/MediaStudentsPage.tsx', 'utf8')
  const configPage = readFileSync('src/pages/DirectorConfigPages.tsx', 'utf8')
  const api = readFileSync('src/services/api.ts', 'utf8')
  const materialApi = readFileSync('src/services/materialApi.ts', 'utf8')
  const autoSave = readFileSync('src/services/directorAutoSave.ts', 'utf8')
  const style = readFileSync('src/styles/pages/media-students.css', 'utf8')

  it('uses the workbench master-detail recipe', () => {
    expect(page).toContain('workspace-page media-students-page')
    expect(page).toContain('media-students-inbox-layout')
    expect(page).toContain('<aside className="media-students-list-pane">')
    expect(page).toContain('<main className="media-students-detail-pane">')
    expect(style).toContain('grid-template-columns: var(--crm-list-pane-w) minmax(0, 1fr)')
    expect(style).toContain('grid-template-columns: repeat(12, minmax(0, 1fr))')
  })

  it('does not render the removed implementation note', () => {
    expect(page).not.toContain('仅展示分配给当前编导')
    expect(page).not.toContain('不包含学习规划师')
    expect(page).not.toContain('我的学员（编导）')
  })

  it('loads the director-owned business detail projection', () => {
    expect(page).toContain('api.mediaStudents.get(personId)')
    expect(page).toContain('api.studentContactContext(service.serviceRelationId)')
    expect(page).toContain('<LeadDetailOverview')
    expect(page).toContain('<StudentDetail')
    expect(page).toContain('student={detail.student}')
    expect(page).toContain('overviewContent={mediaOverview}')
    expect(page).not.toContain('当前课程服务尚未关联客资详情')
    expect(page).toContain('service.serviceRelationId')
    expect(page).toContain("label: '账号'")
    expect(page).toContain('账号定位卡')
    expect(page).toContain('内容生产历史')
    expect(page).not.toContain("label: '学员信息'")
    expect(page).not.toContain('沟通记录')
    expect(page).not.toContain('新增沟通记录')
    expect(page).not.toContain('客资编号')
    expect(page).not.toContain('api.managedLead')
    expect(page).not.toContain('leadId')
    expectSourceToContainTokens(page, "x.personNo || '暂无学员编号'")
    expect(page).toContain("operationTimeline.filter(item => item.type !== 'talk')")
    expectSourceToContainTokens(page, "value === 'positioning'")
    expectSourceToContainTokens(page, "value === 'positioning' || value === 'maintenance'")
    expect(page).toContain("useState(normalizeMediaStudentTab(params.get('tab')))")
    expect(page).toContain("label: '学习规划师', value: selectedService.ownerUserName")
    expect(page).toContain('mainBeforeColumns')
    expect(page).toContain('最新内容')
    expect(page).toContain('操作时间线')
    expect(page).toContain('studentTaskLine')
    expect(page).toContain('selectedAccount?.taskLine')
    expect(page).not.toContain('最近联系')
    expect(page).not.toContain('客资流转')
    expect(page).toContain('待处理')
    expect(page).toContain("directorContext?.availableActions.filter(action => ['DIRECTOR_PRECHECK', 'DIRECTOR_INTERVIEW', 'ASSIGN_OPERATOR'].includes(action))")
  })

  it('refreshes the selected student when a notification reuses the current route', () => {
    expect(page).toContain('const initialLocationKey = useRef(location.key)')
    expectSourceToContainTokens(page, 'if (location.key !== initialLocationKey.current) void loadPage(1')
  })

  it('keeps account maintenance in the account context instead of a student-level tab', () => {
    expect(page).toContain("const MEDIA_STUDENT_TABS = new Set(['overview', 'accounts', 'content'])")
    expect(page).not.toContain("key: 'maintenance', label: '状态维护'")
    expect(page).toContain("selectedAccount.availableActions.includes('MAINTAIN_ACCOUNT')")
    expect(page).toContain('<dt>当下状态</dt><dd>{x.currentStatusLabelSnapshot')
    expectSourceToContainTokens(page, 'initiallyEditing={maintenanceEditorAccountId === selectedAccount.id}')
    expect(page).toContain('<AccountMaintenancePanel key={`${selectedAccount.id}')
  })

  it('presents account selection and detail as a responsive workspace', () => {
    expect(page).toContain('className="media-account-grid"')
    expect(page).toContain('className={`media-account-card${selected ? \' active\' : \'\'}`}')
    expect(page).toContain('className="media-account-card-select" aria-pressed={selected}')
    expect(page).toContain('className="media-account-workspace-shell"')
    expect(page).toContain('className="media-account-workspace"')
    expect(page).toContain('className="media-account-context-bar"')
    expect(page).toContain('className="media-students-card media-account-positioning"')
    expect(style).toContain('grid-template-columns: repeat(2, minmax(0, 1fr))')
    expect(style).toContain('grid-template-columns: minmax(0, 7fr) minmax(320px, 5fr)')
    expect(style).toContain('@container (max-width: 899px)')
    expect(style).toContain('.media-account-workspace { grid-template-columns: minmax(0, 1fr); }')
  })

  it('autosaves only server-backed director business drafts', () => {
    expect(page).toContain('const AUTO_SAVE_DELAY_MS = 1500')
    expect(page).toContain('onValuesChange={scheduleAutoSave}')
    expectSourceToContainTokens(page, "dialog === 'precheck' || dialog === 'interview' || dialog === 'positioning'")
    expect(page).toContain('DirectorAutoSaveCoordinator')
    expect(page).toContain('stageDraftVersion.current = authoritativeVersion')
    expect(page).toContain('草稿已自动保存')
    expect(autoSave).toContain('草稿版本已变化，请重新加载后继续')
    expect(page).toContain('valuePropName="checked" label={label}')
    expectSourceNotToContainTokens(page, "if (field.type === 'checkbox') return null")
    expect(page).not.toContain('localStorage.setItem')
    expect(api).toContain('unwrap<PositioningCardDraftResult>')
  })

  it('shows optional versioned field remarks on every director form control', () => {
    expect(configPage).toContain('label="填写备注"')
    expect(configPage).toContain('maxLength={500} showCount')
    expect(page).toContain("const extra = field.description?.trim() ?")
    expect(page).toContain("whiteSpace: 'pre-wrap', overflowWrap: 'anywhere'")
    expect(page.match(/extra=\{extra\}/g)).toHaveLength(9)
    expectSourceToContainTokens(page, "dialog === 'positioning'")
    expectSourceToContainTokens(page, "dialog === 'interview'")
    expectSourceNotToContainTokens(page, 'fieldsSnapshot || []).filter(field => field.enabled).map(field => ({ key: field.key, label: field.title, description:')
  })

  it('uses the typed positioning student confirmation link API', () => {
    expect(page).toContain('api.positioningCard.generateStudentLink(row.id, row.version)')
    expect(api).toContain('generateStudentLink: async (id: number, version: number)')
    expect(api).toContain('unwrap<PositioningLinkResult>')
    expect(page).toContain('const positioningShareUrl = (sharePath: string)')
    expectSourceToContainTokens(page, "url.protocol !== 'http:' && url.protocol !== 'https:'")
    expect(page).not.toContain('`${window.location.origin}${result.sharePath}`')
  })

  it('creates a student-bound partner invitation behind the configured permission', () => {
    expectSourceToContainTokens(page, "hasPermission(permissions, 'zsjos:partner-invitation:create-student')")
    expect(page).toContain("form.setFieldsValue({ studentName: detail.student.name || '', studentMobile: detail.student.mobile || '' })")
    expect(page).toContain('partnerStudentInvitationApi.create({')
    expectSourceToContainTokens(page, 'studentPersonId: detail.student.personId')
    expect(materialApi).toContain("await http.post('/zsjos/partner-invitation/student/create', data)")
    expect(page).toContain('setStudentInvitation(invitation)')
    expect(page).toContain('navigator.clipboard.writeText(studentInvitation.inviteCode)')
    expect(page).toContain('formatTimestamp(studentInvitation?.expiresAt)')
    expect(page).toContain('姓名和手机号仅用于本次兼职账号注册，不会修改学员主体资料。')
    expect(page).toContain("label: '注册姓名', value: studentInvitation?.name")
    expect(page).toContain("label: '注册手机号', value: studentInvitation?.mobile")
  })

  it('separates the effective positioning from the latest review round', () => {
    expect(api).toMatch(/\blatestRound\s*:\s*boolean\s*;/)
    expect(api).toMatch(/\beffective\s*:\s*boolean\s*;/)
    expect(api).toMatch(/\bcurrent\s*:\s*boolean\s*;/)
    expect(page).toContain('item.effective')
    expectSourceToContainTokens(page, 'item.latestRound && !item.effective')
    expect(page).toContain('当前生效定位')
    expect(page).toContain('当前审核轮次')
    expect(page).toContain('历史提交')
    expect(sourceHasCall(page, 'selectedAccountEffective.availableActions.includes')).toBe(true)
    expect(page).toContain('START_POSITIONING_REVISION')
    expect(page).toContain('api.positioningCard.startRevision(row.id, row.version)')
    expect(api).not.toContain('/confirm-trial')
    expect(api).not.toContain('positioning-card/${id}/archive')
    expect(page).not.toContain('试运行结束日期')
    expect(page).not.toContain('确认试跑')
  })

  it('keeps positioning view and edit actions in the card heading without duplicates', () => {
    expectSourceToContainTokens(page, 'const selectedPositioningView = selectedAccountLatest || selectedAccountEffective')
    expect(page).toContain('<Button size="small" onClick={() => void viewPositioning(selectedPositioningView.id)}>查看定位卡</Button>')
    expect(page).toContain("row.availableActions?.filter(action => action !== 'START_POSITIONING_REVISION')")
    expect(page.match(/\{selectedPositioningButtonVisible &&/g)).toHaveLength(1)
    expect(page).not.toContain('icon={<EyeOutlined />}')
  })

  it('uses only the interview appointment time in the director flow', () => {
    expect(page.match(/name="interviewAt"/g)).toHaveLength(1)
    expect(page).toContain('name="interviewAt" label="访谈预约时间"')
    expect(page).not.toContain('下次联系时间')
  })

  it('imports only server-projected submitted positioning snapshots', () => {
    expect(api).toContain('unwrap<PositioningCardImportSource[]>')
    expect(page).toContain('导入现有定位卡')
    expect(page).toContain('暂无可导入的已提交定位卡')
    expect(page).toContain('覆盖当前定位卡草稿？')
    expect(page).toContain('targetDraftId: currentDraft?.id')
    expect(page).toContain('result.skippedFieldKeys.length')
  })

  it('offers local JSON import independently from positioning query permission', () => {
    expect(page).toContain("from '../services/positioningJsonImport'")
    expect(page).toContain('导入 JSON')
    expect(page).toContain('仅按当前模板字段 key 匹配')
    expect(page).toContain('确认导入并保存')
    expectSourceToContainTokens(page, "dialog === 'positioning' && <><div className=\"media-students-positioning-toolbar\"")
    expectSourceToContainTokens(page, "hasPermission(permissions, 'zsjos:positioning-card:query') && <Button icon={<ImportOutlined />}")
    expect(page).toContain("await autoSaveCoordinator.current!.saveNow(draftSaveTask())")
  })

})
