import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('director and operator My Students', () => {
  const page = readFileSync('src/pages/MediaStudentsPage.tsx', 'utf8')
  const api = readFileSync('src/services/api.ts', 'utf8')
  const autoSave = readFileSync('src/services/directorAutoSave.ts', 'utf8')
  const style = readFileSync('src/styles/pages/media-students.css', 'utf8')

  it('uses the workbench master-detail recipe', () => {
    expect(page).toContain('workspace-page media-students-page')
    expect(page).toContain('media-students-inbox-layout')
    expect(page).toContain('<aside className="media-students-list-pane">')
    expect(page).toContain('<main className="media-students-detail-pane">')
    expect(style).toContain('grid-template-columns: var(--crm-list-pane-w) minmax(0, 1fr)')
    expect(style).toContain('grid-template-columns: repeat(12, minmax(0, 1fr))')
  })

  it('does not render the removed implementation note', () => {
    expect(page).not.toContain('仅展示分配给当前编导')
    expect(page).not.toContain('不包含学习规划师')
    expect(page).not.toContain('我的学员（编导）')
  })

  it('loads the director-owned business detail projection', () => {
    expect(page).toContain('api.mediaStudents.get(personId)')
    expect(page).toContain('api.studentContactContext(service.serviceRelationId)')
    expect(page).toContain('<LeadDetailOverview')
    expect(page).toContain('<StudentDetail')
    expect(page).toContain('student={detail.student}')
    expect(page).toContain('overviewContent={mediaOverview}')
    expect(page).not.toContain('当前课程服务尚未关联客资详情')
    expect(page).toContain('service.serviceRelationId')
    expect(page).toContain("label: '账号'")
    expect(page).toContain('账号定位卡')
    expect(page).toContain('内容生产历史')
    expect(page).not.toContain("label: '学员信息'")
    expect(page).not.toContain('沟通记录')
    expect(page).not.toContain('新增沟通记录')
    expect(page).not.toContain('客资编号')
    expect(page).not.toContain('api.managedLead')
    expect(page).not.toContain('leadId')
    expect(page).toContain("x.personNo || '暂无学员编号'")
    expect(page).toContain("operationTimeline.filter(item => item.type !== 'talk')")
    expect(page).toContain("value === 'positioning'")
    expect(page).toContain("value === 'positioning' || value === 'maintenance'")
    expect(page).toContain("useState(normalizeMediaStudentTab(params.get('tab')))")
    expect(page).toContain("label: '学习规划师', value: selectedService.ownerUserName")
    expect(page).toContain('mainBeforeColumns')
    expect(page).toContain('最新内容')
    expect(page).toContain('操作时间线')
    expect(page).toContain('studentTaskLine')
    expect(page).toContain('selectedAccount?.taskLine')
    expect(page).not.toContain('最近联系')
    expect(page).not.toContain('客资流转')
    expect(page).toContain('待处理')
    expect(page).toContain("directorContext?.availableActions.filter(action => ['DIRECTOR_PRECHECK', 'DIRECTOR_INTERVIEW', 'ASSIGN_OPERATOR'].includes(action))")
  })

  it('refreshes the selected student when a notification reuses the current route', () => {
    expect(page).toContain('const initialLocationKey = useRef(location.key)')
    expect(page).toContain('if (location.key !== initialLocationKey.current) void loadPage(1')
  })

  it('keeps account maintenance in the account context instead of a student-level tab', () => {
    expect(page).toContain("const MEDIA_STUDENT_TABS = new Set(['overview', 'accounts', 'content'])")
    expect(page).not.toContain("key: 'maintenance', label: '状态维护'")
    expect(page).toContain("x.availableActions.includes('MAINTAIN_ACCOUNT')")
    expect(page).toContain("x.availableActions.includes('VIEW_ACCOUNT_HISTORY')")
    expect(page).toContain('状态：{x.currentStatusLabelSnapshot')
    expect(page).toContain('selectAccount(x.id, canMaintainAccount)')
    expect(page).toContain('initiallyEditing={maintenanceEditorAccountId === selectedAccount.id}')
    expect(page).toContain('{selectedAccount && <AccountMaintenancePanel')
  })

  it('autosaves only server-backed director business drafts', () => {
    expect(page).toContain('const AUTO_SAVE_DELAY_MS = 1500')
    expect(page).toContain('onValuesChange={scheduleAutoSave}')
    expect(page).toContain("dialog === 'precheck' || dialog === 'interview' || dialog === 'positioning'")
    expect(page).toContain('DirectorAutoSaveCoordinator')
    expect(page).toContain('stageDraftVersion.current = authoritativeVersion')
    expect(page).toContain('草稿已自动保存')
    expect(autoSave).toContain('草稿版本已变化，请重新加载后继续')
    expect(page).toContain('valuePropName="checked" label={label}')
    expect(page).not.toContain("if (field.type === 'checkbox') return null")
    expect(page).not.toContain('localStorage.setItem')
    expect(api).toContain("http.post('/zsjos/positioning-card/draft'")
    expect(api).toContain('http.put(`/zsjos/positioning-card/draft/${id}`')
    expect(api).toContain('unwrap<PositioningCardDraftResult>')
  })

  it('uses the typed positioning student confirmation link API', () => {
    expect(page).toContain('api.positioningCard.generateStudentLink(row.id, row.version)')
    expect(api).toContain('generateStudentLink: async (id: number, version: number)')
    expect(api).toContain('http.post(`/zsjos/positioning-card/${id}/student-link`, null, { params: { version } })')
    expect(api).toContain('unwrap<PositioningLinkResult>')
    expect(page).toContain('const positioningShareUrl = (sharePath: string)')
    expect(page).toContain("url.protocol !== 'http:' && url.protocol !== 'https:'")
    expect(page).not.toContain('`${window.location.origin}${result.sharePath}`')
  })

  it('separates the effective positioning from the latest review round', () => {
    expect(api).toContain('latestRound: boolean; effective: boolean; current: boolean')
    expect(page).toContain('item.effective')
    expect(page).toContain('item.latestRound && !item.effective')
    expect(page).toContain('当前生效定位')
    expect(page).toContain('当前审核轮次')
    expect(page).toContain('历史提交')
    expect(page).toContain("accountEffective?.availableActions.includes('START_POSITIONING_REVISION')")
    expect(page).toContain('api.positioningCard.startRevision(row.id, row.version)')
    expect(api).toContain('`/zsjos/positioning-card/${id}/start-revision`')
    expect(api).not.toContain('/confirm-trial')
    expect(api).not.toContain('positioning-card/${id}/archive')
    expect(page).not.toContain('试运行结束日期')
    expect(page).not.toContain('确认试跑')
  })

  it('imports only server-projected submitted positioning snapshots', () => {
    expect(api).toContain("http.get('/zsjos/positioning-card/import-sources'")
    expect(api).toContain("http.post('/zsjos/positioning-card/import'")
    expect(api).toContain('unwrap<PositioningCardImportSource[]>')
    expect(page).toContain('导入现有定位卡')
    expect(page).toContain('暂无可导入的已提交定位卡')
    expect(page).toContain('覆盖当前定位卡草稿？')
    expect(page).toContain('targetDraftId: currentDraft?.id')
    expect(page).toContain('result.skippedFieldKeys.length')
  })
})
