import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('student positioning interview and account workspace boundary', () => {
  const page = readFileSync('src/pages/MediaStudentsPage.tsx', 'utf8')
  const dialog = readFileSync('src/components/PositioningInterviewDialog.tsx', 'utf8')
  it('preserves the original shell and keeps screenshot-only account sheets as peer tabs', () => {
    for (const restored of ['ProductionTicketPositioningCard', 'api.positioningCard', 'AccountMaintenancePanel', 'partnerStudentInvitationApi', 'extraTabs={tabs}', 'mediaAccountTabKey(account.id)']) expect(page).toContain(restored)
    expect(page).toContain("from '../components/StudentDetail'")
    expect(page).toContain('NameAvatar')
    expect(page).toContain('lead-profile-fields')
    expect(page).toContain('lead-profile-meta')
    expect(page).toContain('OverflowToolbar')
    expect(page).toContain('StudentPlannerOperations')
    expect(page).toContain("ASSIGN_OPERATOR: '指派运营'")
    expect(page).toContain("studentCollaboratorCandidates(selectedServiceId, 'operator')")
    expect(page).toContain('studentAssignCollaborator(selectedService.serviceRelationId')
    expect(page).toContain('media-students-item-copy')
    expect(page).toContain("label: '新增账号'")
    expect(page).toContain("'开通兼职账号'")
    expect(page).not.toContain("key: 'accounts'")
    expect(page).not.toContain("key: 'content', label: '内容生产历史'")
    expect(page).not.toContain('contextHeader={serviceContextHeader}')
    expect(page).not.toContain('media-students-list-item')
    expect(page).not.toContain('media-account-positioning')
    expect(page).not.toContain('内容生产历史')
    expect(page).not.toContain('CREATE_CONTENT_${account.id}')
  })
  it('uses server-projected operations and preserves notification navigation', () => {
    expect(page).toContain('directorContext?.availableActions')
    expect(page).toContain('const overviewToolbarActions = [...plannerActions, ...directorActions, ...contentApprovalAction, ...overviewAccountActions]')
    expect(page).toContain('overviewToolbarActions.length > 0 && <OverflowToolbar actions={overviewToolbarActions} />')
    expect(page).toContain('location.key')
    expect(page).toContain("params.get('personId')")
    expect(page).toContain("params.get('accountId')")
    expect(page).toContain("params.get('contentId')")
    expect(page).toContain("params.get('positioningCardId')")
    expect(page).not.toContain('roleName')
  })
  it('renders server-published outlines without a local field catalog', () => {
    expect(dialog).toContain('context.fields.filter')
    expect(dialog).toContain('Object.entries(context.statusOptions)')
    expect(dialog).toContain('field.interviewNote')
    expect(dialog).not.toContain('__status')
    expect(dialog).toContain("context?.status === 'completed'")
  })
})
