import { Alert, Button, Drawer, Form, Input, InputNumber, Modal, Select, Space, Tag, Typography, message } from 'antd'
import { useEffect, useState } from 'react'
import BusinessTable from '../components/BusinessTable'
import { performanceApi, money, periodRange, dateText, type Target, type TargetEdit, type OrgNode } from '../services/salesPerformance'
import { PerformanceShell, Panel, Resource, useResource, Refresh } from './performance/PerformanceShared'
function OrganizationConfig({onSaved}:{onSaved:()=>void}){
 const [open,setOpen]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');const [form]=Form.useForm<{kind:string;deptId:number;centerId:number}>()
 const candidates=useResource(()=>open?performanceApi.candidates():Promise.resolve([]),[open]);const orgs=useResource(()=>open?performanceApi.organizations():Promise.resolve([]),[open]);const kind=Form.useWatch('kind',form)
 async function save(){try{const values=await form.validateFields();setSaving(true);setError('');await performanceApi.saveOrg({...values,centerId:values.kind==='CENTER'?values.deptId:values.centerId});message.success('组织关联已保存');orgs.reload();onSaved()}catch(e){setError(e instanceof Error?e.message:'请选择组织并重试')}finally{setSaving(false)}}
 return <><Button onClick={()=>setOpen(true)}>销售组织关联</Button><Modal title="关联销售中心与部门" open={open} onCancel={()=>setOpen(false)} onOk={save} confirmLoading={saving}><p>选择系统已有组织，中心先关联自身，再添加其下属销售部门。</p><Resource state={candidates}><Form form={form} layout="vertical" initialValues={{kind:'CENTER'}}><Form.Item name="kind" label="关联用途" rules={[{required:true}]}><Select options={[{value:'CENTER',label:'销售中心'},{value:'DEPT',label:'销售部门'}]}/></Form.Item><Form.Item name="deptId" label="系统组织" rules={[{required:true}]}><Select showSearch optionFilterProp="label" options={candidates.data?.map(n=>({value:n.scopeId,label:n.title}))}/></Form.Item>{kind==='DEPT'&&<Form.Item name="centerId" label="所属销售中心" rules={[{required:true}]}><Select options={orgs.data?.filter(x=>x.kind==='CENTER').map(x=>({value:x.centerId,label:candidates.data?.find(n=>n.scopeId===x.centerId)?.title??'历史组织'}))}/></Form.Item>}</Form></Resource>{error&&<Alert type="error" title={error}/>}<Resource state={orgs}><Space wrap>{orgs.data?.map(x=><Tag key={x.deptId}>{candidates.data?.find(n=>n.scopeId===x.deptId)?.title} · {x.kind==='CENTER'?'中心':'部门'}</Tag>)}</Space></Resource></Modal></>
}
function revisionSummary(json:string){if(!json)return '未设置';try{const row=JSON.parse(json) as {floorAmount?:number;sprintAmount?:number;manual?:boolean};return row.manual?`保底 ${money(row.floorAmount)} / 冲刺 ${money(row.sprintAmount)}`:'自动汇总'}catch{return '历史记录格式不可读'}}
function belongsToSelection(row:Target,selected:OrgNode,nodes:OrgNode[]) {
 let node=nodes.find(n=>n.scopeType===row.scopeType&&n.scopeId===row.scopeId)
 const seen=new Set<string>()
 while(node&&!seen.has(node.key)){if(node.key===selected.key)return true;seen.add(node.key);node=nodes.find(n=>n.key===node?.parentKey)}
 return false
}
export default function SalesPerformanceTargetPage({permissions}:{permissions:string[]}) {
 const [period,setPeriod]=useState('month'),[start,setStart]=useState(periodRange('month').start),[edits,setEdits]=useState<Record<string,TargetEdit>>({}),[reason,setReason]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState(''),[generation,setGeneration]=useState(0),[historyId,setHistoryId]=useState<number>()
 const rows=useResource(signal=>performanceApi.targets(period,start,signal),[period,start,generation]);const history=useResource(()=>historyId?performanceApi.revisions(historyId):Promise.resolve([]),[historyId]);const editable=permissions.includes('zsjos:sales-performance-target:update')
 useEffect(()=>{if(!rows.data)return;const allowed=new Set(rows.data.map(row=>`${row.scopeType}:${row.scopeId}`));setEdits(previous=>{const entries=Object.entries(previous).filter(([key])=>allowed.has(key));return entries.length===Object.keys(previous).length?previous:Object.fromEntries(entries)})},[rows.data])
 const key=(row:Target)=>row.scopeType+':'+row.scopeId
 function edit(row:Target,field:'floorAmount'|'sprintAmount',value:number|null){setEdits(old=>{const current=old[key(row)]??{scopeType:row.scopeType,scopeId:row.scopeId,id:row.id,periodType:period,periodStart:start,version:row.version,floorAmount:Number(row.floorAmount??0),sprintAmount:Number(row.sprintAmount??0),reason};return {...old,[key(row)]:{...current,[field]:value??0,restoreAutomatic:false}}})}

 async function save(items:TargetEdit[]){if(!reason.trim()){setError('请填写调整原因，历史修订也会保存该说明');return}try{setSaving(true);setError('');await performanceApi.save(items.map(x=>({...x,reason})));setEdits({});setReason('');setGeneration(x=>x+1);message.success('目标已保存')}catch(e){setError(e instanceof Error?e.message:'保存失败，请重试')}finally{setSaving(false)}}
 function changePeriod(value:string,date:string){if(!date)return;const normalized=new Date(date+'T12:00:00');if(value==='week')normalized.setDate(normalized.getDate()-(normalized.getDay()+6)%7);else normalized.setDate(1);date=dateText(normalized);if(Object.keys(edits).length){Modal.confirm({title:'切换周期将放弃未保存修改',onOk:()=>{setEdits({});setPeriod(value);setStart(date)}})}else{setPeriod(value);setStart(date)}}
 const columns=[{title:'对象',dataIndex:'name',width:180},{title:'保底目标',key:'floor',width:160,render:(_:unknown,row:Target)=>editable?<InputNumber min={0} precision={2} value={edits[key(row)]?.floorAmount??row.floorAmount} onChange={v=>edit(row,'floorAmount',v)} aria-label={`${row.name}保底目标`}/>:money(row.floorAmount)},{title:'冲刺目标',key:'sprint',width:160,render:(_:unknown,row:Target)=>editable?<InputNumber min={0} precision={2} value={edits[key(row)]?.sprintAmount??row.sprintAmount} onChange={v=>edit(row,'sprintAmount',v)} aria-label={`${row.name}冲刺目标`}/>:money(row.sprintAmount)},{title:'自动汇总 / 状态',key:'state',width:250,render:(_:unknown,row:Target)=><><div>{row.scopeType==='USER'?'个人录入':`${money(row.automaticFloor)} / ${money(row.automaticSprint)}`}</div><Tag color={row.complete?'green':'orange'}>{row.complete?'完整':`缺少${row.missing}项目标`}</Tag>{row.manual&&<Tag>人工值</Tag>}{row.manual&&row.scopeType!=='USER'&&(Number(row.floorAmount)!==Number(row.automaticFloor)||Number(row.sprintAmount)!==Number(row.automaticSprint))&&<div>与下级汇总存在差异</div>}</>},{title:'操作',key:'action',width:180,render:(_:unknown,row:Target)=><Space>{row.id&&<Button type="link" onClick={()=>setHistoryId(row.id)}>修订历史</Button>}{editable&&row.manual&&row.scopeType!=='USER'&&<Button type="link" onClick={()=>save([{scopeType:row.scopeType,scopeId:row.scopeId,id:row.id,periodType:period,periodStart:start,reason,version:row.version,restoreAutomatic:true}])}>恢复汇总</Button>}</Space>}]
 return <><div className="performance-heading" style={{padding:12}}><Typography.Title level={4}>销售业绩设置</Typography.Title>{permissions.includes('zsjos:sales-performance-target:configure')&&<OrganizationConfig onSaved={()=>setGeneration(x=>x+1)}/>}</div><Space wrap style={{padding:12}}><Select value={period} onChange={v=>changePeriod(v,periodRange(v).start)} options={[{value:'week',label:'周目标'},{value:'month',label:'月目标'}]}/><Input aria-label="目标周期起点" type="date" value={start} onChange={e=>changePeriod(period,e.target.value)}/><span>周目标从周一开始，月目标从每月1日开始</span></Space>
 <PerformanceShell key={generation} targets>{(scope,node,_reload,treeNodes)=><Panel title={`${node.title} · ${start} 起`} extra={<Refresh onClick={()=>{rows.reload();_reload()}}/>}><Alert type="info" title="周/月独立设置，季度/年度汇总月目标。人工调整后下级变化不会覆盖生效值。仅展示启用人员，已保存的历史人员目标仍计入汇总。"/><Resource state={rows}><BusinessTable<Target> tableKey="performance-targets" rowKey={key} dataSource={(rows.data??[]).filter(r=>belongsToSelection(r,node,treeNodes))} search={false} columns={columns} pagination={{pageSize:20}}/></Resource>{editable&&<Space direction="vertical" style={{width:'100%'}}><Input.TextArea value={reason} onChange={e=>setReason(e.target.value)} maxLength={500} placeholder="填写调整原因（必填，将保留历史修订记录）"/><Button type="primary" loading={saving} disabled={!Object.keys(edits).length} onClick={()=>save(Object.values(edits))}>保存 {Object.keys(edits).length} 项修改</Button></Space>}{error&&<Alert type="error" title={error}/>}</Panel>}</PerformanceShell>
 <Drawer title="目标修订历史" width="min(760px,100vw)" open={!!historyId} onClose={()=>setHistoryId(undefined)}><Resource state={history}>{history.data?.map(x=><Panel key={x.id} title={x.at}><p>{x.operatorName} · {x.reason}</p><p>修订前：{revisionSummary(x.before)}</p><p>修订后：{revisionSummary(x.after)}</p></Panel>)}</Resource></Drawer></>
}
