import { useCallback, useEffect, useMemo, useState } from 'react'
import { Alert, Avatar, Button, Drawer, Empty, Input, Modal, Skeleton, Space, Tabs, Tag, Typography, message } from 'antd'
import { CheckOutlined, CloseOutlined, ReloadOutlined, SearchOutlined } from '@ant-design/icons'
import { api, type SalesOrder, type SalesOrderSupervisorInboxItem } from '../services/api'
import SalesOrderDetailCards, { SALES_ORDER_TASK_LABELS } from '../components/SalesOrderDetailCards'
import { formatTimestamp } from '../services/time'
import { useSubmissionGuard } from '../services/submissionGuard'

const STATUS_LABELS = { pending: '待确认', confirmed: '已确认', rejected: '不确认', cancelled: '已取消' } as const
const STATUS_COLORS = { pending: 'gold', confirmed: 'green', rejected: 'red', cancelled: 'default' } as const

export default function SalesOrderSupervisorConfirmationPage() {
  const [handled, setHandled] = useState(false), [keyword, setKeyword] = useState('')
  const [items, setItems] = useState<SalesOrderSupervisorInboxItem[]>([]), [selectedId, setSelectedId] = useState<number>()
  const [detail, setDetail] = useState<SalesOrder>(), [loading, setLoading] = useState(false), [detailLoading, setDetailLoading] = useState(false)
  const [error, setError] = useState(''), [detailError, setDetailError] = useState(''), [drawerOpen, setDrawerOpen] = useState(false)
  const [decision, setDecision] = useState<'confirm' | 'reject'>(), [reason, setReason] = useState('')
  const { submitting, run, resetIntent } = useSubmissionGuard()
  const load = useCallback(async () => { setLoading(true); setError(''); try { const result = await api.salesOrderSupervisorInbox({ pageNo: 1, pageSize: 100, handled, keyword: keyword.trim() || undefined }); setItems(result.list); setSelectedId(current => current && result.list.some(item => item.id === current) ? current : result.list[0]?.id) } catch (loadError) { setError(loadError instanceof Error ? loadError.message : '主管确认列表加载失败') } finally { setLoading(false) } }, [handled, keyword])
  useEffect(() => { void load() }, [load])
  const selected = useMemo(() => items.find(item => item.id === selectedId), [items, selectedId])
  useEffect(() => { if (!selected) { setDetail(undefined); return } setDetailLoading(true); setDetailError(''); void api.salesOrder(selected.orderId).then(setDetail).catch(loadError => { setDetail(undefined); setDetailError(loadError instanceof Error ? loadError.message : '订单详情加载失败') }).finally(() => setDetailLoading(false)) }, [selected])
  const submit = async () => { if (!selected || !decision || !reason.trim()) { message.warning('请填写主管意见'); return } const action = decision; await run(async ({ complete, idempotencyKey }) => { await api.decideSalesOrderSupervisor(selected.orderId, action, { confirmationId: selected.id, taskId: selected.taskId, reason: reason.trim(), approvalRoundId: selected.approvalRoundId, orderVersion: selected.orderVersion, roundVersion: selected.roundVersion, confirmationVersion: selected.version, idempotencyKey }); complete(); setDecision(undefined); setReason(''); message.success(action === 'confirm' ? '已确认，原审批中心可继续处理' : '已不确认，订单退回销售补正'); await load() }).catch(saveError => message.error(saveError instanceof Error ? saveError.message : '主管确认提交失败')) }
  const detailContent = detailLoading ? <Skeleton active paragraph={{ rows: 10 }}/> : detailError ? <Alert type="error" showIcon message={detailError}/> : selected && detail ? <div className="sales-order-supervisor-detail"><Alert type={selected.status === 'pending' ? 'info' : selected.status === 'rejected' ? 'error' : 'success'} showIcon message={`${selected.requesterUserName || '审批人'}申请主管确认`} description={<Space direction="vertical" size={2}><span>{selected.requestReason}</span><Typography.Text type="secondary">{formatTimestamp(selected.requestedAt)}</Typography.Text>{selected.decisionReason && <span>主管意见：{selected.decisionReason}</span>}</Space>}/>{selected.status === 'pending' && <Space wrap className="sales-order-supervisor-actions"><Button type="primary" icon={<CheckOutlined/>} onClick={() => { resetIntent(); setReason(''); setDecision('confirm') }}>确认</Button><Button danger icon={<CloseOutlined/>} onClick={() => { resetIntent(); setReason(''); setDecision('reject') }}>不确认</Button></Space>}<SalesOrderDetailCards order={detail} mode="approval-done"/></div> : <Empty description="选择一条主管确认"/>
  return <section className="workspace-page lead-management-page sales-order-supervisor-page"><header className="lead-inbox-filter-shell"><Tabs activeKey={handled ? 'done' : 'todo'} onChange={key => setHandled(key === 'done')} items={[{ key: 'todo', label: '待处理' }, { key: 'done', label: '已处理' }]}/></header><div className="lead-inbox-layout"><aside className="lead-inbox-list-pane"><div className="lead-inbox-toolbar"><Input allowClear prefix={<SearchOutlined/>} value={keyword} onChange={event => setKeyword(event.target.value)} placeholder="搜索订单号 / 学员姓名 / 手机号" suffix={<Button type="text" aria-label="刷新" icon={<ReloadOutlined/>} onClick={() => void load()}/>} /></div>{error && <Alert className="lead-list-error" type="error" showIcon message={error} action={<Button size="small" onClick={() => void load()}>重试</Button>}/>}<div className="lead-inbox-scroll">{loading ? <Skeleton active paragraph={{ rows: 6 }}/> : !items.length && !error ? <Empty description="暂无主管确认"/> : items.map(item => <button key={item.id} type="button" className={item.id === selectedId ? 'lead-inbox-item active' : 'lead-inbox-item'} onClick={() => { setSelectedId(item.id); if (window.matchMedia('(max-width: 768px)').matches) setDrawerOpen(true) }}><div className="lead-inbox-item-main"><Avatar>{item.studentName.slice(0, 1)}</Avatar><div className="lead-inbox-item-copy"><div className="lead-inbox-item-title"><strong>{item.studentName}</strong><Tag color={STATUS_COLORS[item.status]}>{STATUS_LABELS[item.status]}</Tag></div><span>{item.orderNo}</span><span>{SALES_ORDER_TASK_LABELS[item.taskDefinitionKey]}</span></div></div><div className="lead-inbox-item-meta"><span>{item.requesterUserName || '审批人'} · {formatTimestamp(item.requestedAt)}</span></div></button>)}</div></aside><main className="lead-inbox-detail-pane">{detailContent}</main></div><Drawer className="sales-order-mobile-drawer" open={drawerOpen} onClose={() => setDrawerOpen(false)} title="主管确认详情" width="100%">{detailContent}</Drawer><Modal title={decision === 'confirm' ? '确认订单事项' : '不确认并退回销售'} open={Boolean(decision)} onCancel={() => { setDecision(undefined); setReason(''); resetIntent() }} onOk={() => void submit()} confirmLoading={submitting} okText={decision === 'confirm' ? '确认' : '不确认'} okButtonProps={{ danger: decision === 'reject' }}><Typography.Text strong>主管意见</Typography.Text><Input.TextArea rows={5} maxLength={1000} showCount value={reason} onChange={event => setReason(event.target.value)} placeholder="填写主管意见（必填）"/></Modal></section>
}
