import { useEffect, useMemo, useState } from 'react'
import { Alert, Button, Card, DatePicker, Descriptions, Empty, Form, Input, InputNumber, List, Modal, Select, Space, Spin, Tabs, Tag, Timeline, Typography, message } from 'antd'
import { ReloadOutlined } from '@ant-design/icons'
import { useLocation } from 'react-router-dom'
import WorkOrderAttachmentPicker from '../components/WorkOrderAttachmentPicker'
import { APP_ROUTES } from '../constants'
import { workOrderApi, type WorkOrder, type WorkOrderAccount, type WorkOrderFile, type WorkOrderTemplate } from '../services/workOrderApi'
import { serializeWorkOrderDynamicValues } from '../services/workOrderForm'

const labels: Record<string, string> = { PENDING_ACCEPT: '待接单', AVAILABLE: '可认领', IN_PROGRESS: '处理中', PENDING_REVIEW: '待验收', COMPLETED: '已完成', REJECTED_INVALID: '已失效', WITHDRAWN: '已撤回', TERMINATED_UNQUALIFIED: '已终止' }
const views = [{ key: 'PENDING_ACCEPT', label: '待我接单' }, { key: 'PROCESSING', label: '处理中' }, { key: 'PENDING_REVIEW', label: '待我验收' }, { key: 'CREATED', label: '我发起的' }, { key: 'CLOSED', label: '已结束' }]
type Command = 'reject' | 'withdraw' | 'complete' | 'terminate' | 'return'
const commandLabels: Record<Command, string> = { reject: '拒绝接单', withdraw: '撤回工单', complete: '提交完成', terminate: '不合格并终止', return: '打回重做' }
const commandImpacts: Record<Command, string> = { reject: '拒单后将按模板策略失效或进入候选池，操作不可撤销。', withdraw: '撤回后工单立即终止流转，操作不可撤销。', complete: '提交后将交由发起人验收，当前轮处理内容不可修改。', terminate: '工单将以不合格结果终止，无法恢复。', return: '工单将退回原处理人并进入下一轮，操作不可撤销。' }

function DynamicAttachmentField({ value = [], onChange = () => undefined }: {
  value?: WorkOrderFile[]
  onChange?: (files: WorkOrderFile[]) => void
}) {
  return <WorkOrderAttachmentPicker value={value} onChange={onChange} />
}

export default function WorkOrderCenterPage() {
  const location = useLocation(); const [templates, setTemplates] = useState<WorkOrderTemplate[]>([]); const [orders, setOrders] = useState<WorkOrder[]>([]); const [selected, setSelected] = useState<WorkOrder>(); const [template, setTemplate] = useState<WorkOrderTemplate>(); const [candidates, setCandidates] = useState<Array<{ id: number; name: string }>>([]); const [departments, setDepartments] = useState<Array<{ id: number; name: string }>>([]); const [targetDepartments, setTargetDepartments] = useState<Array<{ id: number; name: string }>>([]); const [users, setUsers] = useState<Array<{ id: number; nickname: string }>>([]); const [accounts, setAccounts] = useState<WorkOrderAccount[]>([]); const [dictionaryOptions, setDictionaryOptions] = useState<Array<{ dictType: string; value: string; label: string }>>([]); const [assignmentType, setAssignmentType] = useState<'PERSON' | 'DEPARTMENT'>('PERSON'); const [requestFiles, setRequestFiles] = useState<WorkOrderFile[]>([]); const [resultFiles, setResultFiles] = useState<WorkOrderFile[]>([]); const [mineView, setMineView] = useState('PENDING_ACCEPT'); const [command, setCommand] = useState<Command>(); const [commandText, setCommandText] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [form] = Form.useForm()
  const createMode = location.pathname === APP_ROUTES.WORK_ORDER_CREATE; const availableMode = location.pathname === APP_ROUTES.WORK_ORDER_AVAILABLE
  const load = async () => { setLoading(true); setError(''); try { if (createMode) setTemplates((await workOrderApi.templates()).list || []); else setOrders((availableMode ? await workOrderApi.available() : await workOrderApi.mine(1, 20, mineView)).list || []) } catch (cause) { setError(cause instanceof Error ? cause.message : '工单加载失败') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [location.pathname, mineView])
  const run = async (fn: () => Promise<unknown>) => { await fn(); setSelected(undefined); setCommand(undefined); setCommandText(''); setResultFiles([]); message.success('操作已提交'); await load() }
  const confirm = (title: string, content: string, onOk: () => Promise<void>) => Modal.confirm({ title, content, okText: '确认操作', cancelText: '取消', onOk })
  const actions = useMemo(() => selected?.availableActions || [], [selected])
  const submitCommand = () => { if (!selected || !command || !commandText.trim()) return message.warning(command === 'complete' ? '请填写完成说明' : '请填写原因'); const id = selected.id; const version = selected.version; const text = commandText.trim(); const files = resultFiles.map(item => item.id); confirm(`确认${commandLabels[command]}？`, commandImpacts[command], () => run(() => command === 'reject' ? workOrderApi.reject(id, version, text) : command === 'withdraw' ? workOrderApi.withdraw(id, version, text) : command === 'complete' ? workOrderApi.complete(id, version, text, files) : command === 'terminate' ? workOrderApi.terminate(id, version, text) : workOrderApi.rework(id, version, text))) }
  const displayFieldValue = (field: NonNullable<WorkOrder['fields']>[number]) => {
    const value = selected?.values?.[field.key]
    if (field.type === 'attachment') {
      const ids = Array.isArray(value) ? value.map(Number) : []
      const files = (selected?.requestAttachments || []).filter(file => ids.includes(file.id))
      return files.length ? <Space direction="vertical" size={2}>{files.map(file => <Typography.Text key={file.id}>{file.name}</Typography.Text>)}</Space> : '-'
    }
    if (value && typeof value === 'object' && 'label' in value) return String((value as { label: unknown }).label)
    return value === undefined || value === null || value === '' ? '-' : String(value)
  }
  if (loading) return <section className="workspace-page"><Spin /></section>
  return <section className="workspace-page"><Card title={createMode ? '发起工单' : availableMode ? '可接工单' : '我的工单'} extra={!createMode && <Button icon={<ReloadOutlined />} onClick={() => void load()} aria-label="刷新工单" />}>
    {error && <Alert type="error" showIcon message={error} action={<Button onClick={() => void load()}>重试</Button>} />}
    {createMode ? <>
      <Select placeholder="选择工单类型" style={{ width: 'min(100%, 360px)', marginBottom: 16 }} onChange={code => workOrderApi.template(code).then(async item => { setTemplate(item); form.resetFields(); setRequestFiles([]); const [people, targetDepts, allDepts, allUsers, dictionaries, accountPage] = await Promise.all([workOrderApi.candidates(code), workOrderApi.candidateDepartments(code), workOrderApi.departments(), workOrderApi.users(), workOrderApi.dictionaries(), item.processorType === 'PRODUCTION_TICKET' ? workOrderApi.accounts() : Promise.resolve({ list: [], total: 0 })]); setCandidates(people.list); setDepartments(allDepts); setTargetDepartments(targetDepts.list.map(dept => ({ id: dept.id, name: dept.name }))); setUsers(allUsers); setAccounts(accountPage.list); setDictionaryOptions(dictionaries); setAssignmentType(item.allowedAssignmentTypes?.[0] === 'DEPARTMENT' ? 'DEPARTMENT' : 'PERSON') }).catch(cause => setError(cause instanceof Error ? cause.message : '模板加载失败'))} options={templates.map(item => ({ value: item.code, label: item.name }))} />
      {template && <Form form={form} layout="vertical" onFinish={async values => { try { const dynamic = serializeWorkOrderDynamicValues(template.fields || [], values); const attachmentIds = [...new Set([...requestFiles, ...dynamic.attachmentFiles].map(item => item.id))]; await workOrderApi.create({ sceneCode: template.code, relatedAccountId: values.relatedAccountId, targetUserId: assignmentType === 'PERSON' ? values.targetUserId : undefined, targetDeptId: assignmentType === 'DEPARTMENT' ? values.targetDeptId : undefined, remark: values.remark, values: dynamic.values, attachmentIds }); form.resetFields(); setRequestFiles([]); Modal.success({ title: '工单已发起' }) } catch (cause) { message.error(cause instanceof Error ? cause.message : '工单发起失败') } }}>
        {(template.allowedAssignmentTypes?.length || 0) > 1 && <Form.Item label="指派方式"><Select value={assignmentType} onChange={setAssignmentType} options={[{ value: 'PERSON', label: '指定人' }, { value: 'DEPARTMENT', label: '指定部门' }]} /></Form.Item>}
        {template.processorType === 'PRODUCTION_TICKET' && <Form.Item name="relatedAccountId" label="相关账号" rules={[{ required: true, message: '请选择相关账号' }]}><Select showSearch optionFilterProp="label" options={accounts.map(item => ({ value: item.id, label: `${item.platformLabelSnapshot || '平台'} · ${item.nickname || item.accountNo || item.id}` }))} /></Form.Item>}
        {assignmentType === 'PERSON' ? <Form.Item name="targetUserId" label="接收人" rules={[{ required: true, message: '请选择接收人' }]}><Select showSearch optionFilterProp="label" options={candidates.map(item => ({ value: item.id, label: item.name }))} /></Form.Item> : <Form.Item name="targetDeptId" label="接收部门" rules={[{ required: true, message: '请选择接收部门' }]}><Select showSearch optionFilterProp="label" options={targetDepartments.map(item => ({ value: item.id, label: item.name }))} /></Form.Item>}
        {template.fields?.map(field => <Form.Item key={field.key} name={field.key} label={field.label} rules={field.required ? [{ required: true, message: `请填写${field.label}` }] : undefined}>{field.type === 'attachment' ? <DynamicAttachmentField /> : field.type === 'textarea' ? <Input.TextArea rows={3} /> : field.type === 'number' ? <InputNumber style={{ width: '100%' }} /> : field.type === 'date' || field.type === 'datetime' ? <DatePicker showTime={field.type === 'datetime'} style={{ width: '100%' }} /> : field.type === 'user' ? <Select showSearch optionFilterProp="label" options={users.map(item => ({ value: item.id, label: item.nickname }))} /> : field.type === 'department' ? <Select showSearch optionFilterProp="label" options={departments.map(item => ({ value: item.id, label: item.name }))} /> : field.type === 'dictionary' ? <Select options={dictionaryOptions.filter(item => item.dictType === field.dictionaryType).map(item => ({ value: item.value, label: item.label }))} /> : <Input />}</Form.Item>)}
        <Form.Item name="remark" label="备注" rules={[{ required: true, message: '请填写备注' }]}><Input.TextArea rows={4} maxLength={2000} showCount /></Form.Item><Form.Item label="附件"><WorkOrderAttachmentPicker value={requestFiles} onChange={setRequestFiles} /></Form.Item><Button type="primary" htmlType="submit">发起工单</Button>
      </Form>}
      {!templates.length && <Empty description="暂无可发起的工单" />}
    </> : <>
      {!availableMode && <Tabs activeKey={mineView} items={views} onChange={setMineView} />}
      <List dataSource={orders} locale={{ emptyText: <Empty description="暂无工单" /> }} renderItem={item => <List.Item actions={item.businessType === 'PRODUCTION_TICKET' ? [<Button key="production" type="link" href={`/zsjos/production-tickets?ticketId=${item.businessId}`}>进入拍剪工单</Button>] : [<Button key="detail" type="link" onClick={() => workOrderApi.detail(item.id).then(setSelected).catch(cause => message.error(cause instanceof Error ? cause.message : '详情加载失败'))}>查看</Button>]}><List.Item.Meta title={<Space wrap>{item.orderNo}<Tag>{labels[item.status] || item.status}</Tag></Space>} description={`${item.sceneName || item.sceneCode} · 第 ${item.currentRound} 轮`} /></List.Item>} />
    </>}
    {selected && <Modal open title={selected.orderNo} width={720} footer={null} onCancel={() => setSelected(undefined)}><Descriptions column={1} items={[{ label: '状态', children: labels[selected.status] || selected.status }, { label: '发起人', children: selected.sourceName }, { label: '处理人', children: selected.targetName || '候选池' }, ...(selected.fields || []).map(field => ({ label: field.label, children: displayFieldValue(field) })), { label: '备注', children: selected.remark || '-' }, { label: '完成说明', children: selected.completionRemark || '-' }, { label: '轮次', children: selected.currentRound }]} /><Typography.Title level={5}>流转记录</Typography.Title><Timeline items={(selected.timeline || []).map(item => ({ children: <><strong>第 {item.roundNo || 1} 轮 · {item.operatorName || '系统'}</strong><div>{item.fromStatus ? `${labels[item.fromStatus] || item.fromStatus} → ` : ''}{labels[item.toStatus] || item.toStatus}</div>{(item.reason || item.resultRemark) && <Typography.Text type="secondary">{item.reason || item.resultRemark}</Typography.Text>}</>, label: item.operatedAt }))} /><Typography.Title level={5}>操作</Typography.Title><Space wrap>
      {actions.includes('take') && <Button onClick={() => void confirm('确认接单？', '接单后工单将进入处理中，操作不可撤销。', () => run(() => workOrderApi.take(selected.id, selected.version)))}>接单</Button>}
      {actions.includes('claim') && <Button type="primary" onClick={() => void confirm('确认认领？', '认领成功后其他候选人将无法接单，操作不可撤销。', () => run(() => workOrderApi.claim(selected.id, selected.version)))}>认领</Button>}
      {actions.includes('reject') && <Button danger onClick={() => setCommand('reject')}>拒单</Button>}{actions.includes('withdraw') && <Button danger onClick={() => setCommand('withdraw')}>撤回</Button>}{actions.includes('complete') && <Button type="primary" onClick={() => setCommand('complete')}>提交完成</Button>}
      {actions.includes('accept') && <Button type="primary" onClick={() => void confirm('确认验收通过？', '通过后工单将结束且不可撤销。', () => run(() => workOrderApi.accept(selected.id, selected.version)))}>通过</Button>}{actions.includes('terminate') && <Button danger onClick={() => setCommand('terminate')}>不合格终止</Button>}{actions.includes('return') && <Button onClick={() => setCommand('return')}>打回重做</Button>}
    </Space></Modal>}
    <Modal open={Boolean(command)} title={command ? commandLabels[command] : ''} okText="下一步" cancelText="取消" onCancel={() => { setCommand(undefined); setCommandText(''); setResultFiles([]) }} onOk={submitCommand}><Input.TextArea rows={5} maxLength={command === 'complete' ? 4000 : 1000} showCount value={commandText} onChange={event => setCommandText(event.target.value)} placeholder={command === 'complete' ? '填写本轮完成说明' : '填写原因'} />{command === 'complete' && <div style={{ marginTop: 16 }}><WorkOrderAttachmentPicker value={resultFiles} onChange={setResultFiles} /></div>}<Alert style={{ marginTop: 16 }} type="warning" showIcon message={command ? commandImpacts[command] : ''} /></Modal>
  </Card></section>
}
