package cn.iocoder.yudao.module.zsjos.controller.admin.studentops;
import cn.iocoder.yudao.framework.common.pojo.CommonResult; import cn.iocoder.yudao.framework.common.util.object.BeanUtils; import cn.iocoder.yudao.module.zsjos.controller.admin.studentops.vo.*; import cn.iocoder.yudao.module.zsjos.service.studentops.StudentOpsService; import jakarta.annotation.Resource; import jakarta.validation.Valid; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import java.util.List; import static cn.iocoder.yudao.framework.common.pojo.CommonResult.success; import static cn.iocoder.yudao.framework.security.core.util.SecurityFrameworkUtils.getLoginUserId;
@RestController @RequestMapping("/zsjos/student-ops") public class StudentOpsController { @Resource private StudentOpsService service; @Resource private cn.iocoder.yudao.module.zsjos.service.studentops.GraduationService graduationService;
 @GetMapping("/exceptions") @PreAuthorize("@ss.hasPermission('zsjos:student-ops:query')") public CommonResult<List<ExceptionTicketRespVO>> exceptions(){return success(service.exceptions(getLoginUserId()));}
 @PostMapping("/exceptions/create") @PreAuthorize("@ss.hasPermission('zsjos:student-ops:create-exception')") public CommonResult<Long> createException(@Valid @RequestBody ExceptionTicketSaveReqVO req){return success(service.createException(req));}
 @PostMapping("/exceptions/{id}/resolve") @PreAuthorize("@ss.hasPermission('zsjos:student-ops:resolve-exception')") public CommonResult<Boolean> resolve(@PathVariable Long id,@RequestParam Integer version,@RequestParam String resolution){service.resolve(id,version,resolution);return success(true);}
 @GetMapping("/assessments") @PreAuthorize("@ss.hasPermission('zsjos:student-ops:query')") public CommonResult<List<CooperationAssessmentRespVO>> assessments(){return success(service.assessments(getLoginUserId()).stream().map(x->BeanUtils.toBean(x,CooperationAssessmentRespVO.class)).toList());}
 @PostMapping("/assessments/create") @PreAuthorize("@ss.hasPermission('zsjos:student-ops:assess')") public CommonResult<Long> assess(@Valid @RequestBody CooperationAssessmentSaveReqVO req){return success(service.assess(req,getLoginUserId()));}
 @GetMapping("/graduations") @PreAuthorize("@ss.hasPermission('zsjos:student-ops:query')") public CommonResult<List<GraduationRespVO>> graduations(){return success(graduationService.list(getLoginUserId()));}
 @PostMapping("/graduations/create") @PreAuthorize("@ss.hasPermission('zsjos:student-ops:graduate')") public CommonResult<Long> graduate(@Valid @RequestBody GraduationCreateReqVO req){return success(graduationService.create(req,getLoginUserId()));}
}
