package cn.iocoder.yudao.module.zsjos.service.bpm.content.provider;
import cn.iocoder.yudao.module.bpm.api.approvalcontent.*; import cn.iocoder.yudao.module.bpm.api.approvalcontent.vo.*; import cn.iocoder.yudao.module.zsjos.dal.dataobject.account.*; import cn.iocoder.yudao.module.zsjos.dal.mysql.account.*; import cn.iocoder.yudao.module.zsjos.service.account.MediaAccountObjectPermissionProvider; import jakarta.annotation.Resource; import org.springframework.stereotype.Component; import java.util.*;
@Component public class MediaAccountDeleteContentProvider implements BpmApprovalContentProvider {
 private static final String PREFIX="media-account-delete:"; @Resource private MediaAccountDeleteRequestMapper requests; @Resource private MediaAccountMapper accounts; @Resource private MediaAccountObjectPermissionProvider perms;
 public String bizType(){return "media_account_delete";} public String businessKeyPrefix(){return PREFIX;} public String parseBusinessId(String k){return BpmApprovalBusinessKey.idSegment(BpmApprovalBusinessKey.strip(PREFIX,k));}
 public BpmApprovalBriefVO brief(String id,Long viewer){ MediaAccountDeleteRequestDO r=load(id); if(r==null)return null; var v=new BpmApprovalBriefVO(); v.setBizType(bizType()); v.setTitle("删除账号 · "+id); v.setSubtitle("主管审批"); v.setFields(List.of(BpmApprovalFieldVO.of("删除原因",r.getReason()),BpmApprovalFieldVO.of("审批状态",r.getStatus()))); return v; }
 public BpmApprovalDetailVO detail(String id,Long viewer){ MediaAccountDeleteRequestDO r=load(id); if(r==null)return null; var d=new BpmApprovalDetailVO(); d.setBizType(bizType()); d.setTitle("删除账号 · "+id); d.setStatusText(r.getStatus()); var g=new BpmApprovalDetailVO.Group(); g.setTitle("删除申请快照"); g.setFields(new ArrayList<>(List.of(BpmApprovalFieldVO.of("账号ID",String.valueOf(r.getAccountId())),BpmApprovalFieldVO.of("申请原因",r.getReason()),BpmApprovalFieldVO.of("申请人",String.valueOf(r.getRequestedByUserId())),BpmApprovalFieldVO.of("审批人",String.valueOf(r.getReviewerUserId()))))); d.getGroups().add(g); return d; }
 private MediaAccountDeleteRequestDO load(String id){try{return requests.byAccount(Long.valueOf(id));}catch(Exception e){return null;}}
}
