# -*- coding: utf-8 -*-
from pathlib import Path
from tempfile import gettempdir
from playwright.sync_api import sync_playwright, expect

with sync_playwright() as p:
    browser = p.chromium.launch(channel='chrome', headless=True)
    page = browser.new_page(viewport={'width': 1440, 'height': 900})
    errors = []
    page.on('pageerror', lambda error: errors.append(str(error)))
    url = 'http://127.0.0.1:81/test/student-partner-binding.html'
    page.goto(url)
    page.get_by_role('button', name='详情', exact=True).first.click()
    page.get_by_role('button', name='绑定已有兼职账号', exact=True).click()
    modal = page.get_by_role('dialog', name='绑定已有兼职账号', exact=True)
    expect(modal.get_by_text('P-1', exact=True)).to_be_visible()
    expect(modal.get_by_role('button', name='确认绑定')).to_be_disabled()
    modal.get_by_role('listitem', name='page 2').click()
    expect(modal.get_by_text('P-11', exact=True)).to_be_visible()
    modal.get_by_label('搜索兼职账号').fill('测试兼职2')
    modal.get_by_role('button', name='搜索', exact=True).click()
    expect(modal.get_by_text('P-2', exact=True)).to_be_visible()
    modal.locator('label.el-radio').click()
    modal.get_by_label('绑定说明').fill('已核对身份')
    page.evaluate("bindingFixture.mode='conflict'")
    modal.get_by_role('button', name='确认绑定').click()
    expect(modal.get_by_text('兼职账号或学员已绑定其他身份', exact=True)).to_be_visible()
    page.screenshot(path=str(Path(gettempdir()) / 'admin-binding-desktop.png'))
    page.evaluate("bindingFixture.mode='bind-denied'")
    modal.get_by_role('button', name='确认绑定').click()
    expect(modal.get_by_text('无权操作该学员', exact=True)).to_be_visible()
    page.evaluate("bindingFixture.mode='success'; bindingFixture.delay=500")
    modal.get_by_role('button', name='确认绑定').click()
    expect(modal.get_by_role('button', name='取消')).to_be_disabled()
    expect(modal).not_to_be_visible()
    expect(page.locator('.el-descriptions').get_by_text('P-2', exact=True)).to_be_visible()
    assert page.evaluate('bindingFixture.lastBinding') == {'partnerId': 2, 'studentPersonId': 1, 'reason': '已核对身份'}
    assert page.evaluate('bindingFixture.writes') == 3
    expect(page.get_by_role('button', name='绑定已有兼职账号', exact=True)).to_have_count(0)

    page.goto(url)
    page.evaluate("bindingFixture.mode='status-error'")
    page.get_by_role('button', name='详情', exact=True).first.click()
    expect(page.locator('.el-drawer').get_by_text('绑定状态加载失败', exact=True)).to_be_visible()
    expect(page.get_by_role('button', name='绑定已有兼职账号', exact=True)).to_have_count(0)
    page.evaluate("bindingFixture.mode='success'")
    page.get_by_role('button', name='重试加载绑定状态').click()
    page.evaluate("bindingFixture.mode='list-error'")
    page.get_by_role('button', name='绑定已有兼职账号', exact=True).click()
    expect(modal.get_by_text('兼职列表加载失败', exact=True)).to_be_visible()
    page.evaluate("bindingFixture.mode='empty'")
    modal.get_by_role('button', name='重试加载兼职').click()
    expect(modal.get_by_text('没有找到兼职账号，请调整搜索条件')).to_be_visible()
    page.evaluate("bindingFixture.mode='success'")
    modal.get_by_role('button', name='搜索', exact=True).click()
    expect(modal.get_by_text('P-1', exact=True)).to_be_visible()
    page.set_viewport_size({'width': 390, 'height': 720})
    page.screenshot(path=str(Path(gettempdir()) / 'admin-binding-mobile.png'))
    expect(modal.get_by_role('button', name='确认绑定')).to_be_in_viewport()
    modal.get_by_role('button', name='取消', exact=True).click()
    page.set_viewport_size({'width': 1440, 'height': 900})
    page.locator('.el-drawer').get_by_role('button', name='Close this dialog').click()
    page.evaluate("bindingFixture.mode='success'; bindingFixture.bound=true; bindingFixture.delay=1200")
    page.get_by_role('button', name='详情', exact=True).first.click()
    page.locator('.el-drawer').get_by_role('button', name='Close this dialog').click()
    page.evaluate("bindingFixture.bound=false; bindingFixture.delay=0")
    page.get_by_role('button', name='详情', exact=True).nth(1).click()
    expect(page.get_by_role('button', name='绑定已有兼职账号', exact=True)).to_be_visible()
    page.wait_for_timeout(1400)
    expect(page.locator('.el-descriptions').get_by_text('P-2', exact=True)).to_have_count(0)
    page.get_by_role('button', name='绑定已有兼职账号', exact=True).click()
    expect(modal.get_by_text('绑定学员：测试学员2（13800000000）', exact=True)).to_be_visible()
    page.goto(url + '?no-permission')
    page.get_by_role('button', name='详情', exact=True).first.click()
    expect(page.get_by_text('课程服务', exact=True)).to_be_visible()
    expect(page.get_by_role('button', name='绑定已有兼职账号', exact=True)).to_have_count(0)
    assert not errors, errors
    browser.close()
    print('PASS Admin binding: status/search/paging/success/conflict/retry/empty/permission/mobile')
