package cn.iocoder.yudao.module.zsjos.service.positioning;
import cn.iocoder.yudao.framework.common.util.object.BeanUtils; import cn.iocoder.yudao.framework.tenant.core.context.TenantContextHolder; import cn.iocoder.yudao.module.zsjos.controller.admin.positioning.vo.*; import cn.iocoder.yudao.module.zsjos.dal.dataobject.positioning.*; import cn.iocoder.yudao.module.zsjos.dal.mysql.account.MediaAccountMapper; import cn.iocoder.yudao.module.zsjos.dal.mysql.positioning.*; import cn.iocoder.yudao.module.zsjos.framework.permission.ZsjosPermission; import jakarta.annotation.Resource; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*; import static cn.iocoder.yudao.framework.common.exception.util.ServiceExceptionUtil.exception; import static cn.iocoder.yudao.module.zsjos.enums.ZsjosErrorCodeConstants.*;
@Service public class PositioningWorkspaceService { @Resource private PositioningCardService cardService; @Resource private PositioningCardVersionMapper versionMapper; @Resource private InterviewRecordMapper interviewMapper; @Resource private PositioningExecCardMapper execMapper; @Resource private MediaAccountMapper accountMapper;
 public List<PositioningCardVersionDO> versions(Long cardId,Long uid){cardService.get(cardId,uid);return versionMapper.selectByCard(cardId);} @Transactional public Long createVersion(PositioningVersionCreateReqVO req,Long uid){var card=cardService.require(req.getPositioningCardId()); PositioningCardVersionDO x=BeanUtils.toBean(req,PositioningCardVersionDO.class); Integer expected=card.getVersionNo()==null?0:card.getVersionNo(); x.setVersionNo(expected+1);x.setProposedByUserId(uid);x.setAdopted(false);versionMapper.insert(x); Long tenantId=TenantContextHolder.getTenantId(); int updated=tenantId==null?0:cardService.advanceVersionNo(card.getId(),card.getVersion(),expected); if(tenantId==null) updated=cardService.advanceVersionNoWithoutTenant(card.getId(),card.getVersion(),expected); if(updated==0)throw exception(POSITIONING_CARD_VERSION_CONFLICT); return x.getId();}
 @Transactional public Long importInterview(InterviewImportReqVO req,Long uid){var account=accountMapper.selectById(req.getAccountId());if(account==null||(!Objects.equals(account.getDirectorUserId(),uid)&&!Objects.equals(account.getOwnerOperatorUserId(),uid)))throw exception(POSITIONING_CARD_PERMISSION_DENIED);InterviewRecordDO x=BeanUtils.toBean(req,InterviewRecordDO.class);x.setDirectorUserId(uid);x.setImportedAt(LocalDateTime.now());x.setConfirmed(false);x.setStatus("imported");x.setVersion(0);interviewMapper.insert(x);return x.getId();} public List<InterviewRecordDO> interviews(Long accountId, Long uid){var account=accountMapper.selectById(accountId);if(account==null||(!Objects.equals(account.getDirectorUserId(),uid)&&!Objects.equals(account.getOwnerOperatorUserId(),uid)))throw exception(POSITIONING_CARD_PERMISSION_DENIED);return interviewMapper.selectByAccount(accountId);} @Transactional public void confirmInterview(Long id,Integer version){if(interviewMapper.confirm(id,version)==0)throw exception(POSITIONING_CARD_VERSION_CONFLICT);}
 @Transactional public Long createExecCard(Long cardId,String executionJson,Long uid){var card=cardService.require(cardId);PositioningExecCardDO existing=execMapper.selectByCard(cardId);if(existing!=null)return existing.getId();PositioningExecCardDO x=new PositioningExecCardDO();x.setExecCardNo("EC-"+UUID.randomUUID().toString().replace("-","").substring(0,16));x.setAccountId(card.getAccountId());x.setPositioningCardId(cardId);x.setExecutionJson(executionJson);x.setReviewDueAt(LocalDateTime.now().plusDays(14));x.setStatus("pending_signatures");x.setVersion(0);execMapper.insert(x);return x.getId();}
 public PositioningExecCardRespVO getExecCard(Long cardId,Long uid){cardService.get(cardId,uid);PositioningExecCardDO x=execMapper.selectByCard(cardId);if(x==null)return null;var v=BeanUtils.toBean(x,PositioningExecCardRespVO.class);List<String> a=new ArrayList<>();if(x.getDirectorConfirmedAt()==null)a.add("director-sign");if(x.getOperatorConfirmedAt()==null)a.add("operator-sign");v.setAvailableActions(a);return v;}
 @Transactional public void signDirector(Long cardId,Integer version,String snapshot,Long uid){var card=cardService.require(cardId);if(!Objects.equals(uid,card.getDirectorUserId()))throw exception(POSITIONING_CARD_PERMISSION_DENIED);signEmployee(cardId,version,snapshot,true);}
 @Transactional public void signOperator(Long cardId,Integer version,String snapshot,Long uid){var card=cardService.require(cardId);var account=accountMapper.selectById(card.getAccountId());if(account==null||!Objects.equals(uid,account.getOwnerOperatorUserId()))throw exception(POSITIONING_CARD_PERMISSION_DENIED);signEmployee(cardId,version,snapshot,false);}
 private void signEmployee(Long cardId,Integer version,String snapshot,boolean director){PositioningExecCardDO x=execMapper.selectByCard(cardId);if(x==null||!Objects.equals(x.getVersion(),version)||!"pending_signatures".equals(x.getStatus()))throw exception(POSITIONING_CARD_STATE_INVALID);int updated=director?execMapper.signDirector(x.getId(),version,LocalDateTime.now(),snapshot,false):execMapper.signOperator(x.getId(),version,LocalDateTime.now(),snapshot);if(updated==0)throw exception(POSITIONING_CARD_VERSION_CONFLICT);}
}
