package cn.iocoder.yudao.module.zsjos.service.employeereminder;
import cn.iocoder.yudao.module.system.api.notify.*; import cn.iocoder.yudao.module.system.api.notify.dto.*; import org.springframework.stereotype.Component; import java.util.*;
@Component public class EmployeeReminderNotifySceneProvider implements NotifySceneProvider {
  private static final String ROLE="employee_reminder_recipient";
  public List<NotifySceneRespDTO> getScenes(){ return List.of(scene("hrm.employee.contract_expiry","员工合同到期提醒",List.of(new NotifySceneVariableRespDTO("employee.name","员工姓名",false),new NotifySceneVariableRespDTO("employee.department","员工部门",false),new NotifySceneVariableRespDTO("employee.contractEndDate","合同到期日",false))),scene("hrm.employee.entry_anniversary","员工入职周年提醒",List.of(new NotifySceneVariableRespDTO("employee.name","员工姓名",false),new NotifySceneVariableRespDTO("employee.department","员工部门",false),new NotifySceneVariableRespDTO("employee.anniversaryDate","周年日期",false),new NotifySceneVariableRespDTO("employee.anniversaryYears","周年年数",false)))); }
  private NotifySceneRespDTO scene(String code,String name,List<NotifySceneVariableRespDTO> vars){ return new NotifySceneRespDTO(code,name,vars,List.of(new NotifySceneRoleRespDTO(ROLE,"员工提醒接收人")),List.of(NotifyActionType.MESSAGE_DETAIL),false); }
  public Set<NotifyRecipientDTO> resolveRecipients(NotifyBusinessEvent event,Set<String> roles){ if(!roles.contains(ROLE)) return Set.of(); Object id=event.getPayload().get("recipientUserId"); return id instanceof Number n?Set.of(NotifyRecipientDTO.admin(n.longValue())):Set.of(); }
  public Map<String,Object> resolveVariables(NotifyBusinessEvent event,NotifyRecipientDTO recipient){ Map<String,Object> v=new LinkedHashMap<>(); v.put("employee.name",event.getPayload().get("employeeName")); v.put("employee.department",event.getPayload().get("departmentName")); v.put("employee.contractEndDate",event.getPayload().get("contractEndDate")); v.put("employee.anniversaryDate",event.getPayload().get("anniversaryDate")); v.put("employee.anniversaryYears",event.getPayload().get("anniversaryYears")); return v; }
}
