-- EAM 单元测试用建表语句（H2，MySQL 兼容模式）
-- 与 script/sql/mysql/schema/eam.sql 结构对应，去掉 MySQL 专有语法。

CREATE TABLE IF NOT EXISTS "eam_category" (
    "id"          bigint       NOT NULL AUTO_INCREMENT,
    "parent_id"   bigint       NOT NULL DEFAULT 0,
    "name"        varchar(100) NOT NULL,
    "code"        varchar(50)  NOT NULL,
    "sort"        int          NOT NULL DEFAULT 0,
    "status"      tinyint      NOT NULL DEFAULT 0,
    "management_mode" tinyint  NOT NULL DEFAULT 1,
    "unit"        varchar(20)  NOT NULL DEFAULT '个',
    "remark"      varchar(500)          DEFAULT NULL,
    "creator"     varchar(64)           DEFAULT '',
    "create_time" timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"     varchar(64)           DEFAULT '',
    "update_time" timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"     bit          NOT NULL DEFAULT FALSE,
    "tenant_id"   bigint       NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "eam_category_field" (
    "id"          bigint       NOT NULL AUTO_INCREMENT,
    "category_id" bigint       NOT NULL,
    "field_key"   varchar(50)  NOT NULL,
    "field_name"  varchar(100) NOT NULL,
    "field_type"  tinyint      NOT NULL,
    "options"     varchar(2000)         DEFAULT NULL,
    "option_source" varchar(30) DEFAULT NULL,
    "dict_type" varchar(100) DEFAULT NULL,
    "required"    bit          NOT NULL DEFAULT FALSE,
    "admin_visible" bit        NOT NULL DEFAULT TRUE,
    "collection_visible" bit   NOT NULL DEFAULT TRUE,
    "collection_required" bit  NOT NULL DEFAULT FALSE,
    "condition_rule" varchar(2000) DEFAULT NULL,
    "sort"        int          NOT NULL DEFAULT 0,
    "creator"     varchar(64)           DEFAULT '',
    "create_time" timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"     varchar(64)           DEFAULT '',
    "update_time" timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"     bit          NOT NULL DEFAULT FALSE,
    "tenant_id"   bigint       NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "eam_asset" (
    "id"              bigint        NOT NULL AUTO_INCREMENT,
    "asset_code"      varchar(64)   NOT NULL,
    "name"            varchar(200)  NOT NULL,
    "category_id"     bigint        NOT NULL,
    "management_mode" tinyint       NOT NULL DEFAULT 1,
    "quantity"        int           NOT NULL DEFAULT 1,
    "unit"            varchar(20)   NOT NULL DEFAULT '个',
    "status"          tinyint       NOT NULL DEFAULT 0,
    "previous_status" tinyint                DEFAULT NULL,
    "brand"           varchar(100)           DEFAULT NULL,
    "specification"   varchar(255)           DEFAULT NULL,
    "sn"              varchar(100)           DEFAULT NULL,
    "barcode"         varchar(128)           DEFAULT NULL,
    "original_value"  decimal(12, 2)         DEFAULT NULL,
    "net_value"       decimal(12, 2)         DEFAULT NULL,
    "purchase_date"   date                   DEFAULT NULL,
    "source"          tinyint                DEFAULT NULL,
    "source_label_snapshot" varchar(100)     DEFAULT NULL,
    "warranty_date"   date                   DEFAULT NULL,
    "use_dept_id"     bigint                 DEFAULT NULL,
    "use_user_id"     bigint                 DEFAULT NULL,
    "location"        varchar(255)           DEFAULT NULL,
    "expected_life"   int                    DEFAULT NULL,
    "remark"          varchar(500)           DEFAULT NULL,
    "file_urls"       varchar(2000)          DEFAULT NULL,
    "ext_fields"      varchar(4000)          DEFAULT NULL,
    "ext_field_labels" varchar(4000)         DEFAULT NULL,
    "ext_field_dict_types" varchar(4000)     DEFAULT NULL,
    "creator"         varchar(64)            DEFAULT '',
    "create_time"     timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"         varchar(64)            DEFAULT '',
    "update_time"     timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"         bit           NOT NULL DEFAULT FALSE,
    "tenant_id"       bigint        NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "eam_asset_import_batch" (
    "id" bigint NOT NULL AUTO_INCREMENT,
    "file_hash" char(64) NOT NULL,
    "file_name" varchar(255) NOT NULL,
    "sheet_name" varchar(100) NOT NULL,
    "total_rows" int NOT NULL DEFAULT 0,
    "create_count" int NOT NULL DEFAULT 0,
    "update_count" int NOT NULL DEFAULT 0,
    "skip_count" int NOT NULL DEFAULT 0,
    "warning_count" int NOT NULL DEFAULT 0,
    "operator_id" bigint DEFAULT NULL,
    "creator" varchar(64) DEFAULT '', "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '', "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE, "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "eam_asset_import_row" (
    "id" bigint NOT NULL AUTO_INCREMENT,
    "batch_id" bigint NOT NULL,
    "file_hash" char(64) NOT NULL,
    "sheet_name" varchar(100) NOT NULL,
    "row_num" int NOT NULL,
    "asset_id" bigint NOT NULL,
    "asset_code" varchar(64) NOT NULL,
    "import_action" tinyint NOT NULL,
    "creator" varchar(64) DEFAULT '', "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '', "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE, "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "eam_asset_change_log" (
    "id"             bigint       NOT NULL AUTO_INCREMENT,
    "asset_id"       bigint       NOT NULL,
    "change_type"    tinyint      NOT NULL,
    "before_status"  tinyint               DEFAULT NULL,
    "after_status"   tinyint               DEFAULT NULL,
    "before_user_id" bigint                DEFAULT NULL,
    "after_user_id"  bigint                DEFAULT NULL,
    "before_dept_id" bigint                DEFAULT NULL,
    "after_dept_id"  bigint                DEFAULT NULL,
    "biz_id"         bigint                DEFAULT NULL,
    "content"        varchar(500)          DEFAULT NULL,
    "operator_id"    bigint                DEFAULT NULL,
    "operate_time"   timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "creator"        varchar(64)           DEFAULT '',
    "create_time"    timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"        varchar(64)           DEFAULT '',
    "update_time"    timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"        bit          NOT NULL DEFAULT FALSE,
    "tenant_id"      bigint       NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "eam_transfer" (
    "id"                   bigint      NOT NULL AUTO_INCREMENT,
    "no"                   varchar(64) NOT NULL,
    "type"                 tinyint     NOT NULL,
    "asset_id"             bigint      NOT NULL,
    "from_user_id"         bigint               DEFAULT NULL,
    "from_dept_id"         bigint               DEFAULT NULL,
    "to_user_id"           bigint               DEFAULT NULL,
    "to_dept_id"           bigint               DEFAULT NULL,
    "expected_return_date" date                 DEFAULT NULL,
    "actual_return_date"   date                 DEFAULT NULL,
    "status"               tinyint     NOT NULL DEFAULT 0,
    "process_instance_id"  varchar(64)          DEFAULT NULL,
    "reason"               varchar(500)         DEFAULT NULL,
    "apply_user_id"        bigint               DEFAULT NULL,
    "apply_time"           timestamp            DEFAULT NULL,
    "creator"              varchar(64)          DEFAULT '',
    "create_time"          timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"              varchar(64)          DEFAULT '',
    "update_time"          timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"              bit         NOT NULL DEFAULT FALSE,
    "tenant_id"            bigint      NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "eam_inventory" (
    "id"             bigint       NOT NULL AUTO_INCREMENT,
    "no"             varchar(64)  NOT NULL,
    "name"           varchar(200) NOT NULL,
    "scope_type"     tinyint      NOT NULL,
    "scope_value"    varchar(500)          DEFAULT NULL,
    "status"         tinyint      NOT NULL DEFAULT 0,
    "total_count"    int          NOT NULL DEFAULT 0,
    "checked_count"  int          NOT NULL DEFAULT 0,
    "normal_count"   int          NOT NULL DEFAULT 0,
    "abnormal_count" int          NOT NULL DEFAULT 0,
    "start_time"     timestamp             DEFAULT NULL,
    "end_time"       timestamp             DEFAULT NULL,
    "remark"         varchar(500)          DEFAULT NULL,
    "creator"        varchar(64)           DEFAULT '',
    "create_time"    timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"        varchar(64)           DEFAULT '',
    "update_time"    timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"        bit          NOT NULL DEFAULT FALSE,
    "tenant_id"      bigint       NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "eam_inventory_detail" (
    "id"              bigint       NOT NULL AUTO_INCREMENT,
    "inventory_id"    bigint       NOT NULL,
    "asset_id"        bigint       NOT NULL,
    "expect_user_id"  bigint                DEFAULT NULL,
    "expect_dept_id"  bigint                DEFAULT NULL,
    "expect_location" varchar(255)          DEFAULT NULL,
    "actual_user_id"  bigint                DEFAULT NULL,
    "actual_dept_id"  bigint                DEFAULT NULL,
    "actual_location" varchar(255)          DEFAULT NULL,
    "result"          tinyint      NOT NULL DEFAULT 0,
    "remark"          varchar(500)          DEFAULT NULL,
    "check_user_id"   bigint                DEFAULT NULL,
    "check_time"      timestamp             DEFAULT NULL,
    "creator"         varchar(64)           DEFAULT '',
    "create_time"     timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"         varchar(64)           DEFAULT '',
    "update_time"     timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"         bit          NOT NULL DEFAULT FALSE,
    "tenant_id"       bigint       NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "eam_repair" (
    "id"            bigint        NOT NULL AUTO_INCREMENT,
    "asset_id"      bigint        NOT NULL,
    "fault_desc"    varchar(500)  NOT NULL,
    "repair_vendor" varchar(200)           DEFAULT NULL,
    "cost"          decimal(10, 2)         DEFAULT NULL,
    "start_time"    timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "end_time"      timestamp              DEFAULT NULL,
    "result"        varchar(500)           DEFAULT NULL,
    "creator"       varchar(64)            DEFAULT '',
    "create_time"   timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"       varchar(64)            DEFAULT '',
    "update_time"   timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"       bit           NOT NULL DEFAULT FALSE,
    "tenant_id"     bigint        NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "eam_scrap" (
    "id"                  bigint      NOT NULL AUTO_INCREMENT,
    "no"                  varchar(64) NOT NULL,
    "asset_id"            bigint      NOT NULL,
    "reason_type"         tinyint     NOT NULL,
    "reason"              varchar(500)         DEFAULT NULL,
    "scrap_date"          date                 DEFAULT NULL,
    "status"              tinyint     NOT NULL DEFAULT 0,
    "process_instance_id" varchar(64)          DEFAULT NULL,
    "apply_user_id"       bigint               DEFAULT NULL,
    "apply_time"          timestamp            DEFAULT NULL,
    "creator"             varchar(64)          DEFAULT '',
    "create_time"         timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"             varchar(64)          DEFAULT '',
    "update_time"         timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"             bit         NOT NULL DEFAULT FALSE,
    "tenant_id"           bigint      NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "eam_code_rule" (
    "id"                bigint      NOT NULL AUTO_INCREMENT,
    "category_id"       bigint               DEFAULT NULL,
    "prefix"            varchar(20)          DEFAULT NULL,
    "use_category_code" bit         NOT NULL DEFAULT FALSE,
    "date_format"       varchar(20)          DEFAULT NULL,
    "serial_length"     int         NOT NULL DEFAULT 4,
    "separator"         varchar(5)           DEFAULT '-',
    "current_serial"    bigint      NOT NULL DEFAULT 0,
    "creator"           varchar(64)          DEFAULT '',
    "create_time"       timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"           varchar(64)          DEFAULT '',
    "update_time"       timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"           bit         NOT NULL DEFAULT FALSE,
    "tenant_id"         bigint      NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);
