package cn.iocoder.yudao.module.zsjos.controller.admin.positioning;
import cn.iocoder.yudao.framework.common.pojo.CommonResult; import cn.iocoder.yudao.framework.common.util.object.BeanUtils; import cn.iocoder.yudao.module.zsjos.controller.admin.positioning.vo.*; import cn.iocoder.yudao.module.zsjos.service.positioning.PositioningWorkspaceService; import jakarta.annotation.Resource; import jakarta.validation.Valid; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import java.util.List; import static cn.iocoder.yudao.framework.common.pojo.CommonResult.success; import static cn.iocoder.yudao.framework.security.core.util.SecurityFrameworkUtils.getLoginUserId;
@RestController @RequestMapping("/zsjos/positioning/workspace") public class PositioningWorkspaceController { @Resource private PositioningWorkspaceService service;
 @GetMapping("/versions") @PreAuthorize("@ss.hasPermission('zsjos:positioning-card:query')") public CommonResult<List<PositioningVersionRespVO>> versions(@RequestParam Long cardId){return success(service.versions(cardId,getLoginUserId()).stream().map(x->BeanUtils.toBean(x,PositioningVersionRespVO.class)).toList());}
 @PostMapping("/versions/create") @PreAuthorize("@ss.hasPermission('zsjos:positioning-card:edit')") public CommonResult<Long> createVersion(@Valid @RequestBody PositioningVersionCreateReqVO req){return success(service.createVersion(req,getLoginUserId()));}
 @PostMapping("/interviews/import") @PreAuthorize("@ss.hasPermission('zsjos:positioning-card:edit')") public CommonResult<Long> importInterview(@Valid @RequestBody InterviewImportReqVO req){return success(service.importInterview(req,getLoginUserId()));}
 @GetMapping("/interviews") @PreAuthorize("@ss.hasPermission('zsjos:positioning-card:query')") public CommonResult<List<InterviewRecordRespVO>> interviews(@RequestParam Long accountId){return success(service.interviews(accountId,getLoginUserId()).stream().map(x->BeanUtils.toBean(x,InterviewRecordRespVO.class)).toList());}
 @PostMapping("/interviews/{id}/confirm") @PreAuthorize("@ss.hasPermission('zsjos:positioning-card:edit')") public CommonResult<Boolean> confirmInterview(@PathVariable Long id,@RequestParam Integer version){service.confirmInterview(id,version);return success(true);}
 @PostMapping("/exec-card/create") @PreAuthorize("@ss.hasPermission('zsjos:positioning-card:edit')") public CommonResult<Long> createExec(@RequestParam Long cardId,@RequestBody String executionJson){return success(service.createExecCard(cardId,executionJson,getLoginUserId()));}
 @GetMapping("/exec-card") @PreAuthorize("@ss.hasPermission('zsjos:positioning-card:query')") public CommonResult<PositioningExecCardRespVO> exec(@RequestParam Long cardId){return success(service.getExecCard(cardId,getLoginUserId()));}
 @PostMapping("/exec-card/director-sign") @PreAuthorize("@ss.hasPermission('zsjos:positioning-card:sign')") public CommonResult<Boolean> directorSign(@RequestParam Long cardId,@RequestParam Integer version,@RequestBody String snapshot){service.signDirector(cardId,version,snapshot,getLoginUserId());return success(true);}
 @PostMapping("/exec-card/operator-sign") @PreAuthorize("@ss.hasPermission('zsjos:positioning-card:sign')") public CommonResult<Boolean> operatorSign(@RequestParam Long cardId,@RequestParam Integer version,@RequestBody String snapshot){service.signOperator(cardId,version,snapshot,getLoginUserId());return success(true);}
}
